title: IOCCC日本語ネタバレ解説
email: mame@ruby-lang.org
description: >-
  難読C言語コードのコンテスト、IOCCCの全作品を日本語で紹介することを目指すサイトです。

twitter:
  username: mametter

baseurl: "/ioccc-ja-spoilers"
url: "http://mame.github.io"

sass:
  style: compressed
  sass_dir: _sass

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

defaults:
  - scope:
      path: ""
    values:
      layout: "entry"
