#define x =
#define double(a,b) int
#define char k[&#39;a&#39;]
#define union static struct

extern int floor;
double (x1, y1) b,
char x {sizeof(
    double(%s,%D)(*)())
,};
struct tag{int x0,*xO;}

*main(i, dup, signal) {
{
  for(signal=0;*k *x * __FILE__ *i;) do {
   (printf(&amp;*&quot;&#39;\&quot;,x);	/*\n\\&quot;, (*((double(tag,u)(*)())&amp;floor))(i)));
	goto _0;

_O: while (!(char &lt;&lt;x - dup)) {	/*/*\*/
	union tag u x{4};
  }
}


while(b x 3, i); {
char x b,i;
  _0:if(b&amp;&amp;k+
  sin(signal)		/ *    ((main) (b)-&gt; xO));/*}
  ;
}

*/}}}