#define C_C_(_)~&#39; &#39;&amp;_
#define _C_C(_)(&#39;\b&#39;b&#39;\b&#39;&gt;=C_C&gt;&#39;\t&#39;b&#39;\n&#39;)
#define C_C _|_
#define b *
#define C /b/
#define V _C_C(
main(C,V)
char **V;
/*	C program. (If you don&#39;t
 *	understand it look it
 */	up.) (In the C Manual)
{
	char _,__; 
	while (read(0,&amp;__,1) &amp; write((_=(_=C_C_(__),C)),
	_C_,1)) _=C-V+subr(&amp;V);
}
subr(C)
char *C;
{
	C=&quot;Lint says &quot;argument Manual isn&#39;t used.&quot;  What&#39;s that
	mean?&quot;; while (write((read(C_C(&#39;&quot;&#39;-&#39;/*&quot;&#39;/*&quot;*/))?__:__-_+
	&#39;\b&#39;b&#39;\b&#39;|((_-52)%(&#39;\b&#39;b&#39;\b&#39;+C_C_(&#39;\t&#39;b&#39;\n&#39;))+1),1),&amp;_,1));
}