#define p struct c
#define q struct b
#define h a-&gt;a
#define i a-&gt;b
#define e i-&gt;c
#define o a=(*b-&gt;a)(b-&gt;b,b-&gt;c)
#define s return a;}q*
#define n (d,b)p*b;{q*a;p*c;
#define z(t)(t*)malloc(sizeof(t))
q{int a;p{q*(*a)();int b;p*c;}*b;};q*u n a=z(q);h=d;i=z(p);i-&gt;a=u;i-&gt;b=d+1;s
v n c=b;do o,b=i;while(!(h%d));i=c;i-&gt;a=v;i-&gt;b=d;e=b;s
w n o;c=i;i=b;i-&gt;a=w;e=z(p);e-&gt;a=v;e-&gt;b=h;e-&gt;c=c;s
t n for(;;)o,main(-h),b=i;}main(b){p*a;if(b&gt;0)a=z(p),h=w,a-&gt;c=z(p),a-&gt;c-&gt;a=u,
a-&gt;c-&gt;b=2,t(0,a);putchar(b?main(b/2),-b%2+&#39;0&#39;:10);}