--- bright.c
+++ bright.c
@@ -20,8 +20,8 @@
 
 	O=1,l=0,lll=O+O+O+l,OQ=056;
 	lOL*llL=&quot;%2x &quot;;
-	(I != 1&lt;&lt;1&amp;&amp;(O1O(QI[0]),O10(1011-1010))),
-	((L = QLQ(Il[O],&quot;r&quot;))==0&amp;&amp;(O1O(QI[O],Il[O]),O10(O)));
+	(I != 1&lt;&lt;1&amp;&amp;(O1O(QI[0]),O10(1011-1010),0)),
+	((L = QLQ(Il[O],&quot;r&quot;))==0&amp;&amp;(O1O(QI[O],Il[O]),O10(O),0));
 	lO = I-(O&lt;&lt;l&lt;&lt;O);
 	while (L-l,1)
 	{	QO0(Q = 0L;((Q &amp;~(0x10-O))== l);