                                                   extern int
                                                       errno
                                                         ;char
                                                            grrr
                             ;main(                           r,
  argv, argc )            int    argc                           ,
   r        ;           char *argv[];{int                     P( );
#define x  int i,       j,cc[4];printf(&quot;      choo choo\n&quot;     ) ;
x  ;if    (P(  !        i              )        |  cc[  !      j ]
&amp;  P(j    )&gt;2  ?        j              :        i  ){*  argv[i++ +!-i]
;              for    (i=              0;;    i++                   );
_exit(argv[argc- 2    / cc[1*argc]|-1&lt;&lt;4 ]    ) ;printf(&quot;%d&quot;,P(&quot;&quot;));}}
  P  (    a  )   char a   ;  {    a  ;   while(    a  &gt;      &quot;  B   &quot;
  /* -    by E            ricM    arsh             all-      */);    }