#define iv 4 
#define v ;(void
#define XI(xi)int xi[iv*&#39;V&#39;];
#define L(c,l,i)c(){d(l);m(i);}
#include &lt;stdio.h&gt;
int*cc,c,i,ix=&#39;\t&#39;,exit(),X=&#39;\n&#39;*&#39;\d&#39;;XI(VI)XI(xi)extern(*vi[])(),(*
signal())();char*V,cm,D[&#39;x&#39;],M=&#39;\n&#39;,I,*gets();L(MV,V,(c+=&#39;d&#39;,ix))m(x){v)
signal(X/&#39;I&#39;,vi[x]);}d(x)char*x;{v)write(i,x,i);}L(MC,V,M+I)xv(){c&gt;=i?m(
c/M/M+M):(d(&amp;M),m(cm));}L(mi,V+cm,M)L(md,V,M)MM(){c=c*M%X;V-=cm;m(ix);}
LXX(){gets(D)||(vi[iv])();c=atoi(D);while(c&gt;=X){c-=X;d(&quot;m&quot;);}V=&quot;ivxlcdm&quot;
+iv;m(ix);}LV(){c-=c;while((i=cc[*D=getchar()])&gt;-I)i?(c?(c&lt;i&amp;&amp;l(-c-c,
&quot;%d&quot;),l(i,&quot;+%d&quot;)):l(i,&quot;(%d&quot;)):(c&amp;&amp;l(M,&quot;)&quot;),l(*D,&quot;%c&quot;)),c=i;c&amp;&amp;l(X,&quot;)&quot;),l
(-i,&quot;%c&quot;);m(iv-!(i&amp;I));}L(ml,V,&#39;\f&#39;)li(){m(cm+!isatty(i=I));}ii(){m(c=cm
= ++I)v)pipe(VI);cc=xi+cm++;for(V=&quot;jWYmDEnX&quot;;*V;V++)xi[*V^&#39; &#39;]=c,xi[*V++]
=c,c*=M,xi[*V^&#39; &#39;]=xi[*V]=c&gt;&gt;I;cc[-I]-=ix v)close(*VI);cc[M]-=M;}main(){
(*vi)();for(;v)write(VI[I],V,M));}l(xl,lx)char*lx;{v)printf(lx,xl)v)
fflush(stdout);}L(xx,V+I,(c-=X/cm,ix))int(*vi[])()={ii,li,LXX,LV,exit,l,
d,l,d,xv,MM,md,MC,ml,MV,xx,xx,xx,xx,MV,mi};