main(t,_,a )
char
*
a;
{
				return!

0&lt;t?
t&lt;3?

main(-79,-13,a+
main(-87,1-_,
main(-86, 0, a+1 )


+a)):

1,
t&lt;_?
main( t+1, _, a )
:3,

main ( -94, -27+t, a )
&amp;&amp;t == 2 ?_
&lt;13 ?

main ( 2, _+1, &quot;%s %d %d\n&quot; )

:9:16:
t&lt;0?
t&lt;-72?
main( _, t,
&quot;@n&#39;+,#&#39;/*{}w+/w#cdnr/+,{}r/*de}+,/*{*+,/w{{ &quot;{%&quot; }}+,/w#q#n+,/#{l,+,/n{n+,/+#n+,/#;#q#n+,/+k#;*+,/&#39;r :&#39;d*&#39;3,}{w+K w&#39;K:&#39;+}e#&#39;;dq#&#39;l q#&#39;+d&#39;K#!/+k#;q#&#39;r}eKK#}w&#39;r}eKK{nl]&#39;/#;#q#n&#39;){)#}w&#39;){){nl]&#39;/+#n&#39;;d}rw&#39; i;# ){nl]!/n{n#&#39;; r{#w&#39;r nc{nl]&#39;/#{l,+&#39;K {rw&#39; iK{;[{nl]&#39;/w#q#n&#39;wk nw&#39; iwk{KK{nl]!/w{{ &quot;{%&quot; }}&#39;l##w#&#39; i; :{nl]&#39;/*{q#&#39;ld;r&#39;}{nlwb!/*de}&#39;c ;;{nl&#39;-{}rw]&#39;/+,}##&#39;*}#nc,&#39;,#nw]&#39;/+kd&#39;+e}+;#&#39;rdq#w! nr&#39;/ &#39;) }+}{rl#&#39;{n&#39; &#39;)# }&#39;+}##(!!/&quot;)
:
t&lt;-50?
_==*a ?
putchar(31[a]):

main(-65,_,a+1)
:
main((*a == &#39;/&#39;) + t, _, a + 1 )
:

0&lt;t?

main ( 2, 2 , &quot;%s&quot;)
:*a==&#39;/&#39;||

main(0,

main(-61,*a, &quot;!ek;dc i@bK&#39;(q)-[w]*%n+r3#l,{}:\nuwloca-O;m .vpbks,fxntdCeghiry&quot;)

,a+1);}