
#include &lt;stdio.h&gt;
#define QQ      1
#define TT         1
#define cc main(c,v) int c; char **v;{char tt[12],qq[7]; int q=0,o=1,l=1,m=1;struct {int c;} f;
#define ouroboros qq[6]=&#39;\0&#39;;tt[11]=&#39;\0&#39;;if(QQ==atoi(v[1])+1){(void)fprintf(stderr,&quot;%s factorial = %d\n&quot;,v[1], TT);exit(1);}o=c+f
#define x ;while(EOF!=(o=getchar())){if(l &amp;&amp; q==&#39;Q&#39; &amp;&amp; o==&#39;Q&#39;){l=0;(void)getchar();(void)fread(qq,6,1,stdin);(void)printf(&quot;Q %6d&quot;,atoi(qq)+1);}else
if(m &amp;&amp; q==&#39;T&#39; &amp;&amp; o==&#39;T&#39;){m=0;(void)fread(tt,11,1,stdin);(void)printf(&quot;T %9d\n&quot;,atoi(tt)*QQ);}else {q=o;(void)putchar(o);}}exit(0);}
cc ouroboros.c -o x 
#define zxc ;{/*
cat ouroboros.c | x $1 &gt; x1
if [ $? -ne 0 ]; then
exit
fi
mv x1 ouroboros.c
chmod +x ouroboros.c
exec ouroboros.c $1
exit
*/