#include &lt;stdio.h&gt;
#define f int
#define v (void)printf(
#define x ),exit(1);
#define y ){if(n)c=z(n,u),u=n,n=c;o[i]=n?&#39;0&#39;+(1&amp;*n):&#39;0&#39;;}
#define z(a,b) (f*)(~1&amp;*a^(f)b)
#define k(l) if(!(l=(f*)malloc(sizeof(l))))v 23+m x if(1&amp;(f)l)v 39+m x*l=
r(p,q,d)f*p,*q;{char o[81];f*n=p,i=39,*c,*u=d?q:z(p,q);o[40]=&#39;0&#39;+(1&amp;*p);
for(;i&gt;=0;i--y u=d?z(p,q):q;n=p;for(i=41;i&lt;79;i++y o[i++]=&#39;\r&#39;;o[i++]=0;
v o);(void)fflush(stdout);sleep(1);}
main(a,c)char**c;{char*u,*malloc(),*m=
&quot;Usage: black [string]\n\0No more memory\n\0Unusable memory alignment\n\0jt,s@m@ (beleY%XX&amp;Yz {z&amp;z}i|R(|)*((.)i)hiniFiGJ%FG.JJgJ: ;;&amp;;z {z&amp;z}-RS/ROiOV OP+PsaPh+ijainnjmamfmfAlnnnnphppopv%vvgv.aABiB1/BVP11/1.%..&amp;.OhrR-WV V1#1VP1CcC0R\
\n\n&#39;CVP0\n!\n\n&#39;\nEaEEnEamat!akckk&#39;kwaww&#39;wz,zzozEit +&quot;,
*n=m;f*q,*p=0,*g,b=3,d;
if(a&gt;2)v m x n=a&gt;1?c[1]:n;
/*v&quot;\t\t\t\t\tV\n&quot;);*/
k(q)0;u=n;a=~1&amp;&#39;j&#39;;
while(a!=&#39;x&#39;){
	/*r(q,p,b);*/
	for(;;u+=3){
		u= *u?u:n;
		if((~1&amp;*u)==a&amp;&amp;(1&amp;*q)&lt;&lt;1==(2&amp;u[2]))break;
	}
	a=~1&amp;u[1];
	d=(8&amp;u[2])&gt;&gt;3;
	if(16&amp;u[2])putchar(u[3]);
	if(4&amp;u[2])*q|=1;else*q&amp;=~1;
	if(b==d)g=p;else{
		g=z(q,p);
		if(!g){k(g)(f)q;*q^=(f)g;}
	}
	p=q;q=g;b=1-d;
}
/*r(q,p,b);v&quot;\n&quot;);*/exit(0);
}