--- cmills.c
+++ cmills.c
@@ -6,7 +6,7 @@
 #define H(v,g)v=h(v,*g++= *r++),*g=0;
 #define B(n)b(l,n),(V)printf(l
 V
-exit();char*g,c[M],d[N],q[N],p[N],*e,*r=d+N,l[M],*t=&quot;??&quot;,*k,*m=&quot;DEATHISDSev2oinpohae3ttsluuln4a?uibfe 5l\0rtlfrb6 ?a?el:e7$!n\0?e t8%ccp\0.%s9deelc.s T.@?-t.\t&lt;J /\0=a\nP=Q Sex \0l KW Sin a$\0ane-lay% ge#-slediefuk ar  r$via-:o ?+}:r? n \0:) ee%lone 1-esy666!-~v\n.!^`&#39;~@#\0\np~===:=q&quot;;b(o,n)char*o;{for(k=n+m;*o++=*k;k+=9);}int
+exit();char*g,c[M],d[N],q[N],p[N],*e,*r=d+N,l[M],t[]=&quot;??&quot;,*k,*m=&quot;DEATHISDSev2oinpohae3ttsluuln4a?uibfe 5l\0rtlfrb6 ?a?el:e7$!n\0?e t8%ccp\0.%s9deelc.s T.@?-t.\t&lt;J /\0=a\nP=Q Sex \0l KW Sin a$\0ane-lay% ge#-slediefuk ar  r$via-:o ?+}:r? n \0:) ee%lone 1-esy666!-~v\n.!^`&#39;~@#\0\np~===:=q&quot;;b(o,n)char*o;{for(k=n+m;*o++=*k;k+=9);}int
 y=M*2,v,x,s,f,j,o;u(s){B(s));if(!gets(l))exit(0);return(o=
 *l)==&#39;y&#39;||o==&#39;Y&#39;||o!=&#39;n&#39;&amp;&amp;o!=&#39;N&#39;&amp;&amp;u(s);}h(v,m){for(k=c;*k!=&#39;J&#39;;)if(m==*k++)break;m=k-c;if(v&lt;0)W(v=m-v)
 if(m==1)W(v+=11)