#include &lt;stdio.h&gt;
#include &lt;malloc.h&gt;
#include &lt;string.h&gt;

#define A(x) (e^d)&amp;i?e:(e+=i+i/15-d,d&lt;&lt;=4,i&lt;&lt;=4,x)
#define B b+=!((e^d)&amp;i)&amp;&amp;(d|=i),i&lt;&lt;=4,
#define C i=15,B B B B d=d&lt;&lt;4|d&gt;&gt;12,
#define D=(d=g,b=0,C b&lt;&lt;=4, C C C b)
#define E if(**y)goto
#define F=a[rand()%c]
#define G unsigned short
#define H e^=a[z],a[z]^=e,e^=a[z],

void
    main
	(int
	    z,char
		**y)
		    {G*a
			,b,c
			    ,d,e
				,f,g
				    ,h,i
					;*(*
					    y+=
						strlen
						    (*y)
							-1)^=
							    &#39;d&#39;;
								srand
								    (time
									(0))
									    ;z==
									2&amp;&amp;
								    sscanf
								(y[1
							    ],&quot;%d&quot;
							,&amp;z)
						    &amp;&amp;z?
						0:(z
					    =6);
					if(!
				    (a=(
				G*)
			    calloc(
			z*z*
		    z*z,
		sizeof
	    (G))
	)){
    printf
(&quot;No\
    memory\
	\n&quot;);
	    exit
		(1);
		    }for
			(c=1
			    ;i=15
				,d=z
				    ,c&lt;z
					*z*z
					    *z&amp;&amp;
						(e=a
						    [c-1
							]+1,
							    a[c]
								=A(A
								    (A(A
									(0))
									    )),1
									);c++
								    );*(
								**y?
							    &amp;g:&amp;
							e)F;
						    do{
						printf
					    (&quot;(%d): ????\b\b\b\b&quot;
					,c);E
				    q0;else
				goto
			    q1;q0:
			printf
		    (&quot;%04X\n&quot;
		,g+
	    4369
	);E
    q2;q1:
scanf
    (&quot;%hx&quot;
	,**y
	    ?&amp;h:
		&amp;g);
		    E q3
			;g-=
			    4369
				;q2:
				    printf
					(&quot;??\b\b&quot;
					    );E q1;
						printf(
						    &quot;%02x\n&quot;
							,h D
							    );q3
								:for
								    (z=f
									=0;(
									   z&lt;c||
									(c=f
								    ,0))
								&amp;&amp;(H
							    b D!=
							h,H b
						    ||(a[
						f++]=
					    a[z])
					,1);z
				    ++);
				}while
			    (h!=
			64&amp;&amp;
		    c&gt;0&amp;&amp;
		((g F
	    ),1)
	);printf
    (&quot;\n&quot;
);}