--- gandalf.c
+++ gandalf.c
@@ -1,15 +1,5 @@
-#define fine #define de #define/**/ /**/*#define*/
-#define de #define
-#define do de
 
-do { begin
-do you like (green eggs and ham++)?
-do you eat them: in a box?
-do you eat them with a fox?0
-do } end
 
-fine
-fine, just fine.
 
                     /*@@@@@@@@@@@@=___
                    /@@@@@@@@@@@@@@@@@@@a
@@ -53,7 +43,6 @@
        &quot;\n&quot;);}main(a
           ,b)int a;
  char **b   ;{int        x=2;
-    do(x=0;x&lt;4;x++)exit(0);
   for(grem();x&lt;1&lt;&lt;3+(int)b[0]
 [0]%2;)cred            (++x-1);}
 