#define _POSIX_SOURCE /* you are not supposed to understand this */
#define O(OOO,OO0,O00,O0O,OO,O0)\0##O0O%:%:OO\0##O0%:%:OOO\0##OO0%:%:O00
#include&lt;signal.h&gt;
static volatile sig_atomic_t One;
#include&lt;stdlib.h&gt;
#include&lt;unistd.h&gt;
#define Zero(NULL)#NULL
#define ONE(One) Zero(One)
in??/
t
#line 10 &quot;01\015&quot;
main (register zero, char **ONE)
%:
&lt;% switch (sizeof __FILE__ &lt; zero) case 1: return One /= zero;
{ auto one = zero = atoi (ONE&lt;:zero-1:&gt;);
do for (one += alarm (One |= (signal (__LINE__, (void(*)(register))main)
!= SIG_ERR)); One; ++one);
while (zero -= write (1, __FILE__+(one&amp;1), 1));
return write (1, 1+__FILE__+1, 1) != 1;
%&gt;}