char r[]=&quot;C#S3K+[;G&#39;W7OB/_? ? &#x00ab; ( !IOCCC! &#x00b4; &#x00b3;&#x00cb;n &#x00a3;0 0 e&#x00f7;|&#x00c5;t&#x00d1;%&#x00c4; &#x00b0; 2u&quot;
&quot; &#x00bb;&#x00be;&#x00df; m&#x00d4;/p &#x00aa; c p) nm &#x00ab;&#x00a8;&#x00aa;&#x00fa;&#x00ef;&#x00b5;!!&#x00b6;&#x00e2;&#x00a1;a &#x00a3;&#x00c0;3s&#x00ee;&#x00dc; 9sz2{ +&#x00a7; 9_&#x00b0;0 &#x00a9; h0 &#x00ba;&#x00c2; / &quot;
&quot;&#x00a4;)$1 &#x00ac; a~ ) % y q&#x00c3;&#39;&#x00af; &#x00b9;&#x00e2; &#x00b0; \&quot; ! q 6 &#x00b5;y&#39; 0 3;e{ &#x00cc; k&#x00e3;&#x00d4;s&#x00be;,&#x00ca; 2~a q t&quot;
&quot; 9dl 9 &#x00ac;.&#x00b4; .&#x00f9;_ &amp;&#x00c1;!&#x00ea; &#39;* &#x00b7;&#x00ad; ; &#x00b7;&#x00b1; &#x00b5;&#x00c1; = &lt;e&#x00e0;&#x00aa;1&#x00e0; B:29 &#x00a6; 6 n&#x00b4; o&#x00ae;&#x00a8;b:_2&quot;
&quot; &#x00b5; +&#x00fa;&#x00ed; h |&#x00f7;t\177&#x00b0;#d`&#x00dd; l&#x00bd;&#x00d9; r )&#x00fe;&#x00c1; @ &#x00b7;&#x00b4;&#x00d6; m d&#x00a9;i&#x00c3; &#x00a4;6 e&#x00a6; v&#x00b8;&#x00bd;^ &#x00b6;` rq&quot;
&quot;&#x00c1; &lt;&#39;7&#x00c3;&#x00f7;&#x00b0;&#x00c5;&#x00d9; &#x00b4;[|&#x00e4;&#x00c8;=&#x00f1;@&#x00ee;p (&#x00b2;, /&#x00e4;^ c &#x00a6; . &#x00ad;` &#x00a3;&#x00b2;&#x00ee; &#x00a1;&#x00ad;&#x00f1;`f&#x00e6; /= :&#x00f9;]y&#x00f7;&#x00a2;&#x00b7;&quot;
&quot; 2&#x00ba; &#x00bb; q &#x00a2; v&#x00b2;4&#x00d5;m&#x00b3;&#x00ed;&#x00d3;&amp;=a&#x00a4;&#x00a1;&#x00a0;g ; d&#x00e0;,&#x00e9;+&#x00b7; +_&#x00bc; =&#x00c8; 5&#x00df;&#x00ac;i&#x00ee;&#x00a6;&#x00be;&#x00ea;&#x00d4;&#x00d8;&#x00fb;&#x00a7;&#x00cc;&#x00cc; r&#x00a3;&quot;
#define O(Q)p!O) { *i[25][41]|=U(642+Q); u e r[(Q)/2]&amp;63); }
&quot;sol&#x00de;&#x00c4;&amp;&#x00be;X&#x00bc;[&#x00dd;; }&#x00ef;? &#x00ba;= &amp;c} 9&#x00c8;&#x00be;&#x00f3;&#x00c0;2 &gt;&#x00fc; 5 ,&#x00de; &amp;  &#x00c3;0  &#x00da;&#x00f9;*&#x00bd; &#x00b3;&#x00e4;&#x00ff;gh&quot;;
#define C(                                 b)O(28+(B+b)%6)
#   define                                 a &gt;&gt; B &amp;M[i X]
#include/*                                 s */&lt;stdio.h&gt;
#include/*                                 s */&lt;time.h&gt;
  unsigned                                 int    long
#   define                                 e putchar(
                   B,E,M,A,Z,I,N,G
# define g                                 ! (32 a)
# define u                                 U(533);
# define n                                 (65 a)
# define z                                 for (
[32768], i                                 [32]
# define p                                 if(
[48][3]={ { { 2} } } ; void**V,*D,*F[32][48];
void*Q(void**O){ return*O?(*O=Q(*O)):O; } U(
O){return E+=(O/=2)-1?U((A=A/2^57525273+(A&amp;
1^O&amp;1)*9583591&lt;&lt;5,O)),0:O,16; } main(O){ A
=O?time(D):953351751; z I=0; I&lt;26; ++I){z
N=I/2; N&lt;30+I/2; ++N){ z M=0; M&lt;3; ++M){
p Z=O)z; (B=I+Z*!!M) &lt;26&amp;&amp;N+Z*(M!=2)-B/
2&lt;30; B[G]=N&lt;&lt;7|Z++&lt;&lt;13|I*4+M)z; G[B=A
# define X [ I+Z*!! M] [ N+Z*(M!= 2)]
&amp;32767]; )u p!Z&amp;&amp;M[i X]){ z B=0; B&lt;6
; B++){ p!g){ C(5)O(0)C(2)O(2)} C((
B&amp;1?!!n:4-3*g))p!g|n)O(4)O(7)} z B
=0; B&lt;6; B++){ p g&amp;&amp;!n)O(14)p!g)O
(8)p B&amp;1|g){ O=!n; O(10)O=!(1040
a ); O(12 )O=0; } O(17+(B&amp;1 ?!(
1040 a)!=!n:g))} } } O(24)} O(
21+(I&amp;1))} O(26)p O)z E=0; E&lt;
1&lt;&lt;15; I=16){ B=E++[G]; D=Q(
&amp;F[I=B/4&amp;31][N=B&gt;&gt;7&amp;63]); M
=B%4; Z=B&gt;&gt;=13; V=Q(&amp;F X);
p!(D==V|N[I[i]] [1]|i X[1
])){ z; --Z&amp;&amp;!(*i X%9|*i
X/9&amp;*i X/9-1); ); p!Z){
*V=D; *i X|=32&gt;&gt;M; Z=B
; z*i X|=4&gt;&gt;M; --Z; i
X[*i X?2-!i X [1]:!(
F X=V)]=36&gt;&gt;M); } }
} p!O){ u u z I=8;
I--; )p(N=I[r]=(I
&gt;3?E:A)&gt;&gt;(I*9&amp;24
))==10||N==13){
e 0 ); I =8; u
u u u} e 1 );
} z E =1333;
++ I&lt;8+469*
!!O; e(N=I
[r])-32|!
O?N:r[++
I]-N));
return
 O &amp;&amp;
main
(!O
);
}