	
		    #define/**/X
		  char*d=&quot;X0[!4cM,!&quot;
	       &quot;4cK`*!4cJc(!4cHg&amp;!4c$j&quot;
	     &quot;8f&#39;!&amp;~]9e)!&#39;|:d+!)rAc-!*m*&quot;
	   &quot;:d/!4c(b4e0!1r2e2!/t0e4!-y-c6!&quot;
	  &quot;+|,c6!)f$b(h*c6!(d&#39;b(i)d5!(b*a&#39;`&amp;c&quot;
	  &quot;)c5!&#39;b+`&amp;b&#39;c)c4!&amp;b-_$c&#39;d*c3!&amp;a.h&#39;d+&quot;
	 &quot;d1!%a/g&#39;e+e0!%b-g(d.d/!&amp;c*h&#39;d1d-!(d%g)&quot;
	&quot;d4d+!*l,d7d)!,h-d;c&#39;!.b0c&gt;d%!A`Dc$![7)35E&quot;
       &quot;!&#39;1cA,,!2kE`*!-s@d(!(k(f//g&amp;!)f.e5&#39;f(!+a+)&quot;
       &quot;f%2g*!?f5f,!=f-*e/!&lt;d6e1!9e0&#39;f3!6f)-g5!4d*b&quot;
       &quot;+e6!0f%k)d7!+~^&#39;c7!)z/d-+!&#39;n%a0(d5!%c1a+/d4&quot;
       &quot;!2)c9e2!9b;e1!8b&gt;e/!     7cAd-!5fAe+!7fBe(!&quot;
      &quot;8hBd&amp;!:iAd$![7S,Q0!1     bF 7!1b?&#39;_6!1c,8b4&quot;
      &quot;!2b*a,*d3!2n4f2!${4    f.      &#39;!%y4e5!&amp;f%&quot;
     &quot;d-^-d7!4c+b)d9!4c-a    &#39;d        :!/i(&#39;`&amp;d&quot;
     &quot;;!+l&#39;a+d&lt;!)l*b(d=!&#39;   m-        a  &amp;d&gt;!&amp;d&#39;&quot;
    &quot;`0_&amp;c?!$dAc@!$cBc@!$   b         &lt;    ^&amp;d$`&quot;
    &quot;:!$d9_&amp;l++^$!%f3a&#39;    n1        _       $ !&amp;&quot;
   &quot;f/c(o/_%!(f+c)q*c     %!         *       f &amp;d+&quot;
   &quot;f$s&amp;!-n,d)n(!0i-     c-         k)       !  3d&quot;
   &quot;/b0h*!H`7a,![7*     i]          5        4   71&quot;
  &quot;[=ohr&amp;o*t*q*`*d      *v         *r         ;  02&quot;
  &quot;7*~=h./}tcrsth      &amp;t          :          r   9b&quot;
 &quot;].,b-725-.t--//      #r         [           &lt;   t8-&quot;
 &quot;752793?  &lt;.~;b      ].t--+r     /           #    53&quot;
 &quot;7-r[/9~X  .v90      &lt;6/&lt;.v;-52/={            k   goh&quot;
 &quot;./}q;   u  vto     hr  `.i*$engt$            $    ,b&quot;
 &quot;;$/     =t ;v;     6     =`it.`;7=`          :    ,b-&quot;
 &quot;725    = / o`.    .d       ;b]`--[/+       55/     }o&quot;
 &quot;`.d   :   - ?5    /           }o`.&#39;     v/i]q      - &quot;
 &quot;-[;   5  2  =`  it            .        o;53-       . &quot;
 &quot;v96   &lt;7 /      =o            :            d        =o&quot;
 &quot;--/i  ]q--      [;           h.            /        = &quot;
 &quot;i]q--[  ;v      9h           ./            &lt;        - &quot;
 &quot;52={cj   u      c&amp;`          i   t       . o        ; &quot;
 &quot;?4=o:d=         o--          /  i        ]q         - &quot;
 &quot;-[;54={  cj     uc&amp;          i]q          -          -&quot;
 &quot;[;76=i]q[;6     =vsr        u.i           /          ={&quot;
 &quot;=),BihY_gha     ,)\0        &quot;             ,          o [
  3217];int i,   r,w,f        ,              b        ,x ,
  p;n(){return   r  &lt;X        X               X       X  X
  768?d[X(143+   X  r++       +               *d      )  %
   768]:r&gt;2659   ?  59:       (                x      =  d
   [(r++-768)%   X  947      +             768]       ) ?
   x^(p?6:0):(p  =   34      X            X           X )
   ;}s(){for(x=  n   ();     (           x^           ( p
  ?6:0))==32;x=  n    ()     )   ;return x            ; }
  void/**/main X      ()     {           r           =  p
  =0;w=sprintf  (X     X     X         X X           X o
  ,&quot;char*d=&quot;);  for          (    f=1;f &lt;            * d
  +143;)if(33-(  b=d         [      f++ X           ]  )
  ){if(b&lt;93){if   X(!        p          )             o
   [w++]=34;for    X(i       =         35             +
    (p?0:1);i&lt;b;    i++      )         o
    [w++]=s();o[     w++               ]
     =p?s():34;}     else              X
       {for(i=92;     i&lt;b;            i
	++)o[w++]=     32;}           }
	     else o     [w++          ]
			 =10;o        [
			   w]=0      ;
			    puts(o);}