#ifdef s
							    z
							   r(
							  ){z
							 k=0,l
							=0,n,x
					       XQueryPointer(i
				    ,XRootWindow      (i,j),&amp;m,
		      &amp;m,&amp;o,&amp;p,&amp;n,&amp;n,(               ghj)&amp;n),(o
						    &gt;=s(g)||s(o
						   )&lt;=0)&amp;&amp;(k=1),
						  (p&gt;=h||p&lt;=0)&amp;&amp;
						 (l=1),(e==1)&amp;&amp;(
						c=o,d=p,e=0,1)||(
					       (k==0&amp;&amp;o-c-(z)(a+y
					      (a)*.5)!=0)&amp;&amp;(a=o-c
					     ),(l^-1==-1&amp;&amp;p-d-(z)(
				 b+y(b)*.5)!=0)&amp;&amp;(b=p-d),a/=f,b/=f
			 ,k=0,l=0);(o      &gt;=s(g)||o&lt;=0)&amp;&amp;(a=-a),(
	   p&gt;=h||s(p)&lt;=0)                 &amp;&amp;(b=-b),c=o,d=p,I(XWarpP
					 ,ointer)(i,None,None,0,0,s
					(g),h,(z)(a+y(a)*.5),(int)(
				       b+y(b)*.5 JJ(float B;int)C,D;
				      #else/*Egads! something has */
				     #include&lt;X11/Xlib.h&gt;/*taken a*/
				    #include&lt;stdio.h&gt;/*huge bite o-*/
				   #include&lt;stdlib.h&gt;/*ut of the m-*/
				  #include&lt;time.h&gt;/*ouse pointer!!!*/
			     #define H(a, b) (((a)&amp;(7&lt;&lt;3*(b)))&gt;&gt;3*(b))
		#define G(c,d)  ((H(c,d)&lt;&lt;3*(d+1))|((H(c,d+1)&lt;&lt;3*d)|/*
     _XSetPointer(display,     screen,GREASY|BOUNCY)*/c&amp;~(63&lt;&lt;3*(d))))
#define                       s(e) (G(G(G(G(G(G(e,(z)0),1),2),1),0),1))
			     typedef int z;float a=0,b=0,c,d,f=1.03;z e
					  =s(512),g,h,j;
					  Display/**/*i;
			      #define y(X)((X&gt;0)-(X&lt;0))
			#define x        o,p; Window m;
	      #define ghj               unsigned  int*
	#define                         I(aa,bb)aa##bb
				       #define JJ(X)\
				       ));return 0;}X
				      z r();int main
				      (z X,char**Y){
				     clock_t q=0;(X
			   ==2)&amp;&amp;(f=atof(Y[1])),((i
	      =XOpenDisplay(0)      )==0)&amp;&amp;(exit(1
    ),1),j=I(Defa,                  ultScreen)(i),
				   g=s(I(Display,
				   Width)(i,j)-1)
				  ,h=I(DisplayH,
				  eight)(i,j)-1;
				 for(;;((I(clo,
				 ck)()-q)*100&gt;(
				CLOCKS_PER_SEC
		 ))&amp;&amp;(r(),q=clock()));}
   #include __FILE__
#endif
