#define n ((e[++a]-42)/9-f[d+1])?
#define o printf(&quot;%c&quot;,c[&quot; 01./:;|\\&quot;]);

char e[]=&quot;**3&lt;HRZcir+3@OXakt;=GOXds*\?HRZcir*7HNZ`i19JS\\p*H[m1:CJSz*&gt;H[`mr25\
\?Hx,P,B2Gs-KTfzRdv1SeyCR-ISeu.&lt;Ev+9+P,z,4PfzIdvO2*HRZcir6GPis=MU*3HRZcir*HZi\
1JS\\epy*&gt;H[m1JSey*DH[m*3&lt;HZiu-@P*3HZi&lt;N]q1JS\\epy:[m1CJSeny06I[m*4\?HRZcir,\
\?*6HRZcir1J]q2K*H[m2K*H[m2@K]qtO@M2DK]q,]q1JS\\epy[m1:JSey+[m*3&lt;HRZcir13Gt,\
=GVs*3&lt;HRZcir1J]qz*HF*AH2;DK]qua0=G2:K]q]q1CJS\\pDVu1:JS*D!+3:BIOSY`egilqtxz\
\177.0249&lt;==&gt;EJMUY`ejov#$59@CJOXYZbfhlnrxy&amp;+.57=@IMR[``bcfmnq!#),@&quot;,*f;

int main(int j,char *k[]) {
  int a,b,c,d,g,h,i=19;

  printf(&quot;       &quot;);
  for(g=0[f=(char *)calloc(80+(h=atoi(1[k])),1)]=1; g&lt;=h; g++) {
    if ((g&gt;30)&amp;&amp;(f[i-2]+f[i-1]!=0)) i++;
    for(d=c=0; d&lt;i; d++) {
    o f[d]=(e[b=c*9,b+=(c=d[f]),(((a=e[345+b]+b/19*85-33-b/40*12-b/80*4)[e]
		-42)/9-f[d+1])?n n n n n n n n 0:a:a:a:a:a:a:a:a:a]-42)%9; }
    o if (0[f]-1) printf(&quot;\n%6i &quot;,g); else printf(&quot;\n       &quot;); }
}