                                  #include\
                                  &lt;stdio.h&gt;
                     #include                &lt;stdlib.h&gt;
                     #include                &lt;string.h&gt;

                    #define w &quot;Hk~HdA=Jk|Jk~LSyL[{M[wMcxNksNss:&quot;
                   #define r&quot;Ht@H|@=HdJHtJHdYHtY:HtFHtF=JDBIl&quot;\
                  &quot;DJTEJDFIlMIlM:HdMHdM=I|KIlMJTOJDOIlWITY:8Y&quot;
                 #define S&quot;IT@I\\@=HdHHtGH|KILJJDIJDH:H|KID&quot;\
                &quot;K=HdQHtPH|TIDRJDRJDQ:JC?JK?=JDRJLRI|UItU:8T&quot;
               #define _(i,j)L[i=2*T[j,O[i=O[j-R[j,T[i=2*\
              R[j-5*T[j+4*O[j-L[j,R[i=3*T[j-R[j-3*O[j+L[j,
             #define t&quot;IS?I\\@=HdGHtGIDJILIJDIItHJTFJDF:8J&quot;

    #define y                  yy(4),yy(5),                yy(6),yy(7)
  #define yy(              i)R[i]=T[i],T[i ]            =O[i],O[i]=L [i]
#define Y _(0          ], 4] )_ (1 ], 5] )_ (2      ], 6] )_ (3 ], 7] )_=1
#define v(i)(      (( R[ i ] * _ + T [ i ]) * _ + O [ i ]) * _ + L [ i ]) *2
double b = 32  ,l ,k ,o ,B ,_ ; int Q , s , V , R [8 ], T[ 8] ,O [8 ], L[ 8] ;
#define q( Q,R ) R= *X ++ % 64 *8 ,R |= *X /8 &amp;7 ,Q=*X++%8,Q=Q*64+*X++%64-256,
# define  p      &quot;G\\QG\\P=GLPGTPGdMGdNGtOGlOG&quot;   &quot;dSGdRGDPGLPG\\LG\\LHtGHtH:&quot;
#  define W         &quot;Hs?H{?=HdGH|FI\\II\\GJlHJ&quot;    &quot;lFL\\DLTCMlAM\\@Ns}Nk|:8G&quot;
# define   U           &quot;EDGEDH=EtCElDH{~H|AJk}&quot;       &quot;Jk?LSzL[|M[wMcxNksNst:&quot;
#  define u                  &quot;Hs?H|@=HdFHtEI&quot;             &quot;\\HI\\FJLHJTD:8H&quot;
char  *   x                   ,*X , ( * i )[               640],z[3]=&quot;4_&quot;,
*Z = &quot;4,8O4.8O4G&quot; r U &quot;4M&quot;u S&quot;4R&quot;u t&quot;4S8CHdDH|E=HtAIDAIt@IlAJTCJDCIlKI\\K:8K&quot;U
 &quot;4TDdWDdW=D\\UD\\VF\\FFdHGtCGtEIDBIDDIlBIdDJT@JLC:8D&quot;t&quot;4UGDNG\\L=GDJGLKHL\
FHLGHtEHtE:&quot;p&quot;4ZFDTFLT=G|EGlHITBH|DIlDIdE:HtMH|M=JDBJLDKLAKDALDFKtFKdMK\
\\LJTOJ\\NJTMJTM:8M4aGtFGlG=G|HG|H:G\\IG\\J=G|IG|I:GdKGlL=G|JG|J:4b&quot;W
S&quot;4d&quot;W t t&quot;4g&quot;r w&quot;4iGlIGlK=G|JG|J:4kHl@Ht@=HdDHtCHdPH|P:HdDHdD=It\
BIlDJTEJDFIdNI\\N:8N&quot;w&quot;4lID@IL@=HlIH|FHlPH|NHt^H|^:H|MH|N=J\\D\
J\\GK\\OKTOKDXJtXItZI|YIlWI|V:8^4mHLGH\\G=HLVH\\V:4n&quot; u t t
&quot;4p&quot;W&quot;IT@I\\@=HdHHtGIDKILIJLGJLG:JK?JK?=JDGJLGI|MJDL:8M4\
rHt@H|@=HtDH|BJdLJTH:ITEI\\E=ILPILNNtCNlB:8N4t&quot;W t&quot;4u&quot;
p&quot;4zI[?Il@=HlHH|HIDLILIJDII|HKDAJ|A:JtCJtC=JdLJtJL\
THLdFNk|Nc|\
:8K&quot;; main (
int C,char**        A) {for(x=A[1],i=calloc(strlen(x)+2,163840);
C-1;C&lt;3?Q=_=       0,(z[1]=*x++)?((*x++==104?z[1]^=32:--x), X =
strstr(Z,z))      &amp;&amp;(X+=C++):(printf(&quot;P2 %d 320 4 &quot;,V=b/2+32),
V*=2,s=Q=0,C     =4):C&lt;4?Q--&gt;0?i[(int)((l+=o)+b)][(int)(k+=B)
]=1:_?_-=.5/    256,o=(v(2)-(l=v(0)))/(Q=16),B=(v(3)-(k=v(1)
))/Q:*X&gt;60?y   ,q(L[4],L[5])q(L[6],L[7])*X-61||(++X,y,y,y),
Y:*X&gt;57?++X,  y,Y:*X &gt;54?++X,b+=*X++%64*4:--C:printf(&quot;%d &quot;
,i[Q][s]+i[Q ][s+1]+i[Q+1][s]+i[Q+1][s+1])&amp;&amp;(Q+=2)&lt;V||(Q=
0,s+=2)&lt;640
||(C=1));}