#include&lt;stdio.h&gt;

 	 /* 

 	O
  		b  
 	f   		u  			s	 
 	c
 
 	a 
 
 t	
 		e

 		d	 
 	*/ 

 	int 	 		m	 
	 (
	
 	int

 
 c	 	  )	
	
 {	 

 int		

 x 
	
 = 
		 3	
	 	+
	 
 (  
 	c
	
 	-	
	 	1 
 		)
	 	 *

	 	9

		 +  
 	(

		 c
 
 	-

		 1 	
 	)

		 *		
 	27

		 +
	
 	(

		 c 
		 -


 	1	
 
 )	
 	 *
	 	 (
 	 	

 		(
 	 	993
  		-	
 	 &#39;!&#39;

		 * 	
 	c
	 
 )	  		/	
	 	320 

 	)
  		+				 ( 

 	c
  		-

 		&#39;9&#39;
	 	 +	
	 	&#39;8&#39; 
 		)		
 	*  
 	c

		 +  
 	(
	
 	c	
	 	- 
 		1
	 	 ) 
		 *	
	 	243 
 		/		
 	9;	 				 	 	return 		 	c
			 - 
			32	
	 	?	
 
 c 	
 	- 	 		9		 		?
 
 	c
  		-				 10	
	 	? 
 		x		
 	%	 			x	 	 	:	 	  3		
	 : 		 	2

		 :	
 	 1 
 		;	
 	 }
			 
	 
 int 	
 	a 	 		, 
 		b				 ,
	 
 c
	 
 ,
			 d 
			,  
 	e	
 
 		
 	,
 
 	v,

 		f  
 	;
	
 	int	
	 	main 
 		/*				 n
			 (
	 
 c 

 	) 	
 	{				 return  
 	c	
 
 ++	
 
 - 
	
 32	


 ?	
	
 c
 		 -
 		 9
 
 	?	
 
 c	
 
 - 
	
 10	


 ?	
	
 0
			 :
 
 	3 				: 

 	2

 		:				 1 	
	 ;
			 }
	 
 x
 
 	(   		)	
 		{
 
 	int
	 	 a 

 	, 	
 	b				 ,  
 	c	
 
 ,	
 
 d 
	
 ,	


 e	
	
 ,
			 v  
 	;	
 
 while 

	 (
	
	 (
	 
 v 

 	= 	
 	putchar				 (

	 	d	 	  ) 
 	 )	
 
 != 			 EOF
 	 	)
 	 	{ 			 if
 		 (
 		 (

	 	a 
 	 =	
 
 m 			 */
 	 	( 			 ) 			 {
 		 while
 		 (  
 	(	
 
 e	
 
 = 			 d	
 	 = 			 c
			 = 	
 	b	
 
 =		
	 v  
	 = 	
 	getchar
	 
 ( 

 	) 	
 					 ) 
 	 - 	
 	EOF
 		 )
 		 {				 for 
 	 (				 ;  
 	d  
	 &lt; 

	 0
	
	 ;
			 d	
			++	
			) 
 	 {				 f  
 	=  
	 f 	 
 /
			 getchar	
			(	
			) 
 	 ;				 a  
 	&lt;&lt;=  
	 f		
	 ; 	
	 (
			 v
			 *
 		 v
 		 *				 v
 
 	-	
 
 v		
 	||
 
 	e

 		*  
 	e				 *	
	 	e
			 -
			 e 
 	 )	
 
 &amp;&amp;	 	  ( 
	
 e	


 -	
	
 2
			 || 
			(		 		d 
 		&amp; 

 	f
  		)

 		- 	
 	4				 ||	
 	 (	 		 a  
 	&gt;&gt;	 		 v  
 	!=	 		 (  
 	e	 		 -  
 	1	 		 ?  
 	f	
 	 :

		 0


 	)	 	 	)
 
 	)	 		 ; 

	 } 		 	if

		 (


 	(	 	 	v				 %
 
 	v  
	 +
 
 	f	 		 * 

	 --f
			 +
 
	 v 

	 )	 		 &amp;&amp; 

	 ( 		 	v

		 &lt;


 	f	 	 	?				 v				 /
 
 	v  
	 -
 
 	992	 		 * 

	 b
			 :
 
	 v 

	 *  
	 v				 )				 &amp;&amp;
 
 	/*  
	 o
 
 	(	 		 c 

	 )
			 {
 
	 return 

	 c	 		 - 

	 32
			 ?
			 c
 
	 - 

	 9	 		 ? 

	 c	 	  - 		 	10

		 ?


 	0	 	 	:				 3				 :				 2
 
 	:  
	 1
 
 	;	 		 } 

	 y
			 (
 
	 ) 

	 {  
	 int				 a				 ,
 
 	f  
	 ,
 
 	b	 		 , 

	 c
			 ,
 
	 d 

	 ,	 		 e 

	 ,
			 v
			 ;
 
	 while 

	 (  
	 (				 v				 =				 getchar
 
 	(  
	 )
 
 	)	 		 != 

	 EOF
			 )
 
	 { 

	 if  
	 (				 (				 a
 
 	=  
	 m
 
 	(	 		 c 

	 )
			 ;
 
	 */ 

	 (	 		 a 

	 =
			 m
			 (
 
	 b 

	 +	 		 ++ 

	 f
			 *
			 3888
 
	 ) 

	 )	 		 &amp;&amp; 

	 ( 		 	b

		 =


 	m	 	 	(				 getchar				 (				 )				 )
 
 	-	 	  f  
	 /
 
 	243	 		 ) 

	 &amp;&amp;
			 (
 
	 c 

	 =  
	 m				 (				 getchar
 
 	(  
	 )
 
 	)	 		 + 

	 f
			 )
 
	 &amp;&amp; 

	 	 		 ( 

	 f
			 ==
			 1
 
	 ? 

	 124  
	 -				 (				 (				 c
 
 	&lt;  
	 8
 
 	&amp;&amp;	 		 ( 

	 (
			 c
 
	 &amp; 

	 b  
	 )				 !=				 e
 
 	||  
	 (
 
 	c	 		 &gt;&gt; 

	 d
			 )
 
	 != 

	 3888	 		 ) 

	 )
			 )
			 :
 
	 1 

	 )	 		 &amp;&amp; 

	 (
			 d
			 =
 
	 m 

	 (  
	 getchar				 (				 )				 +				 f
 
 	)  
	 )
 
 	&amp;&amp;	 		 ( 

	 e
			 =
 
	 m 

	 (  
	 getchar				 (				 )
 
 	)  
	 )
 
 	)	 	  putchar	 		 ( 

	 f
			 +
 
	 a 

	 -	 		 1 

	 +
			 (
			 b
 
	 - 

	 1  
	 )				 *				 (				 (
 
 	993  
	 -
 
 	&#39;!&#39;	 		 ) 

	 /
			 (
 
	 &#39;(&#39; 

	 *  
	 8				 )				 )
 
 	+  
	 (
 
 	c	 		 - 

	 f
			 -
 
	 &#39;9&#39; 

	 +	 		 &#39;8&#39; 

	 )
			 *
			 9
 
	 - 

	 4	 		 + 

	 (
			 d
			 -
 
	 1 

	 )	 		 * 

	 243
			 /
			 9
 
	 + 

	 f 		 	+
			 11
	 
 +

			(
 
 	e   		-	
 		1
 
 	)
	 	 *		 		3888  			/

 		&#39;0&#39;  
 	-
	
 	7	
	 	) 
 		;				 }  
 	return
			 (
	 
 f

	 	&amp;&amp;	
 
 getchar  
 	(
	 
 )

			)

			;	 	  }