#include &lt;stdio.h&gt;
#include &lt;stdlib.h&gt;
#include &lt;string.h&gt;
#define PI 314
#define Z if
#define P a-&gt;b
#define Q else
#define W =f();
#define X char
#define J while
#define N return
#define V struct e

#define  g(_,a)((_&amp;&amp;a)?!strcmp(_,a):0)
typedef V*d; V{ d o,_; X*b; int c; };
d f() { d _=(d)malloc(sizeof(V)); _
-&gt;b=0; _-&gt;o=_-&gt;_=0; _-&gt;c=1&gt;&gt;1&gt;1;
N _; } d k,l,m,n,o,p,q,r; d j
() { d _=l; d a W a-&gt;o W
l-&gt;o=a; l W l-&gt; _=_;
N a; } d u(d _,
X*a){ J(_){
Z(g(a,_
-&gt;b)
){
 N
_;
} _=
_-&gt;_; }
N 0; } d s
(X*q){ d _=n; Z
(g(&quot;q&quot;, q)){ N o; }  
J(PI){ _=u(_,&quot;cde&quot;); _=_
-&gt; _ ; Z ( g (q, _-&gt;b) ){ N _
-&gt;_ ; } } } void t(d a, d _) { d 
  S,I,M,U,L,A,T,O,R  ; Z(a==o){ S W
S-&gt;o W m-&gt;o=S; I=m; m W m-&gt;_=I; _=_-&gt;
_; J(_) { S-&gt;o-&gt;o=_-&gt;o; I=S-&gt;o; S-&gt;o W
S-&gt;o-&gt;_=I; _-&gt;o-&gt;o-&gt;o=S; I=_-&gt;o-&gt;o; _
-&gt;o-&gt;o  W _-&gt;o-&gt;o-&gt;_=I; _=_-&gt;_; } } 
Q { M W _=_-&gt;_; J(57-*P){ U=M; U
-&gt;b=P; U-&gt;o=_-&gt;o; M W M-&gt;_=U;
_=_-&gt;_; a=a-&gt;_; } a=a-&gt;_
; J(a&amp;&amp;!g(&quot;qtm&quot;,P)&amp;&amp;
!g(&quot;cde&quot;,P)){ L
=s (P); a=a
-&gt;_; A=
L; T
 W
O=
T;
J(*L
-&gt;b-57){ R
=g(&quot;/&quot;,P)?j():g
(P,&quot;0&quot;)?p:g(&quot;b&quot;,P)?
q:g(P,&quot;j&quot;)?r:0; Z(!!!R){
R=u(M,P); Z(!R) { R=j(); U=M;
U-&gt;b=P; U-&gt;o=R; M W M-&gt;_=U; } Q{
R=R-&gt;o; } } O=O-&gt;_ W O-&gt;o=R; O-&gt;b=L
-&gt;b; L=L-&gt;_; a=a-&gt;_; } t(A, T); } } }
void h(d e){ d _,a,c, z=e-&gt;o-&gt;_; J(z){ 
_=z-&gt;o; c=_-&gt;o-&gt;_; a= c-&gt;_-&gt;_-&gt;o; c=_
-&gt;c?c-&gt;_-&gt;o :c-&gt;o; Z(c-&gt;c&lt;a-&gt;c) { c
-&gt;c++; h(c); } Q Z(a-&gt;c&lt;c-&gt;c){ a
-&gt;c++; h(a); } z=z-&gt;_; } } X*
v(X*_,int O){ X*s=(X*)m\
alloc(strlen(_)*siz\
eof(X)); X*l=s;
J((*l++=*_?
*_-O:0)
)_++
;N
s;
 }
/**/
int ma\
in(){d a,_
,b;d    T,O,F,U
,    R,  E, L, A, Y
; X c[PI],x[PI],w[PI],*y
,*B,*d,*K=v(&quot;Cvjme!dpnqmfuf;\
!&amp;e!dpnqpofout-!&amp;e!opeft/\x0b&quot;,1
),*e=v(&quot;&amp;e;!&amp;t\x0b\0nbjo)*|jou!j&gt;1\
&lt;gps)&lt;j=51&lt;j,,*qsjoug)#&amp;e!#-j+j,j,52\
*&lt;~&quot;,1); int i,z,C,G,H,D,I ; k W l W m
W n W o W p W q W r W b=o; for(*x=D=I
=i=0; 5-i; i++){ b-&gt;b=i&amp;4?v(&quot;;&quot;,2):
v(&quot;s&quot;,2); b=b-&gt;_ W } H=p-&gt;c=1; p
-&gt;o W r-&gt;o W q-&gt;o W a=n; J(g\
ets(c)){ d=c; J(*d){ *d=
*d&lt;65||*d&gt;90 ?*d:*d+
32; d++; } y=s\
trchr(c,35)
; Z(y){
*y=0
 ;
 }
 B
=st\
rtok(c,
&quot; &quot;); J(B)
{ a=a-&gt;_ W P=v(
B,1); Z(g(&quot;qtm&quot;,P))
{ _=a; } B=strtok(0,&quot; &quot;)
; } } _=_-&gt;_; z=atoi(v(_-&gt;b,-
1)); _=_-&gt;_; C=atoi(v(_-&gt;b,-1));
G=C; _=_-&gt;_; T=s(_-&gt;b); _=_-&gt;_; O W
F=O; U=k; J(_&amp;&amp;!g( &quot;cde&quot;,_-&gt;b)){ i=*_
-&gt;b; R=i-47?48-i?i-98?106-i?0:r:q:p:j(
); Z(!R){ R=j(); U=U-&gt;_ W U-&gt;o=R; } F
= F-&gt;_ W F-&gt;o=R; _=_-&gt;_; } t(T, O); 
E=m-&gt;_; J(E){ D++; E=E-&gt;_; } L=l
-&gt;_; J(L){ I++; L =L-&gt;_; } p\
rintf(K,D,I); for(i=&#39;\&#39;&#39;
/&#39;\&#39;&#39;; z&gt;i; i++){ J(
!--G){ G=C; H=1
-H ; break;
} r-&gt;c=
! (q
-&gt;
c=
H)
; L=
l-&gt;_; J
(L) { L-&gt;o
-&gt;c=!1; L=L-&gt;_;
} h(p); Z(q-&gt;c){ h(
q); } Q{ h(r); } E=m-&gt;_;
J(E){ A=E-&gt;o; A-&gt;c=A-&gt;o-&gt;_-&gt;_
-&gt;_-&gt;_-&gt;o-&gt;c; E= E-&gt;_; } Y=k-&gt;_; 
d=w; J(Y){ *d++=48+Y-&gt;o-&gt;c; Y=Y-&gt;_;
} *d=0; Z(!g(w,x)){ strcpy(x,w); pri\
ntf (e,  i,  w   ) ;  }  }   N  0  ; }