                            /* &lt;body  bgcolor  = 0 &gt;
                          &lt;img src= cube.gif&gt;&lt;!-- */
                        #define _ ] [ /* ; ; ; ;  */
                      #include &lt;string.h&gt;  /* ; ; */
                    #include  &lt;stdio.h&gt;  /* ; ; ; */
                    #define K(o,O) L o=0; o&lt;O ; o++)
                    #define  H  unsigned  long  long
                    #define /* ; ; ; ; ; ; } */ W ]=
                    #define /* ; ; ; ; ; ; */ L for(
                    #define /* ; ; ; ; ; ; */ J if (
                    #include &lt;stdlib.h&gt; /*; ; ; ; */
                    #define Z (j*3+j/9*3+2)%10+j/9*9
                    int s[ ] = { 186, 94, 1426, 3098
                    ,1047 , 122 , 1082 , 3083 , 1039
                    , 569 , 527 , 1054 ,  531  } ;
                    #define P( o , O ,l) K(C,o)\
                    fputc ( ( O )[ C ] -l, G);
                    #define Y strncpy( /* */

        int j,k,l,v,c,C,O[64],n[
      64],*o,q[13 _ 13],u,d,f,g[
    W{ 8,7,6,6,6,6 } ; H p [13 _
  #define M memset(E[c]+j*298+v\
*a+88-u*5+586*( u*5+152-i/16*a+C
13 _ 432],r,w,t,b,S[13]; FILE*G;
char E[13 _ 168840],*A=&quot;||||||&quot;,
*D=&quot;   {   ;   wb;  aa; aaaa}a \
0z00Zzz} { z0z}      &quot;,Q[64 _ 60
],*F =&quot;+    +&quot;,T [43]; int main(
int I,char**V){ int i,h,B,a,m; H
#define R(z){ x=h=0; K(j,27)h|=\
(c&gt;&gt; j&amp;1 )&lt;&lt;z ; ; ; } c=h; ; ; ;
x; J I&gt;1)B=C=atoi(V[1]); J !d)K(
v,13){ h=s[v]; J B&lt;0){ k=h&gt;&gt;18
^h&amp;511; h^= k&lt;&lt;18|k; C=-C; }
K(k,7){ J k==4)R(Z)R(j+(j-
&quot; /@&quot;[j/9]+38)/3*6-6)K(l

                            ,4){ R(Z)K(a,9) x|=((H)c
                          &gt;&gt;a*3&amp;7)&lt;&lt;a*4 +a/3*4; K(a,
                        96){ m=a-37; r=m&lt;0?x&gt;&gt;-m:x&lt;&lt;
                      m; J!(x!=(m&lt;0?r&lt;&lt;-m:r&gt;&gt;m)||r&amp;r
                    /2&amp;0x888888888888888ULL||r&amp;r&gt;&gt;4&amp;
                    0xF000F000F000ULL)){ p[0 _ v _ q
                    [v _ 0]++W r; K(j,q[v _ 0]-1)J p
                    [0 _ v _ j]==r)q[v _ 0]--; } } }
                    } } h=d; x=w; m=q[f _ h]; a=f; u
                    |=1&lt;&lt;a; B=u; K(i,m){ w|=S[a W p[
                    d _ a _ i]; r: d++; v=*s; t=w; L
                    j=1; j&lt;13; j++){ J u&gt;&gt;j&amp;1^1){ b=
                    c=k=0; l=q[j _ h]; L; k&lt;l; k++){
                    r=p[h _ j _ k]; J!(w&amp;r))b|=p[d _
                    j _ c++W r; } J!c) goto n; J c
                    ==1){ w|=S[j W b; u|=1&lt;&lt;j; J
                    d==12){ J--C&lt;1){ K(c,64)O[
                    c W-1; x=0; K(c,13){ r=~

        0; K(j,13)J S[j]&lt;r&amp;&amp;S[j]
      &gt;x)r=S[j]; K(i,64){ n[i W-
    1; memset(Q[i],32,59); } K(i
  ,64){ J r&gt;&gt;i&amp;1)O[i W n[i W c ;
K(j,2){ o=j?O:n; k=o[i]; u=i&amp;d ;
v=i&amp;3; a=48; J k+1){ C=k==c; Y T
,&quot;+----+/    /|+----+ ||    | +\
|    |/+----+&quot;,43); J!C&amp;&amp;v&amp;&amp;o[i-
1]==k)T[6 W T[21 W T[29 W 32 ; J
u&amp;&amp;o[i-4]==k){ Y T,C?&quot;//////&quot;:F,
6); J v==3||o[i-3]&lt;0)T[d W T [20
W C?47:32; } J i&amp;a&amp;&amp;o[i-16]==k){
J u==d||o[i-d]&lt;0)Y T+36,C?A:F,6)
; J!C)J v==3|| o[i-15]&lt;0) T[35 W
32; } J C){ Y T+7,&quot;////&quot;,4); T
[19 W T[27 W 47; Y T+22,A,4)
; Y T+30,A,4); } K(C,6)Y Q
[9-i/16*3+u/2+C]+v*5-u/2

                            +j*30+g[C],T+&quot;06=EMT&quot;[C]
                          -a,20-g[C]-g[5-C]); K(C,a)
                        { M)+28,m=k+33,h=20); M+h)-h
                      ,k+49+u/4*16,a); } K(C,h){ M)-
                    C,k+17,a); M)+a-C,m,C); M+a)+28,
                    m,h-C); } } } } K(i,21)puts(Q[i]
                    ); x=r; } G=fopen(&quot;cube.gif&quot;, D+
                    11); P(13,&quot;qspbc\213t,J+ **&quot;,42)
                    K(i,8)P(a,D,h+&quot; H Zbjm &quot;[i]+C)P(
                    19,&quot;F$0sjyxhfujWSU(&amp;%%%&quot;,37)K(i,
                    13){ P(19,&quot;K#.3 ***V****t,J+*1&quot;,
                    42)K(j,1340){ P(2,&quot; !&quot;,161)P(126
                    ,E[i]+j*126,0)}P(3+i/d,&quot;!\241 [&quot;
                    ,32 ) } exit(0); } goto n; }else
                    goto r; } J c&lt;v) { f=j; v=c; }
                    q[j _ d W c; t|=b; } } J!~t)
                    main(0,0); n:u=B; w=x; d=h
                    ; } u^=1&lt;&lt;a ; } /*--&gt; */