                          #define  \
                        D(s)&quot;&lt;&lt;&quot;#s&quot;&gt;&gt;&quot;
                      #define  q(s)p(#s)
                     #define S &quot; endobj &quot;
                    #define Y &quot;endstream&quot;S
                    #include     &lt;stdio.h&gt;
                    #define  o(s) b[s]=_;\
                     p(&quot;%u    0  obj&quot;,s);
#define E for         (c=d;c  &lt; 123;c++)
  #define DANCE         &quot;trailer   &quot;D\
    (/Root 3 0            R /Size %d)            &quot;\nstartxref %u %%%%EOF\n*/&quot;
      #define              p(s, ...)             _+=printf(s,  ##__VA_ARGS__)
       #define C         &quot;&lt;&lt;/Type/Page         /Parent %d %d R /Resources &lt;&lt;\
        /ProcSet[       /PDF/Text]/Font       &lt;&lt;/U&quot;D(/Subtype/Type1/BaseFont\
          /Courier) &quot;  /T&lt;&lt;/Subtype/Type3   /FontBBox[0 0 10 10]/FontMatrix[\
           %f 0 0 %f 0 0]/FirstChar %d/LastChar %d/Encoding&lt;&lt;/Differences[%d&quot;
            typedef int N;typedef char*Nyan;typedef char A;N a,b[64],d=65,_,v
              [32]={84,0,64,282,90,74,330,85,93,173,167,176,80,208,81,13,7,87
                ,160,346,32,128,170,218,16,26}; Nyan w[]={&quot;+*-(,&amp;-&amp;&quot;,&quot;+*,&amp;-&amp;&quot;
                  ,&quot;+*.&amp;/&amp;&quot;,&quot;+*/*/+&quot;,&quot;+*())&#39;(&#39;&quot;  ,&quot;+**&amp;)&amp;&quot;,&quot;+*(&amp;&#39;&amp;&quot;,&quot;+*&#39;*&#39;+&quot;,
                    &quot;&quot;,&quot;+,./&quot;,&quot;+,-,./&quot;,&quot;+--,+*&quot;  ,&quot;&quot;,&quot;+,(/&quot;,&quot;+,),(/&quot;,&quot;+-),+*&quot;
                     ,&quot;10 0 d0 &quot;,&quot;8 7 2 2 re &quot;   ,&quot;+*+.&#39;`&#39;@&#39;mi +/+/(mi&quot;};Nyan
                       nyan(Nyan _,N y,A n){
                        N g=v[~-y%32];Nyan
                         s=w[g&gt;&gt;n&amp;3|n*2];
                         for(a=0;*_=*s++;
                         a++,_++,*_++=32)
                         {*_+=*_-32?10:0;
                         if(a%2&amp;&amp;*_/16==3
                         ){if(g&gt;&gt;8)*_=105-*_;
                        _++;*_++=32;*_=~-a&amp;&amp;a-13
                        ?108:109;}}return n?n-9?nyan
                       (_,y,n-2):_:nyan(_+=~y&amp;&#39; &#39;?sprintf
                      (_,17[w]):0,y,9);}N main(N c){A e[256];
                     p(&quot;/*%%PDF-1.3%%*/&quot;)-2;q(#include&lt;stdio.h&gt;\n);
                    q(#define o *_++&amp;&amp; *_-41\n#define);p(&quot; endstream &quot;);q
                   (main(){for(;*_++;      *_-40?:putchar(o?*_:o?10:41));\n)
                  ;q(#define  endobj          return 0;}\n);q(typedef int ET;/)
                 ;q(*);o(1)*b=~(p(D                 (/Length 2 0 R)&quot;stream\n&quot;))
                ;for(p(&quot;BT 12 818&quot;                    &quot; Td/%c 12 Tf 12 TL%%%c/&quot;
               &quot;static char*_=\&quot;&quot;                       &quot; \\\n&quot;,7[v],*v/2);c=
              getchar(),~c;c-10?                         p(&quot;/%c 12 Tf(\\%o)&quot;
             &quot;Tj&quot;,v[~-c%&#39; &#39;&lt;25[                         v]&amp;&amp;!~-(~-c/&#39;@&#39;)?0
            :7],c):(p(&quot;()&#39;&quot;)))                         ;p(&quot;%%\&quot;;\nET &quot;);*
           b-=~_;p(Y&quot;/*&quot;);E{a                         =nyan(e+sprintf(e,
          16[w]),c,6)-e;o(c-                         59)p(D(/Length %d)
         &quot;stream\n%s&quot;Y,a,e)                         ;}o(2)p(&quot; %u&quot;S,*b);
        o(3)p(D(/Pages 4 0                         R)S);o(4)p(D(/Count
       1/MediaBox[0 0 595                         842]/Kids[5 0 R])S)
      ;o(5)p(C,4,0,6e-2,                         6e-2f,d,122,d);E p(
     &quot;/%c&quot;,~-c/6+~14?c:                         d);q(]&gt;&gt;/CharProcs&lt;&lt;)
    ;E if(~-c/6+~14)p(                           &quot;/%c %d 0 R&quot;,c,c+~58);
   for(q(&gt;&gt;/Widths[),                             c=59;--c;p(&quot; 10&quot;));a=p
  (&quot;]&gt;&gt;&gt;&gt;&gt;&gt;/Contents 1                              0 R&gt;&gt;&quot;S);for(p(&quot;xref\
 0 %d &quot;,--d);c&lt;d;p(&quot;%010u\
 %05d n  &quot;,*(c+++b),NULL));
  return!(p(DANCE,d,a));}