#include&lt;stdio.h&gt; /******** SpigotQuine -- usage: ./spigot [pi or e] ********/
char*s=&quot;G1%%xJ{;Q7wunmuGuu%%uu#include&lt;stdio.h&gt;/*Spigot_Quine*/#include&lt;stdli&quot;
&quot;b.h&gt;/*_IOCCC2012_*/int*e,&quot;    &quot;i,j,k,n&quot;     &quot;;char*q&quot;    &quot;,*a,*d,*z,*p=%s%c;&quot;
&quot;int&quot; &quot;%cmain(){a=calloc(&quot;                                 &quot;1,1e4+n*2);;for(*&quot;
&quot;a=\0@3,z=d=a+n+1,j=n*8-7;&quot;    &quot;k=0,j-1&quot;     &quot;;j-=2){&quot;    &quot;for(a[1]+=2;--z-a;&quot;
&quot;*z=k%%10,k/=10)k+=j/2**z;;for(;k=k%%j*&quot;     &quot;10+*++z,z&lt;d;*z=k/j&quot; &quot;);;\0@2,z=&quot;
&quot;d=a+n*2,*z=1,j=0;++j&lt;n;){for(;k=k%%&quot;           &quot;j*10+*z,a-z;*z&quot;   &quot;--=k/j)a+&quot;
&quot;+;for(k=0;z-d;*a--=k%%10,k/=10)k+&quot;               &quot;=*++z+*a\0&quot;     &quot;@;}d+=spr&quot;
&quot;intf(q=d-20,p,p,34,32,n+1)+2;;;;&quot;                 &quot;for(n=n*2&quot;     &quot;0-400;k&lt;n&quot;
&quot;;++k%%n?j=+puts(&quot;                                                 &quot;d)&lt;0:(d++&quot;
&quot;[j]=47,d[j-2&quot;                                                     &quot;]=42),k%%&quot;
&quot;20&lt;1?puts(d&quot;                                                      &quot;-1),a++:0&quot;
&quot;){for(i=-1&quot;                                                       &quot;;i++&lt;32;!&quot;
&quot;*z?q[662]&quot;          &quot;=0,z=q+207:&quot;                 &quot;*z+z[1]&lt;6&quot;     &quot;5?z+=11:*&quot;
&quot;z==34?p=0&quot;         &quot;:0)d[i]=((k/2&quot;               &quot;0-1?275*q[&quot;     &quot;*a+10]-8*&quot;
&quot;q[*a+0]-8&quot;         &quot;:128)&gt;&gt;(i/11+k/&quot;           &quot;4%%5*3))&amp;1?k&quot;     &quot;/3*!j&amp;&amp;p?&quot;
&quot;j=34:(j=&quot;           &quot;i+1,*z++):32;k/3*&quot;     &quot;j--&amp;&amp;p?d[z--,j]=3&quot;   &quot;4:0;}}int&quot;
&quot;*y,n=%d;/*..~&quot;,*f=&quot;nnLa5~z23~|22t$q(s82r&amp;q(s82q&#39;q(s8;q(s8;q(s8:&quot; &quot;r(s8:r(s8:&quot;
&quot;q)s89r)sLr#t+&quot; &quot;sLx,uJw-yGu/wnnnU&quot;,*g=&quot;nnLa&lt;z::t$u88t(u67t*u57s,t56t,t56~v56&quot;
&quot;tF6tF6tF8t1p&quot;   &quot;Nu/qOv+rS}Xxnng&quot;;int main(int m,char**v){char a[2012],b[2012
],*p=a,*r=m&gt;1     &amp;&amp;*v[1]==&#39;e&#39;?g:f,*q=b,*t=r;;sprintf(a,&quot;%s%s%s&quot;,s,r==g?s+281:
s+168,s+386);     sprintf(b,a+22,a,34,32,24);for(sprintf(a,&quot;%.33s/*%.28s*/%.3&quot;
&quot;3s/*%.28s*/%&quot;   &quot;.33s\&quot;%s*/&quot;,b,b+66,b+33,b+76,b+66,b+99);*r;r++){;for(m=0;m++
&lt;(*r-34)%77;*q++=*r&gt;111?32:*p++)(q-b)%66&lt;1?*q++=10:0;*r-110&amp;&amp;*r-126&amp;&amp;r-t&lt;(t-g?
62:45)?*q++=34,((q-b)%66&lt;1?*q++=10,*q++=34:0):0;}*q=0;puts(b+1);}/*IOCCC2012*/