#include &lt;stdio.h&gt;
#include &lt;string.h&gt;

#define Q(B,q,b) s=j[B]; e=*s; *s=0; printf(q,b,b,b); *s=e; H=s;
#define W(a,b) r[O].c=a,r[O].f=b,O++
#define X(B) { int y=A; B; A=y; }
#define R return
#define M 1&lt;&lt;18
#define If char
#define fi &quot;%s&quot;
#define IF for
#define FI &quot;r&quot;
#define long
#define do










typedef  struct { int c,(*f)(); If*t,*h; } T; T*a,*r; int I[M],c[M]={&#39;\0&#39;} ,n
,N,i do,p ; char*s,*H,*z[M],f[M],o[M ],*_ [M ],**l =_ ,e ; int O=6,A=&#39;\5&#39;,x=5
,y=&#39;\0&#39;,g=2;k(p){a[p+2].h=H; R p+2; } S(p){ a[I[n++]=a[p].c&gt;&gt;8].h=H; return ~
p-&#39;\1&#39;;}J(p){R~a[p].c&gt;&gt;8;}C(){ A=O; W(O+1&lt;&lt;8,J); } B(p){ c[g+&#39;\1&#39;]=O;C(do);c[
g+=&#39;\2&#39;]=&#39;\0&#39;;R 1;}h(p){ Z(p); r[O-3].c+=256; R 1; } V(){ *I=n=&#39;\1&#39;; for(; *a
-&gt;t; do ){do a-&gt;t=a[1].h=s; IF(i=N=0; i&lt;n; i++){ p=I[i]; H=a[p ]do.h;for(; p&gt;
0&amp;&amp;a[do p].t-s;){a[p].h&amp;&amp;a[p].h-H&gt;0&amp;&amp;(H=a[p].h);e=a[p].c;a[p].t=s;p=do e&amp;&amp;e-*
s?p+&#39;\1&#39;:~a[p].f(p);}p&lt;0&amp;&amp;(I[N++]=~p);}n=N;s++;}}U(p){X(D(p)); c[g+=&#39;\2&#39;]=O ;
 return Z(p); } d(p){ C(); W(0,k); W(0,J); R 1 ; } q (p ){ C (); X (for(;*++s
!=&#39;\&quot;&#39;; )F(p); ); return 1; } Z(p){ r[A].c =O +1 &lt;&lt;&#39;\10&#39;; r [A ].f  =do J   ;
 { int y=A; W(O+*&quot;\2void&quot;&lt;&lt;8 ,J ); C (); W (y*1 + &quot;signed&quot; [ 6 ] +1 &lt;&lt;&#39;\10&#39;,S
  do   )do ; } return  &#39;\1&#39;;} F(p){ R*s?C(),*s==*&quot;\\&amp;&quot;  long&amp;&amp;*++do s  do  ==
 &#39;n&#39;&amp;&amp;(*do s  =*&quot;\nextern&quot;),W (*s ,k ),W ( (4+5)[&quot;volatile*&quot;],J),&#39;\1&#39;  :&#39;\0&#39;; 
} E(p){ int V =*&quot;\0float&quot;; C (); X(s++;V=(*s++==*&quot;^double&quot;);c[g+=long 2]long=
0;s-=!V;for(; *s!=&quot;]int&quot;[0];s++){e=*s;s+=2*(s[1]==*&quot;-for&quot; ); s=s;for(;e&lt;=do*s
; e++){long C(); V?W(e,J):(W(e,k),W(0,J),U(p)); } } d(p); V||(W(&#39;\0&#39;,J)); D(p
); ); return 1; } j(p){ If*r=z[a[p].c&gt;&gt;8],**D=l; IF(; l-_&amp;&amp;l [-*&quot;\2$&quot;]-H&gt;=0&amp;&amp;
(l [-*&quot;\1do&quot;]!=s||l[-2]!=H||r-l[-3]&lt;=0); )l -=3 ; l ==_ ||l [-*&quot;\1if(&quot;] -H &lt;=
0 * !&quot;\0auto&quot;?*l++=r,*l++=H,*l++=s,l:(l=D); R 0; } L(p){ W(A +*&quot;\1for&quot;&lt;&lt;8,S);
R 1+*&quot;\0while&quot;; } Y (p ){ z [y ]do=++do s  do; s=strchr (s ,*&quot;\nshort&quot;);W(y++
&lt;&lt; *&quot;\btypedef&quot;,j); r [x ].c =O  long&lt;&lt;&#39;\10&#39;; r [x ].f =S ; do x =O do ; C  (
); return   &#39;\1&#39;; } D (p ){ r [c [g ]].c =O &lt;&lt;8 ; c [g ]=&#39;\0&#39;;A=c[--do g]; --
g; return *&quot;\1switch&quot;; } T  b [ 12 + (M) + 321 ]={ {&#39;\0&#39;,&#39;\0&#39;,&quot;-&quot;},{&#39;*&#39;,Z } ,
{ &#39;+&#39;,L},{ &#39;\&quot;&#39;,q} ,{ &#39;[&#39;long ,E } ,{ 70-94+ do &#39;@&#39;do ,B } ,{ &#39;)&#39;,D } do,{124

                  ,U},
                 {46,d}
                  ,{32
                  ,Y},
                {63,h},{
               0,F},{0,0,          &quot;Make a contract with me&quot;
              },{&#39;(&#39;*32,S}
             ,{&#39;\0&#39;,k},{0,J,     &quot;and become a magical girl! &quot;
            },{&#39;@&#39;*4,J},{0,J
            },{&#39;@&#39;,0} };main
           (  int B,If**j){ a
           =b;if(B&gt;=3){s=f;r=
          b+&#39;\14&#39;; f[fread(f,1,
          M,fopen(j[1],FI))]=0;
          V(); W(0,J); IF(i=0;
          i&lt;y;i++){*strchr(z[i
           ],10)=0;}o[fread(s
            =o,1,M,fopen(j[2
             ],FI))]=0; a=r
               ;V(); H=o;
         IF( j=_;j!=l; j+=3 ){Q
         (1,fi,H);Q(2,*j,j[1]);
          }printf(fi,H);}R 0;}