#  include&lt;stdio.h&gt;//  .IOCCC                                         Fluid-  #
#  include &lt;unistd.h&gt;  //2012                                         _Sim!_  #
#  include&lt;complex.h&gt;  //||||                     ,____.              IOCCC-  #
#  define              h for(                     x=011;              2012/*  #
#  */-1&gt;x              ++;)b[                     x]//-&#39;              winner  #
#  define              f(p,e)                                         for(/*  #
#  */p=a;              e,p&lt;r;                                        p+=5)//  #
#  define              z(e,i)                                        f(p,p/*  #
## */[i]=e)f(q,w=cabs  (d=*p-  *q)/2-     1)if(0  &lt;(x=1-      w))p[i]+=w*/// ##
   double complex a [  97687]  ,*p,*q     ,*r=a,  w=0,d;    int x,y;char b/* ##
## */[6856]=&quot;\x1b[2J&quot;  &quot;\x1b&quot;  &quot;[1;1H     &quot;, *o=  b, *t;   int main   (){/** ##
## */for(              ;0&lt;(x=  getc (     stdin)  );)w=x  &gt;10?32&lt;     x?4[/* ##
## */*r++              =w,r]=  w+1,*r     =r[5]=  x==35,  r+=9:0      ,w-I/* ##
## */:(x=              w+2);;  for(;;     puts(o  ),o=b+  4){z(p      [1]*/* ##
## */9,2)              w;z(G,  3)(d*(     3-p[2]  -q[2])  *P+p[4      ]*V-/* ##
## */q[4]              *V)/p[  2];h=0     ;f(p,(  t=b+10  +(x=*p      *I)+/* ##
## */80*(              y=*p/2  ),*p+=p    [4]+=p  [3]/10  *!p[1])     )x=0/* ##
## */ &lt;=x              &amp;&amp;x&lt;79   &amp;&amp;0&lt;=y&amp;&amp;y&lt;23?1[1  [*t|=8   ,t]|=4,t+=80]=1/* ##
## */, *t              |=2:0;    h=&quot; &#39;`-.|//,\\&quot;  &quot;|\\_&quot;    &quot;\\/\x23\n&quot;[x/** ##
## */%80-              9?x[b]      :16];;usleep(  12321)      ;}return 0;}/* ##
####                                                                       ####
###############################################################################
**###########################################################################*/