                                                      #include&lt;stdio.h&gt;
                                                typedef unsigned int _;_ d,b,
                                           #define i(I1,Il,lI)if(Il){lI;}else{I1;}
                                         I[256],			n,y,a,r,u,k,o
                                       ,L,l[					256],O,K[
                                      /**/					    #define\
                                      q(g)						g char\
                                      *C,						   *Q,c[\
                                      ]=						      &quot;KfW&quot;\
                                      &quot;&quot;							&quot;Ww|&quot;\
                                       /*							   &#39;UU!\
                                        %							     NYA!\
                                        */							       &quot;Z}&quot;\
                                 &quot;;fRo?JtJaV&lt;x4@*?R?&amp;JV1&quot;						 &quot;.s&quot;\
                             &quot;{Fyj2_;khB1xQ5oxm~mS@B|(pa&gt;oRU&quot;						  &quot;Ro&quot;\
                          &quot;nB}h@o?)d.X)NSTIUCz7@%&quot;,*s[]={c,&quot;#en&quot;					    &quot;di&quot;\
                       &quot;f/*}||1;\n__DATA__\40*/\n\n#ifndef\40q\n#d&quot;					     &quot;ef&quot;\
                      &quot;ine\x20q\n#include&lt;stdio.h&gt;\ntypedef\40unsign&quot;					       &quot;e&quot;\
                    &quot;d\x20int\x20_;_\x20K[]={\n#include\40__FILE__\n#u&quot;						&quot;n&quot;\
                   &quot;def q&quot;,&quot;0},L,O,l[256],I[256],n,y,a,r,u,k,o;&quot;#g&quot;char&quot;					 &quot;*&quot;\
                 &quot;S,s[]=\&quot;&quot;,c,c,&quot;\&quot;;int main(){X();for(S=s+*K;*S&gt;37;){for&quot;					 &quot;(o&quot;\
                &quot;=0;o&lt;5;o++)r=r*85+(83+*S++)%89;r&quot;,&quot;^=*x();for(o=0;o&lt;4;o++&quot;					  &quot;)&quot;\
                &quot;{s[O++]=r&amp;255;r&gt;&gt;=8;}}return!fwrite(s,O-*S%5,1,stdout);}\n&quot;					   &quot;#&quot;\
               &quot;endif&quot;,c},S[256]=&quot;#ifdef/*\n&#39;true&#39;\40or\40q{\nexec\40head\40&quot;					   &quot;-&quot;\
              &quot;8\40$0\n};for(open$O,$0;&lt;$O&gt;;print\40if$f){$f|=/^$/;}q{*/q&quot;,/*					    */z;
              256];q(_*x(){if(!L--){y+=++a;for(o=0;o&lt;256;y=l[o++]=I[255&amp;(k&gt;&gt;10					    )]+u
              ){n^=(o&amp;1)?n&gt;&gt;(( o&amp; 2)?16:6):n&lt;&lt;((o&amp;2)?2:13);u=I[o];k=I[o]=I[255&amp;					    (u&gt;&gt;
             2)]+(n+=I[(o+128)  &amp;   255]) +y;}L=255;}return&amp;l[L];}_*X(){for(O=0					    ;256
            &gt;O;I[O++]=0);for(O   =     0;   sizeof(K)/sizeof( _)&gt; O;O++)I[O&amp;255]				    ^=K[
            O];for(n=y=a=L=O=0 ;O&lt;1&lt;&lt;24;++   O)x( );r=O=0x0; return&amp;O;})int/*^^*/				    main
           (int p,char**P){FILE* Z=fopen(p&gt;    (+  1)?P[01   ]   :&quot;/dev/urandom&quot;,				    &quot;rb&quot;
          );i(;,Z,O=fread(K,256  ,4,Z);/*P          */     fclose(Z))X();for(p=b=d				    =O=
          0;O&lt;256;K[O++]=0)*K=+  86;for(O                =1;12&gt; O;K[O++]=*x());X();				    for
         (C=Q=S;r-8;){i(*C++=34,  (r-4&amp;&amp;r               -5)||C- S ,;)z=Q[p++];i(;,z				    !=
        32||r-3,i(i(C+=sprintf((    C),                 &quot;%uU&quot;    &quot;,&quot;,K[b++]);i(d=1;C				   =S
       ;i(d=02,b-12,;),b%6,;),r-1                       ,i(b=   fread(c,1,4,stdin);i				   (p
       =O=0,b,for(d=O=0;O&lt;04;O++)d                             +=(c[O]&amp;255)&lt;&lt;(8*O);d				  ^=
      *x();for(p=5;p;c[--p]=O&lt;32?O+                            95:O+6){O=d%85;d/=85;}				 O=
     5)i(d=0,b&lt;4,c[O++]=b?b-1?b-2?36:      37:33:35           ;d=2)c[O]=0,r-4,i(i (d=				 2
    |d,C!=S+6,*C++=(*x()%34)+93;p--),r      -5,*s=          C;d|=2)  )),z ,i(*C++ =92				,
   z-63||C [-1]-63||C&gt;S+76,;)*C++=z))i(                   ;,d&gt;1,d=  d-2  ;Q=s[r]  ;i(			       ;
  ,r&lt;3||  r&gt;5,d=1;i(;,r-1, *C=0)C=S)  i(;,            r-4, p=0)++   r)   i(*(C++ )=
 34,r    &lt;4||r&gt;5||   C&lt;S+    78,;)i       (*C++=0;d=1; C=S   ,r&lt;3       ||       r&gt;
5        ||C&lt;S+     79,;      )i(;,d,                         puts               (
        S);         d=0      )}  return
                                      0;}