               #include\
          &lt;stdio.h&gt;//
        #define Y(\
      _)_##char
    #define \
   _ [9&lt;&lt;9],
  #define j\
 L;fread(&amp;\
 L,4,1,f);u
 #define P\
 &amp;4**(int*\
 )&quot;   &quot;)% \
 3901%31///
  #define q\
   Z[F++]=*E
    #define $\
      for(&quot;IOCCC&quot;
          #include\
              &lt;stdlib.h&gt;










int   *Q,u,i,c,k,B,r=0,w,n,F=0,x,J,u,m,p,s=0,v,e,r,L,a,z,y,D,o,g;   Y(       )*
                                                                    Z=      &quot;Vn&quot;
  &quot;-S&quot;                                                             &quot;xR9Q&quot;   &quot;[$s&quot;
&quot;Zd&amp;o+&quot;                                                            &quot;pf^cM&quot;  &quot;cbac\
J_VHMF_&quot;                                                           &quot;BkaEg^&quot; &quot;x`i_i\
us%d]oWG:&quot;                                                          &quot;r`IZ.6_]H3ec]_\
bWW_^Ej2i[r&quot;                                                         &quot;ZZnJjW[bK`hZakb\
_l]gL3X]d_#$eK&quot;                             &quot;[G3 d[Xe][:V`4Z]Z&quot;      &quot;VfX^]V:X%b]N,ma-j&quot;
&quot;^m57c!`O.qP8lTc^&quot;                    &quot;gm,Um;m`m^^`5n_nci&lt;Wf[h&lt;t+e$%&quot; &quot;]Lha&amp;=l Umc&gt;m#_mdp&quot;
   &quot;h/codZ#i`,&#39;&#39;mbb(fh&quot;          &quot;)h)(^uV9b7dcZq`^d`/*3`#ko`lj;^idad/]0ffxP*]??bff$h`@(Zgtcn&quot;
       &quot;k10t&lt;A6mYZNh!g&amp;a2^j&quot; &quot;!^hOZb!&amp;]bd(]TuqI]#iepZc/XdX(Z X4a!dgpc&gt;0q;]^7p`q*AtqC1j,&#39;#_on tp&quot;
             &quot;on e !1+tA6`db`qciq`&#39;=?ui]&#39;`_`dk`!kx_%]bu]cZX8u_)Z=8@ghg$mlp`a&gt;D_o2_eb)sb)sa0g@f-h&quot;
                  &quot;1bl_DeblFsa&amp;Dt^t4*X *mCC^5Y&quot;,M _ A _ G _ I _ C _ K[]=&quot;&#39;,b}q}a9\&quot;],)&#39;(cDDJr4&quot;
               &quot;Ab,:sdtd/E*#2eXkZ7cPthkq`(stnhct!a:&gt;A;A+jA9&gt;A;A+js&quot;,*E=I;FILE*f;main
           (int d,Y()**t){$;!t;s=c=-D){$,t=v=D?k:J;v++-d;){$,o=L=z=0,s=D?J:k;s+++d
        -B-F;)(o&amp;&amp;(e=m),y=*Q!=(m=Q[u*i+(D?v-u*s:s-u*v)]))^o&amp;&amp;(G[z++]=s-L&gt;20,L=s,o=y);$,
      s=z,o=0;s--;o+=G[s]^s[A]);$;z^w||o;z=w){$,o=1;o&amp;&amp;!--o*D-~-~-w|1[A]|v-a&gt;28&amp;&amp;w^4|1[A]|
    3[A]|!2[A      ]|v-a&gt;5;)$;I[g[I]=2,++g]=-1,-s&lt;w;I[~-g]=A[-s--]);$,a=v,w=z;z--;A[z]=z[G]);
  }}$,v=a        =o;(Z=C+!D*734)[z=a]                         ^3;d=0){$;!~I[v];a=z,v=o=0)$,M[L
 ++]+=          Z[z]^4?-42:o;                                      Z[z++]^4;);      $;~z&amp;&amp;2&gt;(s=I
 [v           ])&amp;4&lt;Z[z]                                                |Z[z]==s         ;)++z,s^2?
             d++,++                                                       v:v&amp;&amp;(o           +=d,a=z,
            z=-1                             );$;v++[                       I]^2;)             ;}}$;d
            ;d                             =c){$,p=*Z;F++                     [I]=                *++
                                        Z%p,*Z;);$,Z=C;x=F                     ,F=
                                        r,s=2,p---7;Q=E,E=Z
                                       ,Z=Q)$;s%x;p^(c=s++[E
                       ])?q*0+c:(q++,  q--));$;K[F];K[F++]-=p
                    );c=fseek((f=fopen(*++t,&quot;rb&quot;))?f:(exit(1)
                   ,f),10,r);j;n=j=j=j;i=j;F=a=fseek(f,n,c);
                  Q=calloc(z=i--*u,4);$;a^z;fread(a+++Q,L&gt;&gt;
                  19,1,f));$;F++&lt;i;r=n){$,n=0,B=u;B;n|=*Q^Q
                  [u*(i-F)+--B]);$,n&amp;&amp;Y(!r&amp;&amp;(D=F-J,J=F);
                 !n&amp;&amp;r;r=x=!put)(10))$;B^u;B++,c=p){$,p=
                0,s=J;s^F;p|=*Q^Q[B+u*(i-s++)]);$;p&amp;&amp;!c;
              )$;++Y        (c*F-J&lt;&lt;1&lt;5*((k=B)-x);put)(32
             ),++c);          $;!p&amp;&amp;c;x=B){$,F-J&lt;&lt;1&lt;Y(D&amp;&amp;
              put)(           10),D=95;D--;D[M]=0);$;main(
               ++D?B:           F,w=a=g=0),!D;);$;x=K[o++]-
                 27;M             [x]*M[K[o++]    -27]&gt;0&amp;&amp;(M
                                    [x]=s));$;     ++c^L;M[c]
                                      &gt;s&amp;&amp;(s=M[       x=c]));$;
                                       3^d||printf      (K+--o,(
                                          *Q P,(e P),      D*!(c+~x);
                                               w++)$,o=     &#39;~&#39;;-~o;)$
                                                 [w]Y(^--     o||put)(D=
                                                   o);0;);c     =Y(~o&amp;&amp;!
                                                    put)(*K+     x);}}}}}