                                                               #/*
                                                               q{G.
                                     */include&lt;stdio.h&gt;        /*G!*/
                                      #define G(g,o)/**/int    g=o;/**/
                                           #define q(b)int o[]={0,0,0,0,\
                                    0};char*p=#b,P[9999],*d=P,*e[]={&quot;(&#39;A`)&quot;\
                                  ,&quot;(A`)&quot;,&quot;(&#39;A)&quot;,&quot;(&#39;A`)&quot;},b/*3792/e887094c*/
                               q(*s=__TIME__;extern void w(){G(g,*o)for(;g--
                          ;);}extern void x(){}extern void y(){}static void z
                       (char*p){for(;(*d=*p++)!=0;d++)*d-=061*(59==*d||*d==81);}int
                         main(){char N[]=&quot;&lt;;iQ=/*do&lt;;dQ=ook8?boc;aQ=odr8&gt;oc;_Q&lt;ox8&gt;oc&quot;
                     &quot;;^Q&lt;d|8=o;]Q&lt;dj8&lt;Pk8&lt;c]&#39;?;QQdi8?P&#39;Q)d8&lt;9`8?c;Qdh8=P&#39;]Q&lt;`c8&gt;PQ9_8&quot;
                   &quot;&gt;b;og8=&#39;&#39;`Q&lt;`b8?&#39;QQ9_8?c;dPe8dQa8&lt;P]Q&lt;``8=;&#39;f8&gt;QQ`]8?ocQQ_8=&#39;&#39;_Q`8aQ&quot;
                &quot;CYOUQWIN!]Q=;of8BQQ)88bc]QA98P&#39;Qo]8&gt;oQQ_8CP;QQ98b`_8@P8(Q`]&#39;^Q=`&#39;]QB)88&quot;
              &quot;bQQ]`8J;QQ`88bc99bd(`8iQ@&#39;&#39;QQo^8E&#39;`8c;QQ&#39;Q``8?QQ`&#39;kQ&lt;o]8B9PQQ`&#39;;_Q&lt;`_8&lt;cbQ&quot;
            &quot;&lt;o_Q&lt;o_QBdo`QQ&#39;;`Q=9`]8=bobQ_o_Q&lt;o]8=&#39;;bQC(88cQ`bcgQ&gt;oP&#39;]8&lt;;cQ&gt;98)^Q?&#39;&#39;oc`Q&gt;&quot;
           &quot;oc&#39;]Q]8&lt;;cQ&gt;`8bbQA``QQ&#39;&#39;`Q?88P;dQ=`)nQ?*/;;&quot;/*}}=~/./;print&quot;cp\40sinon.c\40r&quot;,
                  &quot;un.c\n&quot;;for($i=1;$i&lt;21;$i++){for($j=0;$j&lt;2;$j++){print&quot;gcc\x20-O&quot;,$j*2,
                  &quot;\40run.c\x20-o run&amp;&amp;./run|tee run.c\n&quot;if!($i%(2+$j));}print&quot;sleep $j\n&quot;;
                 } __DATA__ 8M*/;G(Z,60*(60*(10**s+s[1])+s[3]*10+s[4])+s[6]*10+s[7]-1933008
                )G(l,(Z+86400-*o)%86400)G(M,o[3]  *17+o[4]*11)   G(O,(&amp;x-&amp;w)-(&amp;y-&amp;x)?1:0)G(
               m,*o)G(n,m)G(i,0)G(j,O)if(M&gt;197)for(   p=N;*p;     )if(*p&gt;92){*N=p[1  ];N[1]
            =0;for(  O=*p++-90;0&lt;O--;z(  N));p++;}else{   s=       p;for(O=  *p++-59;O--;p++)
         p[-1]=*p;p[-1]=0;z(s);}else{    if(M==0){*o=Z;l=0;         }if(o[O+3]&amp;&amp;o[  O+1]+(O?3:5
         )&gt;l)Z=O;else++o[O+3];o[O+1]     =l;  if(l&lt;60)d+=            sprintf(d,&quot;#include&lt;stdio.h&gt;&quot;
&quot;\12#define G(g,o)  int  g=o;\n#d&quot;       &quot;efine  \161(b&quot;          &quot;)int\40o[]={{ &quot;{%&quot; }}d,%d,%d,%d,%d};char&quot;
      &quot;*p=#b,P[9999],*d=P,*e[]=&quot;         &quot;{\&quot;%s\&quot;, \&quot;&quot;        &quot;%s&quot;    &quot;\&quot;,\&quot;%s\&quot;,\&quot;%s\&quot;},   b\nq(%s)\n&quot;
            ,*o,o[01],o[2],o[3],  o[4]    ,e[3],e[1],      e[2],*e,p);z(&quot;/*;; &quot;);for(i=0;          i++&lt;18
               ;z(&quot;;&quot;))for(j=0;j++&lt;11;n=(n*193+287)      %384 ){m=(97+(67*m    ))%198;for
             (O=0;O++&lt;n%03;z(&quot;Q&quot;)   );s=d;for(z(e[         (  n/3)&amp;3]);m&lt;M      &amp;&amp;s-d;*s++
           =040);}if(l&lt;60)  {for   (z(&quot;;Time:Q&quot;)              ;(l++&lt;60);z       (&quot;#&quot;));for
          (z(&quot;;Heca&quot;/*  */   &quot;t&quot;   &quot;eQII:&quot; &quot;Q&quot;)                ;o[3  ]++      &lt;=24;z(&quot;#&quot;));z
         (Z?&quot;&quot;:&quot;Q(j&quot;     &quot;a&quot;  &quot;m&quot;   &quot;me&quot;   /*                        @     */&quot;d&quot;   &quot;)&quot;);for(z(
       &quot;;GlockQ18&quot;        &quot;C:&quot; /*          *                              */         &quot;Q&quot;);o[4]++&lt;
      25;z(&quot;#&quot;)             );z(                Z-                       1?             &quot;;&quot;:&quot;Q(jam&quot;
     &quot;med);&quot;)                  /*               */                      ;}                 else z(&quot;;&quot;
    &quot;;Gam&quot;                      /*                                     */                    &quot;eQover.&quot;
   &quot;;;&quot;                          /*                                  (-                         */);for
                                  (O=                              0;O                            &lt;77;O
                                    ++)        z(&quot;Q&quot;);z(         &quot;*&quot;                                &quot;&quot;
                                       &quot;/&quot;                    );}
                                          puts           (P);;
                                              return+0;})