 #include      &lt;stdio.h&gt;
#define TA    q=/*XYXY*/
#define/*X    YXY*/CG r=
void p(int    n,int c){;
for(;n--;)    putchar(c)
#define Y(    z)d;d=c++\
%2&lt;1?x=x*4    +z,c%8&gt;5?\
x=x?p(1,x),   0:x:0:0;d=
#define/*X    YX*/C Y(1)
#define/*X    YX*/G Y(2)
 ;}int(*f)(  void),d,c,
 #define/*X  YX*/A Y(0)
  #define/*XY*/AT int\
     m(void/**/){d=
  #define/*XYX*/T Y(3)
 #define GC  d; return\
 0;}int(*f)  (void )=m;
x,q,r; int    main(){if(
f)f();else    {for(puts(
&quot;#include&quot;    &quot;\40\&quot;pro\
g.c\&quot;\n\n     \101T&quot;+0);
d=!d?x=(x=    getchar())
&lt;0?0:x,8*8    :d,TA++c%8
,TA(1+7*q-    q*q)/3,r=c
*15-c*c-36    ,p(r&lt;0?!q+
4:r/6+!q+4    ,32),q||x;
c%=16)q?p(    1,&quot;ACGT&quot;[x
/d&amp;3]),p(q    ,126),p(1,
&quot;TGCA&quot;[x/d    &amp;3]),d/=4,
p(001,10):    puts(c%8?\
&quot;CG&quot;:&quot;TA&quot;)    ;puts(&quot;GC&quot;
 );}return     0;}/**/