#include&lt;stdio.h&gt;
#include&lt;setjmp.h&gt;
#define R return
#define W(x)for(;x;)
#define I typedef
#define H unsigned
I jmp_buf J;
I void P;
I char L;
I int Q;
I H C;
I long long V;
I H char O;
I H short Y;
I H long long Z;
&#x000c;
				       O S[]=&quot;syntax_error!&quot;
				  &quot;M@K~|JOEF\\^~_NHI]&quot;; L*N,*K,*
			     B,*E,*T,*A,*x,D; Q(*k)(),v; V z(P),j,_,*
			   o,b,f,u,s,c,a,t,e,d; J l; Q _k(P){ R*K?*K++:
			 ~-d; } V r(L a){ R a&amp;&amp;putchar(a); } L n(){ R*T=j=
		       k(),++j; } O G(P){ *o=d,longjmp(l,b); } Z g(Y a){ R a
		    &gt;&gt;s|(a&amp;~-e)&lt;&lt;s;} C p(L*T) { W(r(*T++)); *--T-c&amp;&amp;r(c);} L m
		  (P){ W(!((v=A[*T++])-f)); R v; } P q(L**N) { O*q; b=!b; f=-~b;
		 u=f|b; s=b&lt;&lt;u; c=s|f;			       a=s&lt;&lt;f; t=-~u; e=a
	       &lt;&lt;u; D=v=u&lt;&lt;t;q=S				    +c-~t; q[~s]=a;
	      q--[f]+=a;q--[c						]+=a; B=(L*)
	      N+~e*e;x=B+e						   ; A=B+e/f;
	    o=(V*)(x+a								); A[-
	    ~s]=f; T								 =K =A-
	   a*f;A[*--								  q]=c+
	   c; *q=!								   c; W
	  (++j&amp;&amp;*								    ++q)
	  A[*q-a								    ]=j;
	  W(v&lt;D									     +c)
	  x[v-									     D]=
	  v,A[									     v++
	  ]=j;									     ++j
	   ,v=									    D=e/
	    t;									   W(++
	     v&lt;=								  D+f*
	      u)x							       [v-D+~
	      -c]=							      v|a,A[
		v]=A							    [v|a]=j;
		  W((							 A[v]=A[v|a
		    ]=j							 ,++v&lt;a*u+~t));
		       for(						 ; E=*++N;T[~d]
			  =a)W						 (*T++=*E++);k=
			    T
		    -K?_k:
		 getchar; } Z h
	       (C a){ R(g(a)&lt;&lt;s*
	      f)+g(a&gt;&gt;s*f); } P _i	     (L*T)
	     { *o||p(T); } V _b(V a	    ){ Z e=a
	    ; R A[*T++]!=v+c?G():~-v	   ?a&lt;&lt;z():c-A
	   [*T++]+b	     ?--T,a&gt;&gt;	   z():e&gt;&gt;z();}
	  V _c(L*	       l){ T=B	    +a; W(j)*T--
	  =v+j%c		,j/=c;	     E=B+  (*B==
	  a+c+u			);W(T&lt;		    B+a)*
	  E++=*			++T; T		     =E ;
	  l-B&amp;&amp;			++ *--		     E; }
	   P M(			Z k){		    L*p,e
	    =a&gt;&gt;		u; m		   ()&amp;&amp;G(
	     ); p	       =T=B		  ; _=j=k
	      ; v=u	     &lt;&lt;t,*		T=a; j&lt;d
	      &amp;&amp;(*T+++=c+u,j=j==-j?++p,--j:-j);!j?*T++=
	     v:_c(p); *T++=-~s; *T++=v;*T++=a*t-s; p=T
	   ; E=T+=s*f; W(k)*T--=x[k&amp;~-a/f],k&gt;&gt;=e; W(T
	  -e*f&gt;p)*T--=v; W(T&lt;E)*p++=*++T; *p=d;} P U
	  (L*E){ V*N=o,f; *E=f=d; W(++f&lt;c*u-u)*++N
	  &amp;&amp;(M(*N),r(f+a*u),r(-~s),p(B),*(T=E)=d)
	  ; } V w(P){ L*S=N,*x=N; E=T=B; E+=a
	  &lt;&lt;f;
	  W(T
	  &lt;E

	  &amp;&amp;n(									   ))*
	  T==a									   -~u
	  ?U(T),T:*T==c?E=S?T=S:T:S?T:*T==(a|u)?S=T:*T==a*f-c/f?E=T:!x&amp;&amp;A[*T]!=f?x=T++:
	  ++T; *T=d;R j&amp;&amp;!x?w():T-B; } P _d(V e){ L T=c*f-f;V o=j*e+v; D=d; A[v]==T++?D
	  =u&lt;&lt;t:e&gt;c&amp;&amp;A[v]==T++&amp;&amp;(v|a)-a*-~f&lt;~-s?D=b+(v&amp;a)+a*f-c:d; D&amp;&amp;(j=o-D); }V y(P){
	  V a=z();W(m()&amp;&amp;v&lt;c+f&amp;&amp;(v-=u&lt;&lt;b)&gt;=d)v?v-b?v-f?v-u?v-=t,a=_b(a):(a&amp;=z()):(a%=z(
	  )):(a/=z()):(a*=z()); R--T,a;} V _f(P){ V e=c; j=d; D=b; *T==u&lt;&lt;t&amp;&amp;(e-=f)&amp;&amp;(*
	  ++T|a)&gt;&gt;f==a-f&amp;&amp;(e&lt;&lt;=b)&amp;&amp;T++; W(D&amp;&amp;(v=*T++))_d(e); R--T,j; } V F(P){ V n=y();
	  W(m()&amp;&amp;v&lt;u*f)v&lt;t?n+=(v-f)*y():v-b^t?n^=y():(n|=y()); R--T,n; } V i(Z n){R n&gt;&gt;
	  a/f?
	  n&gt;&gt;a
			  ?h(n)&lt;&lt;a|h(n&gt;&gt;a
		     ):h(n):g(n); } Q main(Q x
		    ,L**K){ V*A; q(K); W(w())**
		  K-c*c-b||p(B),_i(!setjmp(l)?T=B
		,M(((A=(*o=m()==c-~s&amp;&amp;(j=a|T[-b])&amp;&amp;
	      s-m()==~s)?&amp;o[j-a*u]:(T=B,&amp;_)),*A=F())
	     ),B:(L*)S);		   } V z(P){ V
	    s; W(m()			       &amp;&amp;v&lt;=f*c
	    )R v&lt;t				 ?(v-f)*
	   z():(				  v-=u&lt;&lt;
	   f)&lt;f					   ?v?--v
	  ?G()					    : i(z(
	  )):~					     z( ):
	  (v-=					     f) &lt;u
	  ?v?s					     = F()
	  ,m()					     ==a&gt;&gt;
	   b?s					    :G ():
	   _:!					    (v-=
	    t)?					  --T,_f
	     ():				v-f?o[
	      (T[			      -b]|a)-
	      a*u]:			      !z();
		G();			       }