#include&lt;stdio.h&gt;
int a = 256;int main(){for(char b[a+a+a],
*c=b ,*d=b+ a ,*e=b+a+a,*f,*g=fgets(e,(b[
a]=b [a+a] =a- a,a) , stdin);c[0]=a-a,f=c
,c=d ,d=e ,e=f, f= g,g =0,g = fgets(e,a+a
-a+ a -a+a -a+ a- +a,stdin ),f +a-a ; pu\
tchar(+10)) { for( int h= 1,i=1,j, k=0 ,l
=e[0]==32,m,n=0,o=c [ 0]== 32, p, q=0;d[q
];j=k,k=l,m=n,n=o,p=(j)+(k* 2 )+(l =(i = 
e[ q]&amp;&amp;i ) &amp;&amp;e[q +1 ]== 32,l*4)+(m* 8 )+(
16*  n  )+(  o  =(h =c[ q]&amp;&amp;h)&amp;&amp;c[q+1]== 
32,o* (16+16) )+0-0 +0, putchar(&quot; ......&quot;
/*\  (  |||  )  |/|/ / */&quot;.&#39;)|)\\\\\\\\&#39;&quot;
&quot;&quot; &quot;|||&quot;   &quot;|||&quot; &quot;|&#39;&quot; &quot;)|)\\\\\\\\&#39;/|/(/&quot;
&quot;(/&#39;/|/\\|\\|&#39;/|/(/(/&#39;/|/\\|\\|&quot;[d[q++]==
32?p:0]));}}/* typographic tributaries */