#include &lt;stdio.h&gt;
#include &lt;unistd.h&gt;
#include &lt;time.h&gt;
#define p return 
#define X typedef
#define E {
#define B }
#define stup(y)printf(&quot;%.11s\n&quot;,(char*)y);
#define $ printf(&quot;\x1b&quot;
#define G(y)usleep(y);fflush(stdout);
#define O __DATE__+7
#define K printf(
X unsigned short P;
X int _;
_ s=41456; //Sleeping time factor
X char H;
_ o,b,a,f,g,k, m; // Oh, be a fine girl, kiss me
FILE *W;
X enum  {T,F}  z; //True &amp; False
X double w;
_ a5_, N = 11,A4=1&lt;&lt;3,a8_=17,A8=2*2,aI_=~-(__FLT_MAX_EXP__&lt;&lt;F);
H l[]=&quot;uDSYT8|TCPZ8|TVCTKp]X^EY|XKPC8aYTRUPp]ZPXU&quot;;H I[]=&quot;Fo~y*lcdn*yego*Oky~ox*ommy&quot;;/*
						      /\
						      c_
						     [9];
			alpha Ursae Minoris A	     main
						    */_ a1,
						   a3 ,a4=
						   024;P a2
						  ,a5;w Z( w
						 D,_ Y)E if(Y
						 ==T)p F;if(Y
						==!0)p D; w b=
					       Z(D,Y/2);if(Y&gt;2	    /* alpha Ursae Minoris Ab*/
					       )p b*b*D;p b*b ;
					      B _ u(_ x) E if( x			    &lt;2)p
					      F;p x*u(x-unix); B
	/*alpha Ursae Minoris B*/	    _ vir(H __[]) E _ e,
					    q=0;for(e=T;e[__];e++)
	   q=q*				    -~9+__[e]-48;p q;B P A
					   (H *a7_, _ a6_ );w V(_ v
					  ,_ i){v%=0550;w D=&#39;-&#39;-&#39;-&#39;;
					 for(i-=i;i^__CHAR_BIT__;i++
 )D+=Z(_POSIX_TRACE,i)*Z(0x1.1df46a226e211p-6 *v,2*i)/u(2*i);p D;B _ main(a6,n)_ a6;H**n;E _ a7,A1,a1_,a8,t,
    A6,D,Y;size_t a3_;_ A2[]=E&#39;q&#39;,W_OK,5911774,&#39;y&#39;,13,1052160,77,15,1709568,&#39;5&#39;,a8_,1314816,34,18,1446400
       ,91,22,1314816,12,28,F_OK B;time_t j =time(NULL);a4 *= &#39;_&#39; ;float and [] =/*trolling is a art */
	  E  4612954808543207739097088.0, 207.285645,  214354950132336733650542884425029386240.0 B ;
	    struct tm  R = *localtime (&amp;j) ;for (;t=aI_ ,a5_[l];) l[a5_++] ^=-~__LINE__ ; A6=a4 +=
	      R.tm_year;a4 /=&#39;d&#39;;ssize_t A3 =1;k=A6/&#39;d&#39;,b=k/A8,a=k%4,o=(k-((k+A4)/25)+1)/F_TEST
		 ,m=(19*(A6%a4 )+k-b-o+__DBL_DIG__)%30,k=(A6%&#39;d&#39;)/R_OK;H*a2_=NULL;f=(A6%&#39;d&#39;)%
		    R_OK,g=(&#39; &#39;+2*a+SEEK_END*k-m-f)%7,k=__ATOMIC_SEQ_CST;W=fopen(__FILE__,
		      &quot;r&quot; ); $&quot;[40m\033[2J\033[;H\x1b[?25l&quot;);if(*(H *)(_[])E X_OK B)stup
			 (and)A3 =getdelim(&amp;a2_,&amp;a3_,&#39;\0&#39;, W);b=((A6%19)+N*m+22*g)/(N*
			   &#39;)&#39;),o=m+g-(~-A4)*b+&#39;r&#39;,D=o/31;for(;a1[I];a1++,a5_=0xb3)
			      I[a1 ]^= &#39;-&#39;-&#39;#&#39;;Y=o% ~-&#39; &#39; +F;for(a3 =T;a3&lt;A3 ;++
				 a3 )a2 =(a2  +a2_[a3 ])%255,a5 =(a5 +a2 )%t;
				  if((a5 &lt;&lt;8|a2 )^s) goto a4_;$ &quot;[1;12H  &quot; )
				 ;G(a4 *s)a4 ^=a4 ;k*=2172211;while(a5_--&gt;-1)
				 E $ &quot;[40m\x1b[2J&quot;);for(a6=W_OK;a6&lt;025;a6 +=3)
				E a7  = A2 [ a6 -__FLT_RADIX__ ] - 0102, a8 =k
			       + a6 [A2],a1 = A2[~-a6 ] *0x1.db6db6db6a92ap+0 ;
			      a1-=~-__DBL_DIG__,a1_=a7 *V(a5_,_XOPEN_VERSION ) -
			      a1*V(90-a5_,a7 )+66,A1 =(a7*V(90-a5_,a1 ) +a1 *V (
			     a5_,a8 )+0xe)/1.8571428571;if(A1 &gt;T&amp;&amp;a1_&gt;0) E $&quot;[3&quot;
			     &quot;8;2;%d;%d;%dm&quot;, (a8&gt;&gt; 16  )&amp;t,(a8&gt;&gt;8)&amp; 255,a8 &amp;t);$
			    &quot;[%d;%dH%c %.*s&quot;,A1,a1_	   ,a5_&gt;90?46:111,6,a5_&gt;45
			   ?&quot;&quot;:l+ ((a6-F_TLOCK) /	      __ATOMIC_RELEASE)*6);
			   B B G(u(A4 ) )B/**/		       a4_:$    &quot;[H\x1b[0m&quot;
			  &quot;\x1b[?25h&quot;) ;if(			  ( D^ (R.tm_mon+1))
			  == (Y-= R./* */			    tm_mday) ) E   K
			 &quot;%s\n&quot;,I);B K				       &quot;&quot;     &quot;%d\n&quot;,
			vir(O)  );p					  a4 ;B //END\
			OF  THIS					     ENTRY IS\
		       N E A R						       SO NEAR\
		      .*****							 ******\
		      ****							    ***\
		     .									.













