
  #define/**/Q(   q)int*P,t,u,M                                  [99999],                                                          *S=3557\
  +M,*C=M+3800;   char*Q=#q;int                                    (main)                                                            (){q;}
    # include       &lt;stdio.h&gt;                                       /*IOC                                                             CCC*/
     Q(for(;*       Q&gt;34?(*S                                        ++=*Q                                                             ++):*
     (Q+= *Q-       27?1:Q[2     ]/49+    4););                     for (          S=M+9                ;*C;u     =t%9,t              &lt;18?*
     ++S=t&lt;0?       *C++%92*    57-t-500:t&lt;9?M[u]:M        [u]++:t&lt;27?M[u       ]=*S--:u?t=*        S--,u&lt;2?M[t]=*S--:u&lt;     3?C+=*S--?t:0,
     0:u-6?*S       =u&lt;4?*S-     t:u/*ABCDEFGH*/&lt;5?*     S%t:*S&lt;t:putchar     (t):(*S=M[*S]))t     =*C++-93;return+0**&quot;    Ler[Tsaxiyj.V}&lt;\
     dzSGs`Fk       {YezYTtb     x0d{iy        kNT}?d   zaxiyjE   K}TdzHe    iy`Me{      Tf|)dz   HeiyH       eiyjxiyax   Ldz2sx     Ke{&#39;d\
     |Yd{2sy?       [saY^{tG     erjxuj        xvbqax`  {)dzc       kydj/    dzjxkya_}JdziHf}Ydz -Vw2d         rQ)qJe_y  h@*}&lt;d       zHeh\
     yAehy)*n       x{qnxKe{     Df|Qd{         uc)e{&amp;  dzZfh       yCehy    6fuchyex;e{ZdzIe_yn q1dqD         +u/dcyl5  L}&lt;dzL       IETi\
     {x=b{1g|{uc2d{byaxvcDfd     }&amp;dzDVd       {x6ecOe  z1dcydCf_{{ &quot;{{&quot; }})d|qSf2   T_{x$c{              ;g|{{ &quot;{{&quot; }}u      Ffjx}4czb   q_xucx/d }Jez0dly\
       c/d{hycSf{hychycFc{      hy_)Ic}{q     _0d{qb_}.c  z:eo:T`{xp]q1d`{D`  zD+ulxcx{-dzcCez     7evOe~Hf~0dcx}/dzd~cx    x~6f~m6e0dcx}{}Ud\
          zc(*{x~c0d{Tf         |.dz&#39;d~c5     L}Ecz1d[Ty     /*0+)IFMNFU*+0-    02;&gt;@=,(#155        5546231rst%wvu#08OCC       C*/#include/*#&quot;



     &quot;exclude*/&lt;stdio.                                                                                                  h&gt;#def\
    ine/**/Q(q)int*P,t,u,M[                                                                                             99999],\
      *S=3557+M,*C=M+3800;cha                                                                                             r*Q=#\
       q;int(ma      in)(){q;}                                                                                           Q(@@~c\
       d`c/C@~o        `rrdc~n                                                                                        m/GSghr~o`qqns~hr~\
       mn~lnqd/       FH~g`ud~     bd`rdc~sn~a d/O@~dw ohqdc~`mc~fnmd~sn~    ldds~lx~l`jdq/GSgh       r~hr~`~k`sd     ~o`qqns/LAdqdes~ne\
       ~khed+~H~qdrs~hm~od`bd    /KH&amp;c~ad~otrghmf~to~s  gd~c`hrhdr/X@~qtm~cn vm~sgd~btqs`hm~`mc~i   nhmdc~sgd~bgnhq~      hmuhr\
       hakd/FSghr~hr~`m~dw,     o`qqns     /6Zba4ORRZ    T`]Sa`    fdgO2bPV[   Ta5dT[    MVfbZZHY  b79bVT^    :L;S&lt;J=     X&gt;Q?X\
       @SAZBWCIDNEQF`GXPU      UgW^a         a[bIaZ[Z    afaf_`     Kg`ZYY[    [`gff^     Jg``8OK KT,VNa6      /TZSW`     0cRMWO       3\
       3f][T`-[K               aV,[Z         /6aPWLab    f[P[a3                f`0dPR             `3M3]8/      R[Z-Z,     VZR#MR     TfNTT\
       4d5^$S]8                RMKRVa       MM8T$9aaZ    gaRSg1                NZ1`5^              d`LK].      %&amp;VZ,&#39;     R#gKaZ       f1T\
     T10aa`b].TZ-               KK/28`-6VKf&#39;ZH^P(./Ka8 a)8[O6NaTb            f*[Hd+Z(V              8&amp;3K%)VNTR#&amp;WbX[      H^dcOWOf]8[OR[aT\
    OM2V&#39;$9aLR[RW*               `0+OMW[([14ZLaK%).NO6 RMRS*[0+ZO            WZS]_&lt;&lt;&lt;&lt;               &lt;htt&quot;/*pa*/&quot;p:        //&quot;/*x@*/&quot;cult\
     ofthepartypa                    rrot.co    m/&gt;&gt;&gt;&gt;  &gt;__&lt;-_So             urce_of_P                   arrots                 __(&quot;)
