#define/**/Q(x,y)char*/*                               */q=y#x&quot;,&quot;#y&quot;)&quot;,*p,s[x;}
  /*IOCCC&#39;20*/#include/*                               */&lt;stdio.h&gt;/*-Qlock-*/
    int(y),x,i,k,r;Q(9/*              12               */&lt;&lt;9];float(o)[03];
      void(P)(){*o=r&lt;0/*         11         1          */?r:-r;o[1]=39.5;
       o[2]=22.5;for(k/*      10               2       */=0;++k&lt;39;*o*=i
        /6875.5/(k%2?k/*                               */:-k))y=o[1+k%2
         ]+=*o;k=o[2];/*     9         o-------&gt; 3     */p=s+y+k/2*80;
          }int(main)()/*              /                */{for(p=s;+i&lt;
          1839;*q&gt;32?k/*       8     L         4       */=i++/80-11,y
           =(750&gt;r*r+k/*          7         5          */*k*4)*4+y/2
           ,*p++=r&lt;41?/*               6               */y?&quot;0X+0X+!&quot;
           [y-1]-1:+*q/*                               */++:10:*q++)
           r=i%80-38;;/*                               */;for(x=13,r
           =20;i=3600*/*     \       /    -------+     */--x,i;*p++=
          &quot;OISEA2dC8e&quot;/*      \     /     ------ |     */[x%10],*p+=x
          /10*41)P();r/*       \   /      ------ |     */=10;;sscanf(
         __TIME__,&quot;%d&quot;/*        \ /       ------ |     */&quot;:%d:%d&quot;,&amp;k,&amp;
        x,&amp;i);for(i+=(/*         X        ------ |     */k*60+x)*60;18+
       r;*p=k%2?*p%2?+/*      __/ \__         |  |     */59:44:*p&gt;39?59:
      39,i=!r--?i%3600/*     /  \ /  \        |  |     */*12:i)P();puts(s
    ),&quot;#define/**/Q(x&quot;/*     \__/ \__/        +--+     */&quot;,y)char*q=y#x\&quot;,&quot;
  &quot;\&quot;#y\&quot;)\&quot;,*p,s[x;}&quot;/*                               */&quot;/*IOCCC&#39;20*/#inclu&quot;
&quot;de&lt;stdio.h&gt;/*-Qlock-&quot;/*                               */&quot;*/int(y),x,i,k,r;Q(&quot;)