                                                       #\
                                define C(c           /**/)#c
                               /*size=3173*/#include&lt;stdio.h&gt;
                            /*crc=b7f9ecff.*/#include&lt;stdlib.h&gt;
                           /*Mile/Adele_von_Ascham*/#include&lt;time.h&gt;
                           typedef/**/int(I);I/*:3*/d,i,j,a,b,l,u[16],v
                           [18],w[36],x,y,z,k;char*P=&quot;\n\40(),&quot;,*p,*q,*t[18],m[4];
                          void/**/O(char*q){for(;*q;q++)*q&gt;32?z=111-*q?z=(z+*q)%185,(k?
                          k--:(y=z%37,(x=z/37%7)?printf(*t,t[x],y?w[y-1]:95):y&gt;14&amp;&amp;y&lt;33?x
                          =y&gt;15,printf(t[15+x],x?2&lt;&lt;y%16:l,x?(1&lt;&lt;y%16)-1:1):puts(t[y%28])))
                          ,0:z+82:0;}void/**/Q(I(p),I*q){for(x=0;x&lt;p;x++){q[x]=x;}for(;--p
    &gt;1;q[p]=y)y          =q[x=rand()%-~p],q[x]=q[p];}char/**/n[999]=C(Average?!nQVQd%R&gt;Rd%
  R%          %RNIPRfi#VQ}R;TtuodtsRUd%RUd%RUOSetirwf!RnruterR{RTSniamRtniQ&gt;h.oidts&lt;edulc
 ni                   #V&gt;rebmun&lt;=NIPD-RhtiwRelipmocResaelPRrorre#QNIPRfednfi#V__ELIF__R_
Re               nifed#V~-VU0V;}V{R= R][ORrahcRdengisnuRtsnocRcitatsVesle#Vfidne#V53556
 .           .1RfoRegnarRehtRniRre   getniRnaRsiR]NIP[R erehwQQc.tuptuoR&gt;Rtxt.tupniR
 &lt;         R]NIP[R:egasuV_Redulcn i#VfednfiVfednuVenife dVfedfiVQc%Rs%#V);I/**/main(
  I(      f),char**e){if(f){for(i=    time(NULL),p=n,q=  n+998,x=18;x;p++){*p&gt;32&amp;&amp;!(
         *--q=*p&gt;80&amp;&amp;*p&lt;87?P[*p-   81]:*     p)?t  [( --  x)]=q+1:q;}if(f-2||(d=atoi
        (e[1]))&lt;1||65536&lt;d){;O(&quot;   \&quot;&quot;);             goto  O;}srand(i);Q(16,u);i=0;Q(
       36,w);for(;i&lt;36; i++){w[i]   +=w           [i]&lt;26 ? 97:39; }O(C(ouoo9oBotoo%]#
      ox^#oy_#ozoou#o{ a#o|b#o}c#                o~d#oo-e   #oo.  f#oo/g#oo0h#oo1i#oo
     2j#oo3k#oo4l#o   p));for(j                   =8;EOF   -(i=   getchar());l+=1){a=1+
    rand()%16;for(b  =0;b&lt;a||i-                           main   (0,e);b++)x=d^d/4^d/8^d/
    32,d=  (d/  2|x&lt;&lt;15)&amp;65535;                          b|=   !l&lt;&lt;17;Q(18,v);for(a=0;a&lt;18;
    a++     ){if( (b&amp;(1&lt;&lt;(i=v[a]      ))))*                 m=75+i,O(m),j=i&lt;17&amp;&amp;j&lt;i?i:j;}O(C(
    !)           ); }O(C(oqovoo97o    /n!));i=           0;for(;i&lt;8;O(m))m[2]=35,*m=56+u[i],m[1
    ]=          75   +i++;O(C(oA!oro   oqoo9)          );k=112-j*7;O(C(6o.!Z!Z#5o-!Y!Y#4~!X!X#3}
     !W  !W     #2    |!V!V#1{!U!U#0z!            T!T#/y!S!S#.x!R!R#-w!Q!Q#ooAv!P!P#+o#!O!O#*t!N!
       N#      oo       &gt;s!M!M#oo=r!L!L#oo&lt;q!K!K#   &amp;pIo@:;= oUm#oo98m##oo9=8m#oo9oUm###oo9;=8m#o
               o9   oUm##oo9=oUm#oo98m####          o09]    #o1:^#o2;_#o3&lt;o  ou#o4=a#o5&gt;b#o6?c#o
             7@d#o8A e#o    9B    f#o:Cg#o;          D     h#o&lt;Ei #o=Fj#o&gt;   Gk#o?Hl#oo9os#####
           ));d=0                                          ;}          O:    for(x=y=0;x&lt;8;++
          x)y|=                                                               d&amp;(1&lt;&lt;u[x])?
          1&lt;&lt;                                                               x:0;return
           /*                                                               :9    */
            y                                                                ;    }