#define _c(C)_ (C)&amp;(&#39;|&#39;+3):c_()(C)&gt;&gt;(&#39;\n&#39;-3) __; /**/
#define C char*
#define keyboard &quot;,,B3-u;.(&amp;*5., /(b*(1\036!a%\031m,,,,,\r\n&quot;
#define main(o,oo)oo(o){
#define _ ;case
C
#define c_(cc)c cc=
#define C_(sand)_O(sand)witch
o=keyboard;
#define __ ;break;
C
ccc(
cc)
C
cc;
{
C
cccc=
cc;int
#ifndef lint
#define keyboard &quot;dijs QH.soav Vdtnsaoh DmfpaksoQz;kkt oa, -dijs&quot;
#endif
c;
main(;c_(=(*cc);*cc++)c,for);
#define _O(s)s
main(0xb+(c&gt;&gt;5),C_(s))
_&#39;\v&#39;
:__ _&#39;\f&#39;:
main(c,C_(s));
_c(8098)_c(6055)_c(14779)_c(10682)
#define O_(O)_O(O)stem(ccc(
_c(15276)_c(11196)_c(15150)
#define _C ;return
_c(11070)_c(15663)_c(11583)
}
__
default
:c_(+)o[c&amp;__LINE__-007];
main(c_(-)&#39;-&#39;-1,C_(s))_
0214
:_
0216
:c_(+)025 _
0207
:c_(-)4 _
0233
:c_(+)&#39; &#39;-1;
}}c_(&amp;)&#39;z&#39;+5;
}_C cccc;
}main(,cc)
C
#define O write(1,
c=&quot;O&quot;;
O_(sy) keyboard));
main(;;,for);
read(0,
c,1);*
c_(&amp;)&#39;~&#39;+1
;O ccc(
c),
&#39;\0&#39;);
main(*c,
C_(s));_
4
:O_(sy)&quot;;kkt -oa, dijszdijs QQ&quot;))_C
_
13
:O o+&#39; &#39;,
3
)
#undef main
__ _ 127:O&quot;\b \b&quot;,3)__
default
:O
c,1)
__}}}main(){
cc();
}