--- heckbert.c
+++ heckbert.c
@@ -1,9 +1,9 @@
 #include &lt;ctype.h&gt;
 #include &lt;stdio.h&gt;
 #define _ define
-#_ A putchar
-#_ B return
-#_ C index
+#define A putchar
+#define B return
+#define C index
 char*r,c[300001],*d=&quot;&gt;=&lt;=!===||&amp;&amp;-&gt;++--&gt;&gt;&lt;&lt;&quot;,*i,*l,*j,*m,*k,*n,*h,*y;e,u=1,v,w,
 f=1,p,s,x;main(a,b)char**b;{p=a&gt;1?atoi(b[1]):79;r=c+read(0,j=l=i=c,300000);v=g(
 j,&amp;m);for(k=m;v!=2;j=k,m=n,v=w,k=m){w=g(k,&amp;n);if(v==1&amp;&amp;m-j==1&amp;&amp;*j==35)e&amp;&amp;A(10),