#define _ define
#_ P char
#_ p int
#_ O close(
#_ H strlen(*
#_ h case_2
#_ case_3 default
#_ while switch
#_ L if
#_ I goto
#_ l 1
#_ f write
#_ J else
#_ a(x)get/***/x/***/id())
P z[l&lt;&lt;(1&lt;&lt;l&lt;&lt;1)&lt;&lt;1&lt;&lt;(l&lt;&lt;1)&lt;&lt;(l&lt;&lt;l&lt;&lt;l)&lt;&lt;1],*v;p r,A=0,c=1;
q(Q)P*Q;{L(*++Q){*Q-=7;q(Q);}}main(V,C)P**C;{
p Z=chroot(&quot;/&quot;);L(!a(u)execv((q(v=&quot;/ipu6ljov&quot;),v),C);Z-=kill(l);
while(V){
case_3:L(!(*C[c]-&#39;-&#39;)&amp;&amp;!(C[c][c]-&#39;n&#39;)&amp;&amp;!C[c][c&lt;&lt;c])V--,C++,Z=c;
case 1:O/*/*/0)+O(c*c-c+c/c)&lt;&lt;(c*c));dup(c);O/*/*/c);pipe(z);L(
    for/*/(;;);/*/k()){O/*/*/c);
case_2:L(!--V){O/*/*/c*c+c);wait(A+c*c-c);L(!Z)f(A,&quot;\n&quot;,c);return(A*a(g);};C++;
    f(c/c+c*c,*C,H C));I h;}J O/*/*/c/c+V/V+A*(p)C);
case 0:c=read(1,z,r=H++C));L(c){L(A++)f(&#39;-&#39;-&#39;-&#39;-&#39;+&#39;+&#39;+&#39;,&quot; &quot;,&#39;/&#39;/&#39;/&#39;);
    f(A-A+c-r-c+r,z,r);}J _exit(Z?Z-Z:Z);};main(chroot(&quot;/tmp&quot;)+l,C);
}