 typedef struct A*B,*(*C)();struct A{C(*d)();B e;}*v(),*b;C n[256];
# include &lt;stdio.h&gt;
#define a (d-&gt;e)
#define o (B)printf
#define X(_){return _;}
#define Y(_,A)B _(d,e)B d,e;X(A)
#define Z(P)C P(f,g,h,i)C f,g,h,i;X(P)
#define c(_)(b=(B)malloc(sizeof(*b)),b-&gt;d=_,b-&gt;e=d,b)
#define _(D,E,F,G,H)B D();Y(D/**/f,E)Y(D/**/g,F)Y(D/**/h,G)Y(D/**/i,H)Y(D,(*(*d-&gt;d)(D/**/f,D/**/g,D/**/h,D/**/i))(d,e))
Z(f)
Z(g)
Z(h)
Z(i)
_(j,d,d,j a,j a)
_(k,d,c(h),c(h),c(h))
_(l,c(i),d,c(i),c(i))
_(m,c(g),c(f),l(m a),k(m a))
_(p,d,l(m(d)),k(p a),l(m a))
_(q,l(p(d)),m(d),l a,k(q a))
_(r,m(d),k(mf a),l(r a),k a)
_(s,d,e,o(&quot;0&quot;,s a),o(&quot;1&quot;,s a))
_(t,d,p(e),k(t(a,e)),v(k(t(a,e)),e))
_(u,k(e),l(r(e)),k(v(a,e)),l(v(a,e)))
_(v,e,r(e),u(e,a),u(q(e),a))
_(w,o(&quot;0&quot;),d,s(d),s(d))
_(x,(*n[getchar()])(d),o(&quot;-1&quot;),w(p(d,o(&quot;-&quot;))),xh(d))
_(y,xf(mg()),v(d,p(yf())),v(d,yf()),t(d,yf()))
_(z,xf(yf()),(*(*j(d)-&gt;d)(w,x))(d),xf(k(d)),xf(l(d)))
main(){
n[&#39;(&#39;]=zf;n[&#39;x&#39;]=yi;n[&#39;-&#39;]=yg;
n[&#39;+&#39;]=yh;n[&#39;0&#39;]=zh;n[&#39;1&#39;]=zi;
n[&#39; &#39;]=xf;n[&#39;)&#39;]=n[&#39;\n&#39;]=kf;
o(&quot;\n&quot;,zg(yf()));}