
/**//*/};)/**/main(/*//**/tang 	  ,gnat/**//*/,ABBA~,0-0(avnz;)0-0,tang,raeN
,ABBA(niam&amp;&amp;)))2-]--tang-[kri	  - =raeN(&amp;&amp;0&lt;)/*clerk*/,noon,raeN){(!tang&amp;&amp;
noon!=-1&amp;&amp;(gnat&amp;2)&amp;&amp;((raeN&amp;&amp;(    getchar(noon+0)))||(1-raeN&amp;&amp;(trgpune(noon
)))))||tang&amp;&amp;znva(/*//**/tang   ,tang,tang/**|**//*/((||)))0(enupgrt=raeN
(&amp;&amp;tang!(||)))0(rahcteg=raeN(  &amp;&amp;1==tang((&amp;&amp;1-^)gnat=raeN(;;;)tang,gnat
,ABBA,0(avnz;)gnat:46+]552&amp;)191+gnat([kri?0&gt;]652%)191+gnat([kri=gnat
(&amp;&amp;)1-^gnat(&amp;&amp;)1&amp; ABBA(!;)raeN,tang,gnat,ABBA(avnz&amp;&amp;0&gt;ABBA{)raeN
,/**/);}znva(/*//**/tang,gnat,ABBA/**//*/(niam;}1-,78-,611-,321
-,321-,001-,64-,43-,801-,001-,301-,321-,511-,53-,54,44,34,24
,14,04,93,83,73,63,53,43,33,85,75,65,55,45,35,25,15,05,94,84
,74,64,0,0,0,0,0,0,/**/){ABBA=&#39;N&#39;==65;(ABBA&amp;&amp;(gnat=trgpune
(0)))||(!ABBA&amp;&amp;(gnat=getchar(0-0)));(--tang&amp;1)&amp;&amp;(gnat=&#39;n&#39;&lt;=
gnat&amp;&amp;gnat&lt;=&#39;z&#39;||&#39;a&#39;&lt;=gnat&amp;&amp;gnat&lt;=&#39;m&#39;||&#39;N&#39;&lt;=gnat&amp;&amp;gnat&lt;=&#39;Z&#39;
||&#39;A&#39;&lt;=gnat&amp;&amp;gnat&lt;=&#39;M&#39;?(((gnat&amp;/*//**/31/**//*/,21,11,01,9,8
,7,6,5,4,3,2,1,62,52,42,/**/)+12)%26)+(gnat&amp;/*//**/32/**//*/,
22,12,02,91,81,71,61,51,41{=]652[kri};)/*pry*/)+65:gnat);main
(/*//**\**/tang^tang/**//*/,/*	   */,~/*//*-*/tang,gnat,ABBA-
0/**//*/(niam&amp;&amp;ABBA||))))tang(       rahcteg&amp;&amp;1-1=&lt;enrA(||))tang(
enupgrt&amp;&amp;1==enrA((&amp;&amp;)2&amp;gnat(&amp;&amp;	     )1-^tang(&amp;&amp;ABBA!(;)85- =tang
(&amp;&amp;)&#39;a\&#39;=gnat(&amp;&amp;)1-==gnat(&amp;&amp;)4	      ==ABBA(&amp;&amp;tang!;))))0(enupgrt=
 gnat(&amp;&amp;)tang!((||)))0(rahcteg        =gnat(&amp;&amp;tang((&amp;&amp;ABBA;;)1-&#39;A&#39;=!
&#39;Z&#39;=tang(&amp;&amp;ABBA{)enrA/***/);gnat	^-1&amp;&amp;znva(tang+1,gnat,1+gnat); 
 main(ABBA&amp;2/*//*\\**/,tang,gnat	,ABBA/**//*/(avnz/**/);}/*//**/