#include &lt;stdio.h&gt;
#define A(a) G a();
#define B(a) G (*a)();
#define C(a,b) G a() { printf(b); return X; }
typedef struct F G;A(a)A(b)A(c)A(d)A(e)A(f)A(g)A(h)A(i)A(j)A(k)A(l)A(m)A(n)A(
o)A(p)A(q)A(r)A(s)A(t)A(u)A(v)A(w)A(x)A(y)A(z)A(S)A(N)void Q();struct F{B(a)B
(b)B(c)B(d)B(e)B(f)B(g)B(h)B(i)B(j)B(k)B(l)B(m)B(n)B(o)B(p)B(q)B(r)B(s)B(t)B(
u)B(v)B(w)B(x)B(y)B(z)B(S)B(N)void(*Q)();}X={a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,
q,r,s,t,u,v,w,x,y,z,S,N,Q};C(a,&quot;z&quot;)C(b,&quot;y&quot;)C(c,&quot;x&quot;)C(d,&quot;w&quot;)C(e,&quot;v&quot;)C(f,&quot;u&quot;)C(
g,&quot;t&quot;)C(h,&quot;s&quot;)C(i,&quot;r&quot;)C(j,&quot;q&quot;)C(k,&quot;p&quot;)C(l,&quot;o&quot;)C(m,&quot;n&quot;)C(n,&quot;m&quot;)C(o,&quot;l&quot;)C(p,&quot;k&quot;
)C(q,&quot;j&quot;)C(r,&quot;i&quot;)C(s,&quot;h&quot;)C(t,&quot;g&quot;)C(u,&quot;f&quot;)C(v,&quot;e&quot;)C(w,&quot;d&quot;)C(x,&quot;c&quot;)C(y,&quot;b&quot;)C(z,
&quot;a&quot;)C(S,&quot; &quot;)C(N,&quot;\n&quot;) void Q(){}main(){X=g().s().v().S().j().f().r().x().p().
S().y().i().l().d().m().S().u().l().c().S().q().f().n().k().v().w().S().l().e
().v().i().S().g().s().v().S().o().z().a().b().S().w().l().t().N();}