#include &lt;stdio.h&gt;
#define Q r=R[*p++-&#39;0&#39;];while(
#define B ;break;case
char*s=&quot;Qjou!s\\311^-g\\311^-n\\311^-c\\::^-q-ma%mO1JBHm%BQ-aP1J[O1HB%[Q&lt;nbj\
o)*|gps)&lt;&lt;*txjudi)m*|aQdbtf!::::;sfuvso&lt;aQefgbvmu;aQ&lt;m,,a%CQ&lt;csfbla%bQ&lt;aN2!Q\
\ndbtf!aP2Q;m&gt;aP2Q&lt;a%!D12J!JGJHJOJQJFJSJJJMHS%HD12D12N3!N4\nJUJT%UQm&gt;aP4HC%T\
Qs\\q,,^&gt;m,2&lt;m&gt;aP4HC%SD12N1\nJNQm&gt;s\\..q^aHC%NHb%GN1!D32P3%RN1UP1D12JPQUaP1H\
R%PN4\nQ&lt;g\\(aP3Q(^&gt;aP2Q,2&lt;n\\(aP3Q(^&gt;aP4Hb%OD12D12N2!N3\nJVP3Q,,&lt;jg)aP3Q=&gt;n\
\\(aP3Q(^*m&gt;g\\(aP3Q(^&lt;fmtf!m,,aHC%QN1!N1\nJ#Qqsjoug)#&amp;e]o#-aP1Q*aHb%#Qqvut)\
aP1Q*aHb%FN1\nQm&gt;::::aHC%VP3Q&gt;bupj)hfut)c**aHb%JD12JON1!Qjg)a%LN1UP1D12JIQUa\
P1HL%IQ*m&gt;aN2!N2\nP2Q&lt;fmtf!m,,aHC%MN1!N2&gt;P2Q&gt;aN2\nP2Hbdd!b/d&quot;;k;char R[4][99]
;main(c,v)char**v;{char*p,*r,*q;for(q=s;*q;q++)*q&gt;&#39; &#39;&amp;&amp;(*q)--;{FILE*i=fopen(v
[1],&quot;r&quot;),*o=fopen(q-3,&quot;w&quot;);for(p=s;;p++)switch(*p++){B&#39;M&#39;:Q(k=fgetc(i))!=EOF
&amp;&amp;k!=*p)*r++=k;if(k==EOF){fputs(&quot;}}\n&quot;,o);fclose(o);return system(q-6);}*r=0
B&#39;P&#39;:while(*p!=&#39;`&#39;)fputc(*p++,o)B&#39;O&#39;:Q*r)fputc(*r++,o);p--B&#39;C&#39;:k=0;Q k&lt;*p-&#39;0&#39;
)(*r++=fgetc(i),k++);*r=0 B&#39;I&#39;:k= *p;if(**R==k)goto G B&#39;G&#39;:k= *p;G:p=s;while(
*p!=&#39;$&#39;||p[1]!= k)p++;p++B&#39;N&#39;:R[*p-&#39;0&#39;][0]++;}}}