--- cdupont.c
+++ cdupont.c
@@ -7,8 +7,8 @@
 x=  u [gi][m]; sorryfor_this_unused_but_very_needed_label:
      if(  m==gi){x=0x70;f=0x68;}else goto cOg0 ; b:putchar(x); if(
 !(n-httxkbl++))
-#define yank putchar(&#39;
-  {httxkbl=1;       yank &#39;);goto
+#define yank(x) putchar(x)
+  {httxkbl=1;       yank(&#39; &#39;);goto
    hxi;}goto bl;
            /* hardlyundrstandable, but
 likely to be missed if removed */
@@ -18,7 +18,7 @@
           c0g0 : n=cd&amp;0x40000000L&gt;&gt;0x1e;
  goto         cOgO;   g6w:
                  if(x!=0x2e){i++;goto c0gO;}else /*
-injail*/yank\n&#39;);goto vhjsgfdyl1lgjhd;
+injail*/yank(&#39;\n&#39;);goto vhjsgfdyl1lgjhd;
 cOg0 :
 f=u[m][gi];goto b;bl:m=(i+1)*(4*
 x+3*f)%032;gi=(i+1)*(x+2*f)%0x1a; goto g6w;