#include &lt;stdio.h&gt;
#define D define
#D H(x,y,z) f(p){--p;c=x-_+1];f(c&gt;0){y+1]=z[c];z[c]=y];y]=y+1];}}
#D O(x,y) F(x,int U;int T=0;d=M(U=1);W{f(c==y)b g[T++]=c;f(T==U)g=realloc(g,U&lt;&lt;=1);}g[T]=0;)
#D W Y((c=k?K[--k]:getchar())-EOF)
#D S i[q
#D F(w,z) f(c==w){z h}
#D f if
#D P p&gt;1&amp;&amp;(c=u,
#D _ s[p
#D C =G
#D g S]
#D J(x,y) F(I[x],y)
#D Q P e
#D Y while
#D b break;
#D u _--]
#D m p&amp;&amp;
#D R char*
#D l Z[c]
#D L strlen
#D d i[++q]
#D G c)
#D h ;continue;
#D N s[++p]
#D e _]
#D j x;{R r=M(L(
#D v return
#D w [256]
#D V f(k&gt;o||p&gt;o||q&gt;o)v 2;
R I=&quot;I&#39;d love ta win: the most useful !$&gt;%`/#&lt;&amp;*|^ _OBFUSCATED_ utility. Pleez?&quot;;U(y,x)R y;R*j*x)+L(y)+1);sprintf(r,&quot;%s%s&quot;,*x,y);*x=r;}R T(x)R j x)+1);strcpy(r,x);v
r;}R(i w);static R(Z w);K w;main(a,A)int a;R*A;{int s w,p=0,q=0,n=0,c,k=0;W{V
f(c&gt;=&#39;0&#39;&amp;&amp;c&lt;=&#39;9&#39;){f(!n)N=0;n=1;e=10*e+(c-&#39;0&#39;)h}n=0;J(39,m
sprintf(d=M(13),&quot;%d&quot;,e))
J(37,q&amp;&amp;puts(g))J(34,q&amp;&amp;printf(&quot;%s&quot;,g))J(27,H(p,_,s))O(&#39;[&#39;,&#39;]&#39;)J(56,f(p){c=e;N=c;})J(2,m--p)J(10,N=a)J(4,f(q){N=L(g);X(S--]);})J(1,f(q){S+1]=T(g);++q;})J(53,m
e&gt;=0&amp;&amp;e&lt;a&amp;&amp;(d=T(A[u])))
J(54,q&gt;1&amp;&amp;(--q,U(S+1],i+q)))J(5,q&amp;&amp;p&gt;1&amp;&amp;(_-1]=open(g,_-1],e),--p,X(S--])))J(47,m
close(u))
J(26,m(e=dup(e)))O(&#39;&quot;&#39;,&#39;&quot;&#39;)J(51,H(q,S,i))J(49,N=fork())J(12,wait(&amp;N)+1||(e=-1))J(68,{++p;pipe(s+p++)==-1&amp;&amp;(e=-1);})F(&#39;q&#39;,v
0)
F(&#39;=&#39;,W{R x;f(m u)f(x=l){k+=n=L(x);V;Y(*x)K[--k]=*x++;k+=n;n=0;}b})J(15,f(q)W{l&amp;&amp;X(l);l=T(g);b})J(33,f(c=q){*i=g;g=0;Y(--q&amp;&amp;**(i+q))g++;f(q){N=execvp(*i,i+q+1);q=c;}})J(38,P
c&amp;&amp;(e/C))
J(35,Q=e&gt;G)F(&#39;+&#39;,Q+C)J(42,Q*C)J(41,Q=~(e&amp;G))J(57,m(e=-e))J(3,)F(&#39;\n&#39;,)putchar(c);puts(73+I);}}