--- dds.c
+++ dds.c
@@ -1,7 +1,7 @@
 #include &lt;stdio.h&gt;
 #define Q r=R[*p++-&#39;0&#39;];while(
 #define B ;break;case
-char*s=&quot;Qjou!s\\311^-g\\311^-n\\311^-c\\::^-q-ma%mO1JBHm%BQ-aP1J[O1HB%[Q&lt;nbj\
+char s[]=&quot;Qdibs!+hfut)*&lt;jou!s\\311^-g\\311^-n\\311^-c\\::^-q-ma%mO1JBHm%BQ-aP1J[O1HB%[Q&lt;nbj\
 o)*|gps)&lt;&lt;*txjudi)m*|aQdbtf!::::;sfuvso&lt;aQefgbvmu;aQ&lt;m,,a%CQ&lt;csfbla%bQ&lt;aN2!Q\
 \ndbtf!aP2Q;m&gt;aP2Q&lt;a%!D12J!JGJHJOJQJFJSJJJMHS%HD12D12N3!N4\nJUJT%UQm&gt;aP4HC%T\
 Qs\\q,,^&gt;m,2&lt;m&gt;aP4HC%SD12N1\nJNQm&gt;s\\..q^aHC%NHb%GN1!D32P3%RN1UP1D12JPQUaP1H\