--- westley.c
+++ westley.c
@@ -1,7 +1,7 @@
 		a(X){/*/X=-		a(X){/*/X=-
 		-1;F;X=-		-1;F;X=-
 		-1;F;}/*/		-1;F;}/*/
-char*z[]={&quot;char*z[]={&quot;,&quot;a(X){/*/X=-&quot;,&quot;-1;F;X=-&quot;,&quot;-1;F;}/*/&quot;,&quot;9999999999  :-| &quot;,
+char z[][99]={&quot;char z[][99]={&quot;,&quot;a(X){/*/X=-&quot;,&quot;-1;F;X=-&quot;,&quot;-1;F;}/*/&quot;,&quot;9999999999  :-| &quot;,
 &quot;int q,i,j,k,X,O=0,H;S(x)int*x;{X+=X;O+=O;*x+1?*x+2||X++:O++;*x=1;}L(n){for(*&quot;,
 &quot;z[i=1]=n+97;i&lt;4;i++)M(256),s(i),M(128),s(i),M(64),N;X*=8;O*=8;}s(R){char*r=z&quot;,
 &quot;[R];for(q&amp;&amp;Q;*r;)P(*r++);q&amp;&amp;(Q,P(44));}M(m){P(9);i-2||P(X&amp;m?88:O&amp;m?48:32);P(&quot;,