#define f 000:
          char
	  *s,*
	  t,v;
	  char 
	  _  [
	  999]
	  ,x [
	  999]
	  ,*p=
	  x  ;
	  char
	  *av[
	  ]= {
	  &quot;W&quot;,
	  &quot;H&quot;,
	  &quot;o&quot;,
	  &quot;l&quot;,
	  &quot;N&quot;,
	  &quot;e&quot;,
	  &quot; &quot;,
	  &quot;r&quot;,
	  &quot;d&quot;,
	  &quot;.&quot;,
	  &quot;m&quot;,
          &quot;s&quot;,
          &quot;g&quot;,
          &quot;!&quot;,
          &quot;*&quot;,
          &quot;\n&quot;
	  }  ;
	   int 
	  n= 0
	  ;int 
	  __ =
	  0,i=
	  000;
	  main
	  () {
#define f 001:
#define F 042:
#define f 100:
         _[i--
#define f 126:
#define f 132:
#define f 103:
#define f 202:
#define f 666:
#define f 77::
#define f 101:
	   ]=0
#define f 232:
#define f 151:
	  ;if(
#define f 256:
          !i){
          puts
          (&quot;I&quot;
          &quot;BM&quot;
          &quot; S&quot;
          &quot;UX&quot;
          );;;
          ;;;}
	  ;for
	  (  ;
	  gets
	  (_);
	  )  {
	  for(
#define f 301:
	  t=_,
#define f 700:
#define f 999:
	  s=t,
#define f 77 :
#define f 300:
	  s=t;
#define f s=t;
#define f 123:
#define f 127:
	  *t&amp;&amp;
	  !(!(
	  *t &lt;
	  &#39;0&#39;
	  ||*t
	  &gt;&#39;9&#39;
	  )&amp;&amp;!
          ((t[
          1] ^
          &#39;:&#39;)
          &amp;&amp;(t
          [1]^
          &#39;.&#39;)
	  )) ; 
	  t++)
#define f 137:
#define f 133:
	  ;if(
#define f 111:
#define f 220:
          v^*t
          &amp;&amp;*t
	  ){v=
          *t;;
          n=n*
	  2+(1
	  &amp;*t)
	  ;__=
	  (__+
	  1)&amp;3
	  ; __
	  ||((
	  n&lt;15
	  &amp;&amp;(*
	  p= *
	  av[n
	  ] ),
#define f 2+2:
	  p++)
	  ,n=0
	  );}}
#define f ==4:
	  ;*p=
	  &#39;\0&#39;
	  ;;;;
#define f puts
	  puts
	  (x);
	  s=t;
#define f s=5;
	  s=t;
#define f s=5:
	  s=t;
#define f 445:
#define f 113:
#define f 900:
	  s=t;
#define f n22:
#define f n40:
	  s=t;
#define f nn6:
	  s=t;
#define f nn1:
#define f 0:--
	  s=t;
#define f 19:-
#define f x2:x
	  s=t;
#define f x1:x
	  s=t;
#define f y2:x
#define f y7:y
	  s=t;
#define f 1:::
	  s=t;
#define f @3:@
#define f 10:0
#define f x+1:
	  s=t;
#define f 2:::
#define f 3:::
#define x 7:::
#define y 3:::
#define z 990:
#define Z 47::
	  ;;;}
