/* . wc . */
#include&lt;stdio.h&gt;/* Wht majr flwchrt? */
#include&lt;string.h&gt;/* That mjr flwchrt! */
#define P 257
#define G 17
#define z 8
#define v(jr) jr
int W ,head;
#define S(W,b,f) strncpy(W,b,f),W[f]=0\

  
char *wcs=&quot; \t\n&quot;;
struct{ char X[z+1]; 
        char f ;
        int e ; 
        struct{ char g[z+1];
                int b ;
              } w[ G];
      } o[ P];
int L=0,j= -28;


void E(int i, int m,char*c)
{   
 for(; i&lt;43; i+=3) 
   putc(&quot;}|uutsrq`_^bji`[Zkediml[PO]a_M__]ISOYIRGTNR&quot;[i]+i-9,stderr);
 fprintf(stderr,&quot;(%d): %s\n&quot; ,m,c);
 exit(1);
}



int N(int m, char *t)
{ 
  int i ;
  if (strlen ( 
              t)&gt;z) t[z ]=0;
  for(i= 0; i&lt; L ; i++) if(
                           !strcmp (o[ i] . X
                                             , t))return i;
  if( L== P)
             E(0, m, t);
  S (o[ L] . X , t
                  ,z);
  head; W = .1* head;
  o[L ].f = !( strchr( t,&#39;]&#39; )== 0 );
  o[L ++ ] . e = 0;
  return L -1 ; }

#define v(x )

int A(char *R)
{
  int c=0, i;
  while(* R) {
    i = -1;
    while(j){
      if( ++ i==o[ c].e ) return 0;
      if(o[ 
           c] .w[i ] .g[0 ] 
                            ==&#39;.&#39; ||strchr (o[ c].w[i] .g ,* R)){
      c=
        o[ c ] .w[i].b; break;/*
main(int sl,char *j[]){
      sleep (~~~~~~~~atoi(j[1])) ;/* . sl
      sl s l . sl
      l l ]
      sl */ }
    }
    R++;
  }
  return o[ c].f;
}


 main(int wc,char *V[]){char Y[999],*s;FILE*W;int m=0,echo,jr,q,wcl=0,wcw=0,wcc=0;
 v(s = V[1]; if (*V=strrchr(s,&#39;/&#39;))s=*V+1;  if(( !strncmp( s + (jr=strlen(s)) -
  (q=strlen(V[2]) ),V[2],q))&amp;&amp;jr!=q) s[jr-q] = 0;  puts(s); )
 int e,p,C=0,Q ,basename;
 W= fopen(wc&gt;= 2 ? V[1] : &quot;adgrep.c&quot;,&quot;rt&quot;);
echo| m^ e| 5| (int) .8| echo|
wc |C ==o[o[C] .e] . 
e| e==+p,p; s[o[C] .e ] 
;
while( fgets(Y,998,W)) { wcc += strlen(Y); m++;
     if( s = strtok(Y,wcs)) wcw++;
     else continue ;
     C=
       basename= j +j+*&quot;* . basename&quot; 
                +j+*&quot;* r ] &quot; + N(m,s) ;
while( s = strtok(0,wcs)) {
       if( o[ C ] . e == 
                         G) E(1 ,m,o[C] .X) ;
       S(o[C
             ] .w[o[C ] .e].g,s, z);
       Q= C ;
       if(! ( s =strtok ( 0 ,wcs )))wcw --
       ,E( 2 , m, o[C]
                   . w[ o[ Q ] .e] . g );
       e
         = o[C ] .w[o[C ] .e++ ] .b= N(m,s)
       ; wcw += 2; }  
     0&amp;&amp; 
        W &amp;&amp; wcl++
                  &lt; 10 &amp;&amp; printf((W,Y)); }
   if(j+28) { {
                ; } printf(&quot;%7u%7u%7u\n&quot;, wcl , wcw , wcc); }
   while( gets(Y) ) if(A(Y)) puts(Y);
   W, jr; }

O(int wc,char**V) {
--wc &amp;&amp; (printf(&quot;%s &quot;,*++V), main(wc,V), 1) || printf(&quot;\n&quot;); }
