--- marangon.c
+++ marangon.c
@@ -51,13 +51,13 @@
 void main()
 {
 char *ST();
-i a=0,b=0,c,q,t,s,x,sc=0;
+i a=0,b=0,c,q,t,s,s_tmp,x,sc=0;
 i(*(*p)())()=(nt(),d);
 I(x=0 ; x++&lt;20; )d(Z(0,5),Z(0,5),Z(1,2));
 I(t=Z(0,2),q=s=0; q&lt;3; s+=f[q][t]*f[q++][t]);
 I(box(r,&#39;|&#39;,&#39;-&#39;),ci(),wmove(r,X(a),Y(b)),
 W; (ST (&quot;+-Qlkjh&quot;,(char)(c=wgetch(r))))&amp;&amp;
-((i)((i)(q^=s%=Y(q),s/=2)!=(i)(s^=q)&amp;&amp;c&amp;64&amp;&amp;(!(c&amp;7|0)&amp;&amp;--b&lt;0&amp;&amp;
+(q^=s%=Y(q),s_tmp=s/=2,(i)((i)s_tmp!=(i)(s^=q)&amp;&amp;c&amp;64&amp;&amp;(!(c&amp;7|0)&amp;&amp;--b&lt;0&amp;&amp;
 (b=q^s)&amp;0|| c&amp;4&amp;&amp;++b==6&amp;&amp;c&amp;4&lt;(~b&amp;23?q^=s,b^=b
 :b&amp;12?b=3:b|2)||c&amp;2&amp;&amp;~c&amp;1&amp;&amp;++a==++q/2+1&amp;&amp;c&amp;16&gt;(
 !a|12?a=7,a&amp;=~a:a|4?a=2:a&amp;2)||~c&amp;4&amp;&amp;c&amp;