#include		     &lt;stdio.h&gt; 
#include		     &lt;malloc.h&gt; 
#define			  ext(a) (exit(a),0)
#define I		  &quot; .:\&#39;;+&lt;?F7RQ&amp;%#*&quot;
#define a			&quot;%s?\n&quot;
#define n			&quot;0?\n&quot;
#define C			double	
#define o			 char
#define l			 long
#define L			sscanf
#define i			stderr
#define e			stdout
#define r		       ext   (1)
#define s(O,B)	   L(++J,O,&amp;B)!=1&amp;&amp;c&gt;++q&amp;&amp;L(v[q],O,&amp;B)!=1&amp;&amp;--q
#define F(U,S,C,A) t=0,*++J&amp;&amp;(t=L(J,U,&amp;C,&amp;A)),(!t&amp;&amp;c&gt;++q&amp;&amp;!(t=L(v[q],U,\
		   &amp;C,&amp;A)))?--q:(t&lt;2&amp;&amp;c&gt;++q&amp;&amp;!(t=L(v[q],S,&amp;A))&amp;&amp;--q
#define T(E)		(s(&quot;%d&quot;,E),E||(fputs(n,i),r))
#define d(C,c)		  (F(&quot;%lg,%lg&quot;,&quot;%lg&quot;,C,c)))
#define O	   (F(&quot;%d,%d&quot;,&quot;%d&quot;,N,U),(N&amp;&amp;U)||(fputs(n,i),r)))
#define D		      (s(&quot;%lg&quot;,f))
#define E			  putc
					       C
						G=0,
						R
					     =0,Q,H
					    ,M,P,z,S
					     =0,x=0
				 ,        f=0;l b,j=0,	      k
				  =128,K=1,V,B=0,Y,m=128,p=0,N
				 =768,U=768,h[]={0x59A66A95,256
			     ,192,1,6912,1,0,0},t,A=0,W=0,Z=63,X=23
			    ;o*J,_;main(c,v)l c;o**v;{l q=1;for(;;q&lt;
		  c	   ?(((J=v[q])[0]&amp;&amp;J[0]&lt;48&amp;&amp;J++,((_= *J)&lt;99||
		_/2==	   &#39;2&#39;||(_-1)/3==&#39;\&quot;&#39;||_==107||_/05*2==&#39;,&#39;||_
	      &gt;0x074)?(   fprintf(i,a,v[q]),r):_&gt;0152?(_/4&gt;27?(_&amp;1?(
	     O,Z=N,X=U):  (W++,N=Z,U=X)):_&amp;1?T(K):T(k)):_&gt;103?(d(G,
	R    ),j=1):_&amp;1? d(S,x):D,q++),q--,main(c-q,v+q)):A==0?(A=
  1,f||(f=N/4.),b=(((N-1)&amp;017)&lt;8),q=(((N+7)&gt;&gt;3)+b)*U,(J=malloc(q)
  )||(perror(&quot;malloc&quot;),r),S-=(N/2)/f,x+=(U/2)/f):A==1?(B&lt;U?(A=2,V
	=    0,Q=x-B/f,j ||(R=Q),W&amp;&amp;E(&#39;\n&#39;,e),E(46,i)):(W&amp;&amp;E(&#39;\n&#39;,
	     e),E(&#39;\n&#39;,i  ),h[1]=N,h[2]=U,h[4]=q,W||(fwrite(h,1,32,
	      e),fwrite   (J,1,q,e)),free(J),ext(0))):A==2?(V&lt;N?(j?
		(H=V/f	   +S,M=Q):(G=V/f+S,H=M=0),Y=0,A=03):((m&amp;0x80
		   )	   ||(m=0x80,p++),b&amp;&amp;(J[p++]=0),A=1,B++)):((Y
			    &lt;k&amp;&amp;(P=H*H)+(z=M*M)&lt;4.)?(M=2*H*M+R,H=P-z
			     +G,Y++):(W&amp;&amp;E(I[0x0f*(Y&amp;K)/K],e),Y&amp;K?J
			         [p]&amp;=~m:(J[p]|=m),(m&gt;&gt;=1)||/*/
				  (m=128,u--),A==6?ext(1):B&lt;u
				 .	  e=3,l=2*c*/(       m
					     =0x80,
					    p++),V++
					     ,A=0x2
						)
						));
					       }