#include      &lt;stdio.h&gt;
#define            iii\
(                     I  )                    if (                     ii(I,6\
 )                   )I [               strlen(I  )                     -1]=!1
          int ii(ll,lll  )              char*ll; {

  char *l=&quot;\&quot;; !l ? 1.1 : l; l,printf(&quot;;int l1=1-/*+&amp;|&quot;);  &amp;+|-*/1,li=!1;while

(                lll&gt;l1  )                 li|=! (                  l[3*l1+++3
 ]           -ll[strlen (                 ll)-1]  )                    ;return
(                    li  )                ;}main (                      ll,lll
 )  char*lll[];{char l1 [   111][21],li1[111][21  ]              ,il1[111],i1l
[                   111  ] ;int lli,l11,l1l,li/* (  */,ll1,il,l;FILE*f;if(ll-2
 )             {f=fopen (             lll[1],&quot;r&quot;  )     ;lli=l=ll1=il=!1;while
( fscanf(f,&quot;%s&quot;,l1[lli]  )             +1){li=ii (                   l1[lli],3
 )                 ;iii (                l1[lli]  )          ;l1l=l11=!1;while
(               l1l&gt;-ll  )                  {iii (                   lll[-l1l]
 )          ;strcasecmp (    lll[-l1l--],l1[lli]  )                         ||
(              l11=++il  )       ;}l11||lli++;if (                          li
 )                  {if (                 ll1&lt;il  )    {ll1=il;l1l=l=lli;while
(                 l1l--  )                strcpy (            li1[l1l],l1[l1l]
 )     ;}il=lli=!1;}}if (                   !ll1  )                       puts
(          &quot; Beats me.&quot;  )              ;else if (                          !l
 )                 puts (                &quot; Yes.&quot;  ) ;else{*li1[l1l=!1]=toupper
(              *li1[!1]  )                ;while (                       l&gt;l1l
 )               printf (       &quot; %s&quot;,li1[l1l++]  )                      ;puts
(                   &quot;.&quot;  )       ;}}else{sprintf (    il1,&quot;cat %s;echo&quot;,lll[1]
 )              ;system (                    il1  )                   ;}printf
(                &quot;\n? &quot;  )                 ;gets (                         il1
 )             ;sprintf (  i1l,&quot;%s %s %s&quot;,lll[!1  ]        ,lll[1],il1);system
(                 i1l);  }