#if O
main(){}
#else
























#if rop&amp;onut&amp;((own&amp;rain)|warf)
#include &quot;						  										  The orc scrambles to the drain,					          trying to get the donut; you						          run out the door and escape!							  										  	       The End								  										  &quot;
#else
#if escribe
#if ocument
#include &quot;						  										  It reads:								              Depress Dotted Dog							  										  &quot;
#else
#if oor
#include &quot;						  										  The door is decorated with relief						  figures of various dog breeds						            										  &quot;
#else
#if rain
#include &quot;						  										  Through the drain you see a dwarf						  in another cell							            										  &quot;
#else
#if warf
#include &quot;						  										  The gnarled dwarf looks thirsty					            										  &quot;
#else
#if ungeon|ebris
#include &quot;						  										  You notice a desk, a phone, and					          a phone directory among the clutter						  										  &quot;
#else
#if esk
#include &quot;						  										  There are some dimes on the desk						  										  &quot;
#else
#if irectory
#include &quot;						  										  It reads:								              Pixie&#39;s Pub -								      instant service -								      Dial DUNgeon0614								  										  &quot;
#else
#include &quot;						  										  You notice nothing unusual							  										  &quot;
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#else
#if ial&amp;UNgeon0614
#include &quot;						  										  Pixie takes your order, and							  magically, the room is filled						          with banana daiquiris								  										  &quot;
#endif
#if rink&amp;aiquiri
#include &quot;						  										  As you drink, a voice from						          below says &#39;Could you drop						          one down here?&#39;								  										  &quot;
#endif
#if rop&amp;aiquiri
#if warf|own
#include &quot;						  										  The dwarf eagerly accepts						          the drink.  &#39;Thanks!  Here,						          I found this, but I can&#39;t							  understand it.&#39;  He hands							  you a document								  										  &quot;
#else
#include &quot;						  										  You drop the drink							          on the floor									  										  &quot;
#endif
#endif
#if epress&amp;(almatian|almation)
#include &quot;						  										  As you press the dalmatian						          figure, the door opens - only						          to reveal a menacing orc by							  a vending machine (with a							  sign reading &#39;DEPOSIT MONEY&#39;)							  										  &quot;
#endif
#if eposit&amp;(ime|imes)
#include &quot;						  										  Donuts spill out; you get						          some, the orc hungrily eats						          the rest									  										  &quot;
#endif
#if rop&amp;onut
#include &quot;						  										  The orc quickly eats the						          donut; he still bars the						          way										  										  &quot;
#endif
#if rop+epress+ime+eposit+rink+aiquiri+onut==1
#include &quot;						  										  Be more specific								  										  &quot;
#endif
#include &quot;						  										  You are in a debris-filled						          dungeon; a door bars the						          way, and sludge trickles into						          a floor drain									  										  &quot;
#endif
#endif
#endif