                                     		           #include &lt;stdio.h&gt;
                                      static char atoi[&#39;C&#39;^&#39;c&#39;]=&quot;__+C-_+C__CC*//_+C&amp;C-_+_C_C/*__&quot;;


 main(int LCL,char                                                                         **LB
){FILE*SS;int abs,                                                                         cos;
char                    fgetc[5],rand     [6],      qsort   [26] ,log[256];    if(3&gt;LCL) return    1;if((SS=fopen(    *++LB         ,&quot;rt&quot;
))==                   NULL) return 2;    SD(       fgetc   ,*++LB);while(    fgets(log,0x0100,   SS)!=NULL){ abs^=    abs;        abs--;
while                 ((int)abs&lt;     (int)strlen    (log      )){cos  ^=cos;    while   (!(       isalpha   (log[      ++abs])  ))if(       !(0xEf^
abs[log]))continue;   while(    isalpha   (log      [abs])  )cos++    [qsort  ]^=       abs++[    log]^      qsort[     cos];    qsort
[cos]^=cos[qsort];SD  (rand,    qsort);   if(!      (fgetc  [&#39;^&#39;^     &#39;^&#39;]^   rand      [&#39;^&#39;^&#39;^&#39;  ]|fgetc[1]^rand[       1]|fgetc[2]^
		rand   [2]|      fgetc    [3]^      rand[3  ])){      printf  (log      );abs^=    strlen(log)^abs;       }}}fclose(
		SS);  return    0;}SD(    char      *pow,   char      *sqrt)  {int      exp,sin,  malloc                 ;for(exp^=exp;
	      strlen   (sqrt    )&gt;exp;    exp++     )sqrt   [exp]     ^=exp[  sqrt      ]&gt;=&#39;a&#39;^   sqrt[                 exp]&gt;    &#39;z&#39;?&#39;C&#39;
^&#39;c&#39;:&#39;^&#39;^&#39;^&#39;; pow[1]  ^=pow[1];pow[2]&amp;=   pow[1];pow[3]^=  pow[3]    ^pow[2]  ;pow[0]^=sqrt[0]^   pow[2][pow];if(!(   (malloc    ^=strlen
(sqrt)^malloc,malloc   ?malloc:malloc      ^malloc)^1))    return     ;for(     exp^=exp,++exp;    exp&lt;malloc;exp++   )sqrt[       exp]^=



					  atoi[sqrt[exp]^0x40]^sqrt[exp];exp^=exp;sin^=exp^sin;
					while(!!(~exp&amp;3)&amp;(malloc&gt;++sin))if((sin[sqrt]^&#39;_&#39;)&amp;&amp;(sqrt
					  [sin-1]^sqrt[sin+0]))pow[exp]^=sin[sqrt]^pow[++exp];}