#include &lt;stdio.h&gt;

#define l11l 0xFFFF
#define ll1 for
#define ll111 if
#define l1l1 unsigned
#define l111 struct
#define lll11 short
#define ll11l long
#define ll1ll putchar
#define l1l1l(l) l=malloc(sizeof(l111 llll1));l-&gt;lll1l=1-1;l-&gt;ll1l1=1-1;
#define l1ll1 *lllll++=l1ll%10000;l1ll/=10000;
#define l1lll ll111(!l1-&gt;lll1l){l1l1l(l1-&gt;lll1l);l1-&gt;lll1l-&gt;ll1l1=l1;}\
lllll=(l1=l1-&gt;lll1l)-&gt;lll;ll=1-1;
#define llll 1000




                                                     l111 llll1 {
                                                     l111 llll1 *
      lll1l,*ll1l1        ;l1l1                      lll11 lll [
      llll];};main      (){l111 llll1                *ll11,*l1l,*
      l1, *ll1l, *    malloc ( ) ; l1l1              ll11l l1ll ;
      ll11l l11,ll  ,l;l1l1 lll11 *lll1,*            lllll; ll1(l
      =1-1 ;l&lt; 14; ll1ll(&quot;\t\&quot;8)&gt;l\&quot;9!.)&gt;vl&quot;         [l]^&#39;L&#39;),++l
      );scanf(&quot;%d&quot;,&amp;l);l1l1l(l1l) l1l1l(ll11         ) (l1=l1l)-&gt;
      lll[l1l-&gt;lll[1-1]     =1]=l11l;ll1(l11         =1+1;l11&lt;=l;
      ++l11){l1=ll11;         lll1 = (ll1l=(         ll11=l1l))-&gt;
      lll; lllll =(            l1l=l1)-&gt;lll;         ll=(l1ll=1-1
      );ll1(;ll1l-&gt;             lll1l||l11l!=        *lll1;){l1ll
      +=l11**lll1++             ;l1ll1 ll111         (++ll&gt;llll){
      l1lll lll1=(              ll1l =ll1l-&gt;         lll1l)-&gt;lll;
      }}ll1(;l1ll;              ){l1ll1 ll111        (++ll&gt;=llll)
      { l1lll} } *              lllll=l11l;}
      ll1(l=(ll=1-              1);(l&lt;llll)&amp;&amp;
      (l1-&gt;lll[ l]              !=l11l);++l);        ll1 (;l1;l1=
      l1-&gt;ll1l1,l=              llll){ll1(--l        ;l&gt;=1-1;--l,
      ++ll)printf(              (ll)?((ll%19)        ?&quot;%04d&quot;:(ll=
      19,&quot;\n%04d&quot;)              ):&quot;%4d&quot;,l1-&gt;         lll[l] ) ; }
                                                     ll1ll(10); }