#define fine #define de #define/**/ /**/*#define*/
#define de #define
#define do de

do { begin
do you like (green eggs and ham++)?
do you eat them: in a box?
do you eat them with a fox?0
do } end

fine
fine, just fine.

                    /*@@@@@@@@@@@@=___
                   /@@@@@@@@@@@@@@@@@@@a
                   @@@@@@@@@@@@@@@@@@@@@
                   |@@@@@@@@@@@@@@@@@@@@
                    @@@@@@@@@@@@@@@@@@@@
                     \@=~         ~~@@@/
                      \               /
                       \              |
                       /@@@@@===__    |
                       @@@@@@@@@@@@==/
                      /@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@@@
                     / ~~~====@@@@@@
                    /           ~~~/
                   |              /
                  /____          |
                 @@@@@@@@=====__/
                @@@@@@@@@@@@@@@@
               /@@@@@@@@@@@@@@@
              /@@@@@@@@@@@@@@@|
          ___/        ~~~~@@*/
   char groo(p,q)int p;int q;{return
((char)          (--q*q+   (p/10)*q+--p))
       ;          }void grem /**/  (){ int x=0
     ;             printf(&quot;   &quot;)
     ;/**/   /**/    for(;x&lt;16
    ;                x++)printf
   (                 &quot;%c&quot;,groo(x
   ,    8))            ;printf
   (                   &quot;\n\n&quot;)
  ;                  }void cred(a
 )                   int a;{int
                    x=0;printf
 (                  &quot;%c  &quot;
 , /*_____===~*/  groo(a,8))
  ;             for(;x&lt;16
   ;           x++)printf
    (         &quot;%c&quot;,(char)
      a*16+ x);printf(
       &quot;\n&quot;);}main(a
          ,b)int a;
 char **b   ;{int        x=2;
    do(x=0;x&lt;4;x++)exit(0);
  for(grem();x&lt;1&lt;&lt;3+(int)b[0]
[0]%2;)cred            (++x-1);}
