#ifndef int
#ifdef while
char s[234],d[56],*p=s,m=&#39;m&#39;;
#define int typedef (*define)();\
 define O [6]={getc,putchar,(y)memmove,(y)printf,(y)n,(y)l};
#include __FILE__
signed short n(short bz){
	short pb=0,Md=1,ih=2,sfp=3,sjs=4,fo,u=5,scp=6,t,gq=7,oh,r=8,pcf=9,rs=10;
	char o=1,i=1,l,pc=i,b=r+o/2,_f=6,m=7,s=8,g,q,od=o*rs+4^s,js=_f/*3-m*&#39;c&#39;,bs=&#39;g&#39;;
return 1; }
#y	FILE c[a]+s,p[c],r[m]+u[i+4*o|f]-r[wob][wad]+s*f-!w|o,L+x					|  cut 
;}int main(i,love_unix){*/;}int main(i,love_unix){/*;}int main(i,love_unix){*\;}|  here */
while(FILE)for(;9-(i=0[O](f)););
for(;32-(i=0[O](f));0&amp;&amp;	3[O](&quot;--&gt;%s&lt;--&quot;, &quot;gxdgbtgxsxpcctvpixktedhiedcte&quot;)); 
for(;&#39;\n&#39;-(i=O[0](f));)(i&gt;=&#39;a&#39;&amp;&amp;i&lt;&#39;z&#39;)?*
#include __FILE__
                                  &quot;Demonic Smiley&quot; );}		/* &lt;g&gt; */
#else
#define while(int) short c=0;int*f=fopen(__##int##__,&quot;r&quot;);for(i=0;i&lt;25;i _)i[d]=&#39;A&#39;+(13+i)%26;main:
#define y define
#define _ ++
#include &lt;stdio.h&gt;
#include &lt;string.h&gt;
#include &lt;time.h&gt;
#include __FILE__
#endif
#elif defined(signed)
(p _)=(i-&#39;a&#39;)[d]:!(i-&#39;z&#39;)?*(p _)=32:(i&gt;=&#39;A&#39;&amp;&amp;i&lt;=&#39;Z&#39;)&amp;&amp;((3&amp;8|2)[O](d+1,d,24L),*(p _)=0[d]=i);/*
#y	FILE t,ra|js+t*gj,at[qdd]-=K,is _,qv _,veb _,ti _,ao[mqht] _*/
if(c _&lt;6) goto main; 5[O](
#else
#define signed short l(){char q=&#39;_&#39;;p=s+4*(time(NULL)%24)*2,m=(char)p+1;\
*(p+8)=0; for(d[3]=10,d[33]=3[d]-10;d[3]&lt;18;3[d] _) d[3][p]=q;3[d][p]=0;\
hell:  printf(&quot;\t[%s]\n&quot;,p+10);if(!m) goto stoned;\
froze: d[8]=(scanf(&quot;%c&quot;,&amp;(2[d+__STDC__])),2[d+!NULL])&amp;223;if(!(3[d+5]-&#39;\n&#39;)) goto froze;\
for(m=1[d]=0;d[1]&lt;8;2[d-1] _) (p[d[1]]-d[8]||(p[3[d-2]+10]=4[d+4]))+(p[d[1]+10]-q||m _);\
goto hell;stoned:;}
FILE *X(FILE s){	char i,iev,jmqhu,xqht,mqh,ujek,sxydw,kdj,yjb,utou,qhre,eamy,jxxe,bt;}
#endif