#include &lt;stdio.h&gt;

char
*T=&quot;IeJKLMaYQCE]jbZRskc[SldU^V\\X\\|/_&lt;[&lt;:90!\&quot;$434-./2&gt;]s&quot;,
K[3][1000],*F,x,A,*M[2],*J,r[4],*g,N,Y,*Q,W,*k,q,D;X(){r  [r
[r[3]=M[1-(x&amp;1)][*r=W,1],2]=*Q+2,1]=x+1+Y,*g++=((((x&amp;     7)
-1)&gt;&gt;1)-1)?*r:r[x&gt;&gt;3],(++x&lt;*r)&amp;&amp;X();}E(){A||X(x=0,g       =J
),x=7&amp;(*T&gt;&gt;A*3),J[(x[F]-W-x)^A*7]=Q[x&amp;3]^A*(*M)[2         +(
x&amp;1)],g=J+((x[k]-W)^A*7)-A,g[1]=(*M)[*g=M[T+=A            ,1
][x&amp;1],x&amp;1],(A^=1)&amp;&amp;(E(),J+=W);}l(){E(--q&amp;&amp;l              ()
);}B(){*J&amp;&amp;B((D=*J,Q[2]&lt;D&amp;&amp;D&lt;k[1]&amp;&amp;(*g++=1                ),
!(D-W&amp;&amp;D-9&amp;&amp;D-10&amp;&amp;D-13)&amp;&amp;(!*r&amp;&amp;(*g++=0)                   ,*
r=1)||64&lt;D&amp;&amp;D&lt;91&amp;&amp;(*r=0,*g++=D-63)||D                     &gt;=
97&amp;&amp;D&lt;123&amp;&amp;(*r=0,*g++=D-95)||!(D-k[                       3]
)&amp;&amp;(*r=0,*g++=12)||D&gt;k[3]&amp;&amp;D&lt;=k[                          1]
-1&amp;&amp;(*r=0,*g++=D-47),J++));}j(                            ){
putchar(A);}b(){(j(A=(*K)[D*                              W+
r[2]*Y+x]),++x&lt;Y)&amp;&amp;b();}t                                 ()
{(j((b(D=q[g],x=0),A=W)                                   ),
++q&lt;(*(r+1)&lt;Y?*(r+1):                                     Y)
)&amp;&amp;t();}R(){(A=(t(                                        q=
0),&#39;\n&#39;),j(),++r                                          [2
]&lt;N)&amp;&amp;R();}O()                                            {(
j((r[2]=0,R(                                              ))
),r[1]-=q)                                                &amp;&amp;
O(g-=-q)                                                  ;}
C(){(                                                     J=
gets                                                      (K
[1]))&amp;&amp;C((B(g=K[2]),*r=!(!*r&amp;&amp;(*g++=0)),(*r)[r]=g-K[2],g=K[2
],r[
1]&amp;&amp;
O())
);;}
main
(){C
((l(
(J=(
A=0)
[K],
A[M]
=(F=
(k=(
M[!A
]=(Q
=T+(
q=(Y
=(W=
32)-
(N=4
))))
+N)+
2)+7
)+7)
),Y=
N&lt;&lt;(
*r=!
-A))
);;}