main(i)??&lt;char c??(81??)??(81??);for(i=0;gets(*(c+i)); i++);A(i,c);J(i-1,c);??&gt;
                          /* {   /KC 0000 K  } */
S(c,r,i)char*c; ??&lt;printf(&quot;|&quot;);for(;*(c+i); i++)putchar(T(*(c+i),r));U(c,i);??&gt;

          char* B,*r; X(c,k)??&lt;return isupper(c)?0:V(*(r+k),B); ??&gt;
J(i,c,j)char*c; ??&lt;for(j=t(i,0)            ; j+j&lt;i; j++)L(c,j,i-j); M(i,c); ??&gt;
          U(c,i)char*c; ??&lt;while(i++&lt;80)printf(&quot; &quot;); puts(&quot;|&quot;); ??&gt;

A(i ,c,j ,k) char *c; ??&lt; for(j= -1; ++j&lt;i; )for (k =j; k&lt;i; )D(c ,j, k++); ??&gt;
R(c,r) char *c; ??&lt; printf( &quot;/%-80s|??/n&quot; ,c); for (; r&lt; 13; r++)S (c,r,0); ??&gt;
 t(a,b)??&lt;return a;??&gt;

M(i,c)char c??(81??)??(81??);??&lt;i++;while(i--)t(1,0)?puts(*(c+i)):P(*(c+i));??&gt;
 char*d= &quot;yyzzyzz zz z0y000 zz 00yzz00y00yzz Brian Westley zyy00yy0yy 0&quot; ; ; ;
#define t(a,b) t(b,a)

char* K;Y (c ,r) ??&lt; int i=V ( tolower (c) ,K); return(i &lt;0)?1 :Z(c ,r, i); ??&gt;
char*m= &quot;7831734578 9547693564569528334164263z284106579 52626423135477&quot;; ; ; ;
P(c)char*c;                  ??&lt;Q(1,0); R(c,1                    ); Q(0,0); ??&gt;

char* d,*m,*B; Z(c,i,k)??&lt;return W(i, V(*(d+k), B),V(*( m+k),B) ,X(c, k)); ??&gt;
char*K= &quot;gh$j|lm&#39;pq&amp;rv&lt;x&gt;z#);@_winky,.%/+*!=3-284106579 (:obfuscated??/?&quot; ; ;
         L(c,i,j)char c??(81??)??(81??);??&lt;G(*                (c+i),*(c+j));??&gt;
  char*r=     &quot;008y8yy8yyyyz8z8z88888z0yyz888 8888            88y00zz00z0088&quot;;
D(c,i,j)                        char c??(81??)??(81??);??&lt;E(*(c+i),*(c+j));??&gt;

 E(r,s)char*r,*s; ??&lt; if(t(                         0,1)&amp;&amp; F(r,s)&lt;0)G(r,s); ??&gt;
H()??&lt;static i=0; if (!i) ??&lt; time(&amp;i); srand(i); ??&gt; return rand()-rand(); ??&gt;
F(r,s)char*r,*s; ??&lt;return                          t(0,1)?H():strcmp(r,s); ??&gt;

                                      T(c,r) ??&lt; return Y(c, r)?&#39;??(&#39; :&#39; &#39;; ??&gt;
G(r,s)char*r,*s; ??&lt;char t??( 81??); strcpy(t,r); strcpy(r,s); strcpy(s,t); ??&gt;
                                      W(r,a,b,c)??&lt;return r==a||r==b||r==c; ??&gt;

Q(t,i)??&lt; printf(t?&quot; &quot;:&quot;|&quot;); for(; i&lt;80; i++) printf(&quot;_&quot;); puts(t?&quot;_&quot;:&quot;|&quot;); ??&gt;
                          char*B=&quot; yz0123456789&quot;;
V(c,k,i) char*k; ??&lt;for (i=0; *(k+i) &amp;&amp;*(k+i)!=c; i++); return *(k+i)?i:-1; ??&gt;