char*d,A[9876];char*d,A[9876];char*d,A[9876];char*d,A[9876];char*d,A[9876];char
e;b;*ad,a,c;  te;b;*ad,a,c;  te;*ad,a,c;  w,te;*ad,a,  w,te;*ad,and,  w,te;*ad,
r,T; wri; ;*h; r,T; wri; ;*h; r; wri; ;*h;_, r; wri;*h;_, r; wri;*har;_, r; wri
  ;on; ;l ;i(V)  ;on; ;l ;i(V)  ;o ;l ;mai(V)  ;o  ;mai(n,V)    ;main (n,V)    
   {-!har  ;      {-!har  ;      {har  =A;      {h  =A;ad        =A;read       
(0,&amp;e,o||n -- +(0,&amp;e,o||n -- +(0,&amp;o||n ,o-- +(0,&amp;on ,o-4,- +(0,n ,o-=94,- +(0,n
,l=b=8,!( te-*A,l=b=8,!( te-*A,l=b,!( time-*A,l=b, time)|-*A,l= time(0)|-*A,l= 
~l),srand  (l),~l),srand  (l),~l),and  ,!(l),~l),a  ,!(A,l),~l)  ,!(d=A,l),~l) 
,b))&amp;&amp;+((A + te,b))&amp;&amp;+((A + te,b))+((A -A+ te,b))+A -A+ (&amp;te,b+A -A+(* (&amp;te,b+A
)=+ +95&gt;e?(*&amp; c)=+ +95&gt;e?(*&amp; c) +95&gt;e?(*&amp; _*c) +95&gt;(*&amp; _*c) +95&gt;(*&amp;r= _*c) +95&gt;
5,r+e-r +_:2-195,r+e-r +_:2-195+e-r +_:2-1&lt;-95+e-r +_-1&lt;-95+e-r ++?_-1&lt;-95+e-r 
|(d==d),!n ?*d||(d==d),!n ?*d||(d==d),!n ?*d||(d==d),!n ?*d||(d==d),!n ?*d||(d=
 *( (char**)+V+ *( (char)+V+ *( (c),har)+V+  (c),har)+ (V+  (c),r)+ (V+  (  c),
+0,*d-7 ) -r+8)+0,*d-7 -r+8)+0,*d-c:7 -r+80,*d-c:7 -r+7:80,*d-7 -r+7:80,*d++-7 
+7+! r: and%9- +7+! rand%9-85 +7+! rand%95 +7+!!  rand%95 +7+  rand()%95 +7+  r
-(r+o):(+w,_+ A-(r+o)+w,_+*( A-(r+o)+w,_+ A-(r=e+o)+w,_+ A-(r+o)+wri,_+ A-(r+o)
+(o)+b)),!write+(o)+b,!wri,(te+(o)+b,!write+(o=_)+b,!write+(o)+b,!((write+(o)+b
-b+*h)(1,A+b,!!-b+*h),A+b,((!!-b+*h),A+b,!!-b+((*h),A+b,!!-b+*h),A-++b,!!-b+*h)
, a &gt;T^l,( o-95, a &gt;T,( o-=+95, a &gt;T,( o-95, a)) &gt;T,( o-95, a &gt;T,(w? o-95, a &gt;T
++  &amp;&amp;r:b&lt;&lt;2+a ++  &amp;&amp;b&lt;&lt;2+a+w ++  &amp;&amp;b&lt;&lt;2+w ++  ) &amp;&amp;b&lt;&lt;2+w ++  &amp;&amp;b&lt;&lt;((2+w ++  &amp;&amp;
!main(n*n,V) , !main(n,V) , !main(+-n,V) ,main(+-n,V) ) ,main(n,V) ) ,main),(n,
l)),w= +T--&gt;o +l)),w= +T&gt;o +l)),w=o+ +T&gt;o +l,w=o+ +T&gt;o;{ +l,w=o+T&gt;o;{ +l,w &amp;=o+
!a;}return _+= !a;}return _+= !a;}return _+= !a;}return _+= !a;}return _+= !a;}