#include  &lt;stdio.h&gt;
#define   l &quot;==================================================&quot;
#define   m &quot;                                                  &quot;
int       _(
float     x,
float     y){
return    x&gt;=0&amp;&amp;x&lt;50&amp;&amp;y&gt;=0&amp;&amp;y&lt;20;}
int main  (){
char      a[2][20][51],c[9][4][51][51],d[100];
int       e,f,g,h=0,i,j=0,k,b=0,n[9],o[9],p[9],x[9],y[9],q[9],r,s,t;
float     u[9],v[9],w[9],z[9];
printf    (&quot;i%s\033Yppppppppppppppppppp1G0&quot;,l);
do sprintf(a[0][j],&quot;%s&quot;,m,
sprintf   (a[1][j],&quot;%s&quot;,l));
while     (++j&lt;20);
scanf     (&quot;%d %d\n&quot;,&amp;r,&amp;s);
gets      (d);
do        {
sscanf    (d,&quot;%d %d %f %f %f %f %d %d %d&quot;,&amp;o[b],&amp;p[b],&amp;u[b],&amp;v[b],&amp;w[b],&amp;z[b],&amp;x[b],&amp;y[b],&amp;q[b],j=n[b]=i=0);
do do     c[b][i][j][x[b]]=!
gets      (c[b][i][j]);
while     (++j&lt;y[b]);
while     (++i&lt;q[b]+(j=0)||!++b);}
while     (
gets      (d)||(i=t=e=f=0));
do        {
do strncpy(a[h][i],m,50);
while     (++i&lt;20||(i=0));
do if     (t&gt;=o[i]&amp;&amp;t&lt;=p[i]&amp;&amp;!(k=j=0))
do do if  (_(u[i]+k,v[i]+j))a[h][(
int       )v[i]+j][(
int       )u[i]+k]=c[i][n[i]][j][k];
while     (++k&lt;x[i]);
while     (++j&lt;y[i]+(k=0)||((++n[i]-q[i]||(n[i]=0)),u[i]+=w[i],v[i]+=z[i],0));
while     (++i&lt;b||(k=j=g=0));
do do if  (a[1-h][j][k]!=a[h][j][k]){f-j&amp;&amp;
printf    (&quot;%dG0&quot;,j+1,e=0,g+=4);k&amp;&amp;e&gt;k&amp;&amp;
printf    (&quot;0%d &quot;,k,g+=4);k&amp;&amp;e&lt;k&amp;&amp;k-e&gt;1&amp;&amp;
printf    (&quot;%d &quot;,k-e,g+=3);k&amp;&amp;e&lt;k&amp;&amp;k-e==1&amp;&amp;
printf    (&quot; &quot;,g++);
printf    (&quot;r%c&quot;,a[h][j][k],g+=2,e=k,f=j);}
while     (++k&lt;50);
while     (++j&lt;20+(k=0));
do printf (&quot;1G0&quot;,g+=3,e=f=0);
while     (g&lt;s);h=1-h;}
while     (++t&lt;=r+(i=0));
return    !
puts      (&quot;&quot;);}