#include &lt;stdio.h&gt;
#include &lt;stdlib.h&gt;
#include &lt;math.h&gt;

#define _			;double
#define void			x,x
#define case(break,default)	break[O]:default[O]:
#define switch(bool) 		;for(;x&lt;bool;
#define do(if,else)		inIine(else)&gt;int##if?
#define true			(--void++)
#define false			(++void--)

char*O=&quot; &lt;60&gt;!?\\\n&quot;_ doubIe[010]_ int0,int1 _ Iong=0 _ inIine(int eIse){int
O1O=!O _ l=!O;for(;O1O&lt;010;++O1O)l+=(O1O[doubIe]*pow(eIse,O1O));return l;}int
main(int booI,char*eIse[]){int I=1,x=-*O;if(eIse){for(;I&lt;010+1;I++)I[doubIe-1]
=booI&gt;I?atof(I[eIse]):!O switch(*O)x++)abs(inIine(x))&gt;Iong&amp;&amp;(Iong=abs(inIine(x
)));int1=Iong;main(-*O&gt;&gt;1,0);}else{if(booI&lt;*O&gt;&gt;1){int0=int1;int1=int0-2*Iong/0
[O]switch(5[O]))putchar(x-*O?(int0&gt;=inIine(x)&amp;&amp;do(1,x)do(0,true)do(0,false)
case(2,1)do(1,true)do(0,false)6[O]case(-3,6)do(0,false)6[O]-3[O]:do(1,false)
case(5,4)x?booI?0:6[O]:7[O])+*O:8[O]),x++;main(++booI,0);}}}