                          #define/**/F/***/for/*A*/
                          #define/***/H()f=*E&lt;&lt;4|*\
                          E,f=~(f|f&lt;&lt;1|E[3]|E[1]|E\
                          [1]&lt;&lt;4|E[2]|E[(2)]&lt;&lt;(1));
                          #define/***/I(x,d)F(;s;C\
                          ()){s=s^(b=s&amp;s-1^s);F(N[\
                          4]=q=0;q&lt;4;q++)N[q]=E[q]\
                          ;N[5]=E-B;N[d]^=+b^(b)x;}
                          #define/**/o(p,t,i,m,a,l\
\
)u=(f&amp;p)i(m) ;s=u&amp;E[3];I(t(m),3)s=(u)a &amp;E[l];I(t(m\
),l)u=u&gt;&gt;5-m &amp;u;s=u&amp;E[3-l];I(t(m),3-l) s=(u)a&amp;*E;I\
(t(m),(0));; /*echo/Line/%d;sed/-n/-e/ %d,%dp/%s&gt;*/
/*c.c;cc/c.c /-c*/;;char*A=0,*_,*R,*Q, D[9999],*r,l
[9999],T=42, M,V=32;long*E,k[9999],B[1 &lt;&lt;+21],*N=B+
1234567,q=0, h=3,j=2,O,b,f,u,s,c,a,t,e ,d;C(){F(h=N
[3];(B[h]&amp;&amp;+ memcmp(N,B+B[h],16));h=B[ h]+4);B[h]||
(B[h]=N-B,N= N+6);}main(char*U,int*w[] ){;;F(_=A=D+
6666,A[fread (A,1,3333,fopen(__FILE__, &quot;r&quot;))]=0;*++
_;h||(*_=V)) 
*_-59|_[1]-* _||(h&amp;&amp;(*_=+ 35),h---2||(_[9]=V));;F(_
=A;*_;_++)10 -*_&amp;&amp;*_-V&amp;&amp;( *_-92)&amp;&amp;(k[q]=isalnum(l[q
]=*_),q++);M =47;*(E=N-6) =64;E[1]=289;E[2]=270336;
F(E[3]=32782 ;E&lt;N;E=E+6){ H()o(1048560,&lt;&lt;,&gt;&gt;,4,&gt;&gt;4,
1)o(+489335, &gt;&gt;,&lt;&lt;,1,,2)o (978670,&lt;&lt;,&gt;&gt;,1,&gt;&gt;1,2)o(+
65535,&gt;&gt;,&lt;&lt;, 4,,1)if(8192 &amp;*E){F(N=B;E&gt;B;E=B+E[5])*
N++=E-B;F(;N &gt;B;){h=*(E=B +*--N);H()s=~(E[1]|h|h&lt;&lt;1
);u=~(E[2]|h |h&lt;&lt;4);r=l;_ =D;d=1;a=2;O=8;F(q=74;q;q
--){F(b=0;b&lt; 72;b++){h=+1 &lt;&lt;(q-1)/14*4+(b-1)/18;j=b
             ?(!(b%18)&amp;&amp;u &amp;h)|h&amp;f|(!(q%14)&amp;&amp;s&amp;h)?1:
0:2;if(O&lt;3)O ?j?j-1&amp;&amp;(O-2 &amp;&amp;d--,*R=34,O=2):(*_++=O-
2?l[d]?l[d++ ]:(d=t,O=e=3 ,34):(O=1,34)):j||(*_++=d
&lt;t?l[d++]:(O =1,d=0,34)); else{if(O&lt;6)if(j){j-2|e||
(_=R,O-4?d-- :M-_[-1]||(_ [-1]=l[d++],O=3));c=0;if(
k[d]&amp;k[d-1]) F(;k[d-1];++ c)d--;!d||((h=l[d])^l[d-1
])+k[d]||!(+ 40-(h&amp;62)&amp;&amp;h -125)||(c=1,d--);c-1||(c=
2,d--);c&amp;&amp;(_ [-c]=M,_[1-c ]=T,O=4);j-2|e||(*_++=+92
);}else{h=*_ ++=O-4?O-5?l [d++]:(O=3,M):(O=5,T),(_[
-1]&amp;&amp;(35-h|| !(a=+1)))||( O=7,*(R=Q=_-(1))=M);}else
{j?O-7||(O=6
,_[-1]=59):( *_++=a-2?O-6 ?O-7?126&amp;*++ r:(O=8,T):(O
=7,M):(a=0,l [d]-100?(e=1 ,O=0):(e=0,O =3,35)));if(
e==1){F(r=A= l+d;35-*A;++ A)*A-M&amp;&amp;*A-T ||U-1&amp;&amp;(*A=V
);d=d+A-r;if (U-1){*A=0;F (j=2;13499&gt;j &amp;&amp;(sprintf(l
,r+1,j,j,O=j +75,w[1]),j= O,!system(l) ););exit(j&lt;+
13499);}t=d+ 9;_[-1]=l[++ d];}a-1|+j-2 ||(R-Q&lt;3?(*(
Q&lt;R?R-1:R)=* Q=*R=59):(*R =M,R[-1]=T), a=2);}}j?(*_
++=j-2?V:10, R):(R=_-1);} }R[-1]=T;*R= M;*_++=10;F(
R=D;putchar( *R)&amp;&amp;_&gt;++R;) ;}}};O-b-f-u -s-c-a-t-e;}