#include &lt;X11/Xlib.h&gt;
char *l=&quot;dbcefcbddabcddcba~WAB+  +BAW~              +-84HLSU?A6J57IKJT576,&quot;,
*F=&quot;          ,&gt;&gt;,&gt;  xl~w/?  ,&gt;&gt;&gt;,s  m\177&gt;&gt;\177\177  mm2&gt;&gt;&gt;  &gt;uk&gt;&gt;&gt; &quot;,*f;y,u;
#define v for (i=0,b=0;b&gt;511?b=0,i+=64:0,i&lt;512;b+=64) A=i/64*10+b/64+21,XCopy\
Plane(d, r[I[A]+7+14*(i+b&gt;&gt;6&amp;1)+28*(A==z)],w,C,0,0,64,64,b,i,1); XFlush(d);
#define _(a) *f++=a&amp;*F?-(z%14&lt;7):&quot;U\252U\0DDDD&quot;[z/14*2|u&amp;1],
#define G(p) p##Pixel(d,DefaultScreen(d))
#define R(a) |(a==O|p==a)*
#define P return y=~y,
#define a X(0,0,0,
#define H while(
#define D ;if(

I[304],b,i,z;main(x,W)                   char**W; { Display *d =
 XOpenDisplay(&quot;&quot;); Window               w = XCreateSimpleWindow
  (d, DefaultRootWindow(d),            64,64,512,512,2,G(Black)
   ,G(Black)); XGCValues g;           XButtonEvent e; int A,r
    [56],Z,* m = I , C ,Y;           XSelectInput(d,w,32772);
     XMapWindow( d, w); g.          foreground = G(White);
      C=XCreateGC(d,w,4,&amp;g);       F+=48; H f=I,i=0,z&lt;56){
       H u=0,i++&lt;8){ H _(0)_(     64)_(16)_(8)_(4)_(2)_(1
       )_(0)++u&lt;8); F++; } F-=   z%7-6?z%14&lt;6?16:0:8; r[
        z++]=XCreateBitmapFromData(d,w,I,64,64); } srand(
       time(z=u=0)); H I[z]=-(   z&gt;98|z&lt;21|(z+1)%10&lt;2),
      ++z&lt;120); H ++m&lt;9+I) 80     [m]=-2,90[m]=~(20[m]=7&amp;*
     l++),30[m]=1; D 1&lt;x) Z=       *W[1]-45; D 2&lt;x){ a u,1
   ,Z); a u,0,1); z=0; } H          1){ XNextEvent(d,&amp;e); D
  e.type==12){ v } D e.              type==4){ b=e.y/64*10+e
.x/64+21; D(b[I]^y)&lt;-1)               { z=b; v} else{ i=(b&lt;29
|b&gt;90)&amp;((z[I]^y)==-2)?-                6^y:z[I]; Y=y; a u,0,1);
z=0; v D 1&lt;x&amp;&amp;Y-y){ a u                ,1,Z); a u,0,1); } z=0;
        v } } } }


                             X(w,c,h,e,S,s)


{ int p,O=          *l,t,d,o,C          ,*g,E,n,*m          =I,N=-1e8,
          A,L,r,x =           10,q; y=~y          ; H--O&gt;20)
{ o=I[p=O]          D q=o^y,q&gt;          0){ q+=(q&lt;          2)*y,C=q
         [&quot;51#/+++&quot;],       A=q[&quot;95+3/33&quot;];       do { m=0,
r=I[p+=C[l          ]-64] D !w          |p==w&amp;&amp;q&gt;1          |C+2&lt;A|!r)
          { d=abs(O-          p) D g=q&lt;2          &amp;e&gt;&gt;6==p+(
y?x:-x)?I+          (e&gt;&gt;6):0,           !r&amp;(q&gt;1|d%          x&lt;1||g)|(r
          ^y)&lt;-1){ n          =o,t=q&lt;2&amp;(          89&lt;p|30&gt;p)
?n+=y|1,6^          y:o+(y|1)           D (r^y)&lt;-6          ) P 1e7-811
          *h; H n-t)          { O[I]=0,p          [I]=n,m?*g
=*m,*m=0:g          ?*g=0:0;            E=e&amp;63 R(           91)16 R(28)
          4 R(21)2 R          (98)32; L=          (q&gt;1?6-q?l
[p/x-1]-l[          O/x-1]-q+2          :(E|=y?8:1          ,!!m)*9:(E
          |=20-d?0:           64*p,n-o?(          l[15+n]-&#39; &#39;
)*9:d/8+!!          g*99))+(l[          r+15]-&#39; &#39;)          *9+l[p%x]-
          h-l[O%x];           L-=s&gt;h||s==         h&amp;L&gt;49&amp;1&lt;s
?X(s&gt;h?0:p          ,L,h+1,E,N          ,s):0 D !(          z-O|i-n|h|
          p-b|S|L&lt;-           1e6))return         u=E; O[I]=
o,p[I]=r,m          ?*m=*g,*g=          0:g?*g=-2^          y:0 D S|h&amp;&amp;
          (L&gt;N||!h&amp;N          ==L&amp;&amp;rand(          )&amp;4)){ N=L
D !h&amp;&amp;s) i          =n,z=O,b=p          D h&amp;&amp;c-L&lt;S          ) P L; } q
          &gt;5&amp;d&lt;2&amp;C+6          &lt;A&amp;&amp;(g=I+p          ,r=I[p+=p-
O],m=p&lt;O?g          -3:g+2,!(e          &amp;(p&lt;O?3:5)          &lt;&lt;3*-y|*g|
          r|m[p&lt;O?1:          -1])&amp;&amp;L&gt;-           1e6&amp;&amp;1e6&gt;a
63,1,0))?d          ++:(n+=y|1          );} } } C           +=q&lt;2&amp;C+3&gt;
          A&amp;((y?O&lt;80          :39&lt;O)||r)          ; } H!r&amp;q&gt;
2&amp;q&lt;6||(p=          O,++C&lt;A))           ; } } P N+          1e8?N:0; }
