--- toledo2.c
+++ toledo2.c
@@ -17,7 +17,7 @@
                     unsigned char o[10],l[78114],*c=l,*k=l
                           #define d(e)o[e]+256*o[e-1]
 #define h(l)s=l&gt;&gt;8&amp;1|128&amp;y|!(y&amp;255)*64|16&amp;z|2,y^=y&gt;&gt;4,y^=y&lt;&lt;2,y^=~y&gt;&gt;1,s|=y&amp;4
-+64506; e,V,v,u,x,y,z,Z; main(r,U)char**U;{
++64506; long e,V,v,u,x,y,z,Z; main(r,U)char**U;{
 
      { { { } } }       { { { } } }       { { { } } }       { { { } } }
     { { {   } } }     { { {   } } }     { { {   } } }     { { {   } } }