#include &lt;stdio.h&gt;
#include &lt;math.h&gt;
#define clear 1;if(c&gt;=11){c=0;sscanf(_,&quot;%lf%c&quot;,&amp;r,&amp;c);while(*++_-c);}\
  else if(argc&gt;=4&amp;&amp;!main(4-(*_++==&#39;(&#39;),argv))_++;g:c+=
#define puts(d,e) return 0;}{double a;int b;char c=(argc&lt;4?d)&amp;15;\
  b=(*_%__LINE__+7)%9*(3*e&gt;&gt;c&amp;1);c+=
#define I(d) (r);if(argc&lt;4&amp;&amp;*#d==*_){a=r;r=usage?r*a:r+a;goto g;}c=c
#define return if(argc==2)printf(&quot;%f\n&quot;,r);return argc&gt;=4+
#define usage main(4-__LINE__/26,argv)
#define calculator *_*(int)
#define l (r);r=--b?r:
#define _ argv[1]
#define x

double r;
int main(int argc,char** argv){
  if(argc&lt;2){
    puts(
      usage: calculator 11/26+222/31
      +~~~~~~~~~~~~~~~~~~~~~~~~calculator-\
      !                          7.584,367 )
      +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+
      ! clear ! 0 ||l   -x  l   tan  I (/) |
      +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+
      ! 1 | 2 | 3 ||l  1/x  l   cos  I (*) |
      +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+
      ! 4 | 5 | 6 ||l  exp  l  sqrt  I (+) |
      +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+
      ! 7 | 8 | 9 ||l  sin  l   log  I (-) |
      +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~(0
    );
  }
  return 0;
}