--- goren.c
+++ goren.c
@@ -1,5 +1,5 @@
 typedef unsigned char t;t*F=&quot;%c&quot;,l[]=&quot;|\\/=_ \n](.\0(),*(.(=(}*.)[[*.&quot;,N=&#39;\n&#39;,*
-r;typedef(*H)();extern H Ar;Q(a){return(a|-a)&gt;&gt;31;}H S(c,a){return(H)(a&amp;~c|(int
+r;typedef(*H)();extern H Ar;Q(a){return(a|-a)&gt;&gt;31;}H S(long c,long a){return(H)(a&amp;~c|(long
 )Ar&amp;c);}extern t*ist;V(t*u){*u^=*u&amp;2^(*u&gt;&gt;7)*185;}Z(t*u,t n){*u-=n;}e(t c,H h){
 R(h,Q(*                                                                 r^c));}
 I(){r=l                                                                 +7-4*Q(