                                       /*
                                      +
                                     +
                                    +
                                    +
                                    [         &gt;i&gt;n[t
                                     */   #include&lt;stdio.h&gt;
                        /*2w0,1m2,]_&lt;n+a m+o&gt;r&gt;i&gt;=&gt;([&#39;0n1&#39;0)1;
                     */int/**/main(int/**/n,char**m){FILE*p,*q;int        A,k,a,r,i/*
                   #uinndcelfu_dset&lt;rsitcdti_oa.nhs&gt;i/_*/;char*d=&quot;P%&quot;   &quot;d\n%d\40%d&quot;/**/
                 &quot;\n%d\n\00wb+&quot;,b[1024],y[]=&quot;yuriyurarararayuruyuri*daijiken**akkari~n**&quot;
          &quot;/y*u*k/riin&lt;ty(uyr)g,aur,arr[a1r2a82*y2*/u*r{uyu}riOcyurhiyua**rrar+*arayra*=&quot;
       &quot;yuruyurwiyuriyurara&#39;rariayuruyuriyuriyu&gt;rarararayuruy9uriyu3riyurar_aBrMaPrOaWy^?&quot;
      &quot;*]/f]`;hvroai&lt;dp/f*i*s/&lt;ii(f)a{tpguat&lt;cahfaurh(+uf)a;f}vivn+tf/g*`*w/jmaa+i`ni(&quot;/**
     */&quot;i+k[&gt;+b+i&gt;++b++&gt;l[rb&quot;;int/**/u;for(i=0;i&lt;101;i++)y[i*2]^=&quot;~hktrvg~dmG*eoa+%squ#l2&quot;
     &quot;:(wn\&quot;1l))v?wM353{/Y;lgcGp`vedllwudvOK`cct~[|ju {stkjalor(stwvne\&quot;gt\&quot;yogYURUYURI&quot;[
     i]^y[i*2+1]^4;/*!*/p=(n&gt;1&amp;&amp;(m[1][0]-&#39;-&#39;||m[1][1]  !=&#39;\0&#39;))?fopen(m[1],y+298):stdin;
      /*y/riynrt~(^w^)],]c+h+a+r+*+*[n&gt;)+{&gt;f+o&lt;r&lt;(-m]    =&lt;2&lt;5&lt;64;}-]-(m+;yry[rm*])/[*
       */q=(n&lt;3||!(m[2][0]-&#39;-&#39;||m[2][1]))?stdout /*]{     }[*/:fopen(m[2],d+14);if(!p||/*
       &quot;]&lt;&lt;*-]&gt;y++&gt;u&gt;&gt;+r &gt;+u+++y&gt;--u---r&gt;++i+++&quot;  &lt;)&lt;      ;[&gt;-m-.&gt;a-.-i.++n.&gt;[(w)*/!q/**/)
    return+printf(&quot;Can &quot;  &quot;not\x20open\40%s\40&quot;    &quot;&quot;       &quot;for\40%sing\n&quot;,m[!p?1:2],!p?/*
  o=82]5&lt;&lt;+(+3+1+&amp;.(+  m  +-+1.)&lt;)&lt;|&lt;|.6&gt;4&gt;-+(&gt;    m-        &amp;-1.9-2-)-|-|.28&gt;-w-?-m.:&gt;([28+
 */&quot;read&quot;:&quot;writ&quot;);for  (   a=k=u= 0;y[u];  u=2    +u){y[k++   ]=y[u];}if((a=fread(b,1,1024/*
,mY/R*Y&quot;R*/,p/*U*/)/*          R*/ )&gt;/*U{  */   2&amp;&amp; b/*Y*/[0]/*U*/==&#39;P&#39; &amp;&amp;4==/*&quot;y*r/y)r\}
*/sscanf(b,d,&amp;k,&amp; A,&amp;           i,  &amp;r)&amp;&amp;        !   (k-6&amp;&amp;k -5)&amp;&amp;r==255){u=A;if(n&gt;3){/*
]&amp;&lt;1&lt;6&lt;?&lt;m.-+1&gt;3&gt; +:+ .1&gt;3+++     .   -m-)      -;.u+=++.1&lt;0&lt; &lt;; f&lt;o&lt;r&lt;(.;&lt;([m(=)/8*/
u++;i++;}fprintf   (q,    d,k,           u      &gt;&gt;1,i&gt;&gt;1,r);u  = k-5?8:4;k=3;}else
  /*]&gt;*/{(u)=/*{   p&gt; &gt;u  &gt;t&gt;-]s                &gt;++(.yryr*/+(    n+14&gt;17)?8/4:8*5/
     4;}for(r=i=0  ;  ;){u*=6;u+=                (n&gt;3?1:0);if    (y[u]&amp;01)fputc(/*
      &lt;g-e&lt;t.c&gt;h.a r  -(-).)8+&lt;1.                 &gt;;+i.(&lt;)&lt;     &lt;)+{+i.f&gt;([180*/1*
      (r),q);if(y[u   ]&amp;16)k=A;if                               (y[u]&amp;2)k--;if(i/*
      (&quot;^w^NAMORI; {   I*/==a/*&quot;                               )*/){/**/i=a=(u)*11
       &amp;255;if(1&amp;&amp;0&gt;=     (a=                                 fread(b,1,1024,p))&amp;&amp;
        &quot;)]i&gt;(w)-;} {                                         /i-f-(-m--M1-0.)&lt;{&quot;
         [ 8]==59/* */                                       )break;i=0;}r=b[i++]
            ;u+=(/**&gt;&gt;                                     *..&lt;/&lt;&lt;&lt;)&lt;[[;]**/+8&amp;*
            (y+u))?(10-              r?4:2):(y[u]         &amp;4)?(k?2:4):2;u=y[u/*
             49;7i\(w)/;}             y}ru\=*ri[        ,mc]o;n}trientuu ren (
             */]-(int)&#39;`&#39;;}             fclose(          p);k= +fclose( q);
              /*] &lt;*.na/m*o{ri{                       d;^w^;}  }^_^}}
               &quot;   */   return  k-                -1+   /*\&#39;   &#39;-`*/
                     (   -/*}/   */0x01        );       {;{    }}
                            ;           /*^w^*/        ;}