       Int L[A],m,b,*D=A,
        *c,*a=L,C,*U=L,u;s
         (_){u--&amp;&amp;s(a=*a);}
          char*B,I,O;S(){b=b
           --?b:m|read(0,&amp;I,1
            )-1;return~I&gt;&gt;b&amp;1;
             }k(l,u){for(;l&lt;=u;
              U-L&lt;A?*U++=46^l++[
               &quot;-,&amp;,,/.--/,:-,&#39;/&quot;
               &quot;.-,-,,/.-,*,//..,&quot;
              ]:exit(5));}p(Int*m){
             return!*U?*m=S()?U++,!S
            ()?m[1]=p(++U),2:3:1,p(U)
           :S()?U+=2:p(U[1]++),U-m;}x(
          c){k(7*!b,9);*U++=b&amp;&amp;S();c&amp;&amp;x
         (b);}d(Int*l){--l[1]||d(l[d(*l),
        *l=B,B=l,2]);}main(e){for(k(10,33
       ),a[4]-=m=e-2&amp;7,a[23]=p(U),b=0;;e-2
      ?e?e-3?s(D=a),C=a  [3],++1[a=a[2]],d(
     D):c?D=c,c=*D,*D=    a,a=D:exit(L[C+1])
    :C--&lt;23?C=u+m&amp;1?O      =O+O|C&amp;1,9:write(m
   ||(O=C+28),&amp;O,1)+        1:(S(),x(0&lt;b++?k(0,
  6),U[-5]=96:0)):(          D=B?B:calloc(4,X))
 ?B=*D,*D=c,c=D,D[            2]=a,a[++D[1]]++,D
[3]=++C+u:exit(6)              )e=L[C++],u=L[C];}