#include &lt;stdio.h&gt;
#include &lt;string.h&gt;

char X[] =
  &quot; ETIANMSURWDKGOHVF:L:PJBXCYZQ::54:3:::2&amp;:+::::16=/:::(:7:::8:90&quot;
  &quot;::::::::::::?_::::\&quot;::.::::@:::&#39;::-::::::::;!:):::::,:::::&quot;;

int j,w,h,f,u,d,g,e,n,i,l,a,r,p,c,m,o,t,s,Q=32,T[32],W[32],I=13000;

int main(int v, char** b) {

  for (i=0;v&gt;0&amp;&amp;v&lt;5&amp;&amp;(v*=t=fread(X,1,1,stdin));)

  for (v-1&amp;&amp;101==*1[b]?++g%1500?u+=(g&amp;1^1)*(*X&lt;0?-*X:*X):(f=e,e=w,w=d,d=u,
    m=(1 - h%2* 2  )*(d -f)/ (d&lt;f  ?d|1 : 1|f) &gt;  5?T[ h%Q] =o+l  , l=W[
    h++%Q]=o,o=0:m,o++,u=main(0,b)):(c=strrchr(X,~(Q&amp;*X&amp;*X/2)&amp;*X)-X,j=255);
    v==1&amp;&amp;(c*j||main(*X-Q?8:24,b));j/=2)c&lt;j?0:main(9+(c-j)/(j/2+1)%2*10,b);

  for (a=u=0;i&lt;=Q*Q&amp;&amp;!v;j&gt;7&amp;&amp;j&lt;13?s=c*s+T[i/Q]/2,s/=++c:0)
    !(i++%Q)?a=c&gt;a?u=s,c:a,c=s=0:0,j=T[i%Q],j=j?T[i/Q]*10/j:0,j*=(j&lt;5)*2+1;

  for (r+=(h-r)/Q*Q;i&lt;v/4*I;putchar((i/I&lt;v%4)*i%2*85&lt;&lt;(i%176/88)),i++);

  for (g*=!!v;r+t!=h+1&amp;&amp;h&gt;5&amp;&amp;!v;r+t!=h+1?(W[r%Q]&gt;2*u||r==h?p=n=n&gt;6?0:
    putchar(X[p-1+(1&lt;&lt;n)])&amp;0:0,W[r++%Q]&gt;6*u?putchar(Q):0):0)
    *X=Q,p=r%2?++n,2*p+(W[r++%Q]&gt;2*u):p;

  return 0;
}