







                #include&lt;stdio.h&gt;/*IOCCC2014            2014    2014    IOCCC2014IOCCC2014IOCCC201*/
                char*s=&quot;\&quot;nsu{AntynCnuq}Bnu{            sEot    ln&gt;b    )+c^g+@`+]_osk{;j@bkg&amp;c&lt;&#39;^o\
                r&#39;Q]                    bh&#39;l    vQ^k                    g&amp;c:                    %n|\
                N]_o                    ptj9    lwg+                    )d:b                    kg$\
                c8#^    #g+)d8`a%g+)    d8`_                g&amp;;bh&#39;oq    Q^)g    +&amp;kcNlyMc+)d    8`a\
                `g+@    u)|d8ak=bl}(    Q^og                (O{MK6lM    L(rR    pOpM866OsRlm    N(q\
                Q]##    OsR#M_(lQoOa    N9$m    vOwwRor~        }(cN    mkM:    q(Q]%_(uU]}_    {8b\
                %mRh    #S^`#mOaaD%/    RI4$    4SNH$%N4        RlMG    /2MJ    24O3NF(tQ?1l    N*N\
                +Q]l    mq9l8b$^#h$#    .d,d    xv#mSOPm    R8`/        lM;b    h&amp;^/lM:k8b%&amp;    Q^-\
                h%c9    .#,/&amp;N$McPc%    -d8,    $c8``7:b    %^h%        :79b    $^%$7ON8r%Qr    h$Q\
                On%q                    N%O~        M$qN$OMp    RmPQ    O%rQ                    $rQ\
                MkQN                    77O#        dj#Nkd$7    O%d8    ``(r                    RmM\
                :(luN](%mRMmO%lNRmO_loa8%%O&lt;    b(lQ    h&#39;lQ    O^ln    ;b&#39;%N&amp;O^6sN#M9slltwzh&amp;TmS$&#39;\
                %R#ON$oNS&amp;pRM7O$&#39;%S#ON$oNS&amp;p    SMd9    ``(t    pkO9    $:nk8b#^%}kx#O%lMtpk#OQOP:#\
                                                mR8`}(qQ        O&lt;b\
                                                &#39;7M{N^kh        &#39;Q]\
                    7sN&#39;    M8q;k&#39;N_7vN&#39;nSM8    &#39;nR;    $%M&#39;    TamS&amp;7O#d#7O    &amp;d8`z9b$    ^h$\
                    rQ]6    yN$_$$pQaM8m{px$    TmSt    6O#N    sM$nRmUd#7Os    d77sNOsd    8`j\
                =nk;        |8k9    b1g(    Q^)$c:%]    k*Q]g$9%_h*]+wnS        _+sTaa:&amp;%{R\
                M&lt;%{        S{O_    &amp;&lt;#w    kP8#a;&#39;(    0d:`184&gt;b)^15)OM        :23h)QN&lt;&#39;/M\
                    =b(^&#39;h(Q]0h#    c_kah%0d9`b&#39;/O(Q^(/SlM90%M(/            RM;&amp;    $c&amp;kckQ,    -$c\
                    .&amp;kccMcOP$&amp;d    9g(=``6:69j=b5g(Q^3(2lNUO&lt;b4            &#39;Q^s    ;b&amp;^%%pQ    M8k\
                        $7O#cQ]0(2(Q]&#39;2O    3&#39;Q]&#39;_3a    N_1&#39;    5OMaMch&amp;T$mR#nRMPmSk    U$7\
                        O#d8_a%%mS]l_%mR    mS]$]h$9    j_la    _$6N]g$9j_laaaN:`g&#39;&lt;    ``7\
                oM:6%N9b%g$Q        ^6%N8b%g    #Q^l            peoqemtemw#jQ7#QO$jQ    O7$Q    Ok#\
                $7OMQ]k_#$7O        ckQaOrON    epne            luelue`lpeoqempepneu    e`kf    _a`\
                                                lf))    *+,**,*)-)/),0).0(6/2+667,(&amp;    $##\
                                                #;=@    D*0;#include&lt;stdio.h&gt;@intYH[    9`%\
                .],*s,*c,d,t;`;&#39;main(`-9n,ch            ar*v    []){        for(s=c=    H+3`XI;\
                (*++s=Q[d++]););for(;n&gt;1&amp;&amp;(*            ++s=    v[1]        [tgANs=H    ;d=*c++\
                %93,                    d-9;    ){in    tYv=*s,g        []={    n+v,        v-n,n*_\
                ,#^_                    ,,&lt;v    ,n?v    /n:0`,#%        `,,v    &gt;&gt;n,        v==n}ay\
                &gt;t=0    ;d&lt;4&amp;&amp;d&gt;=2*!    !n&amp;&amp;    (c-=d/3*2_KK3+*c++,t||v!=98+d);)        t+=v++/6-16\
                ?0:v    /2%3-1cq*d-1    4;t&gt;    0_t$&lt;3_z(105&lt;*c_X&#39;=t*21aq@-106;n        =d&gt;76?s--,g\
                [d-7    7]:d&gt;55?H_1)    21]=    n,*_@_8(        9?*++s_4&amp;12&gt;d_C`f3]+=21-d*2\
                :d&lt;3    4?t:_Zadat57    &lt;d?p    utchar(n        ),v:6&lt;a](g+99]=a{d2#:`xa6,n\
                ;}re    turnY_.&quot;,*p,    b,d[        9338    ],*q,x,*r=d;            int main(){;for(
                p=q=    5000+0+d;*s;    s++)        if(*    s&gt;32)*p++=*s            -89?*s:32;for(p=
                1152                    +q;(    b=*p++);){for(d[17]=            10;x    =*p++,b&lt;
                92&amp;&amp;                    34&lt;b    --;*r++=x)if(x==9*9)            for(    ;*q;x=34
                )*r++=*q++;for(p-=b&lt;92;b--&gt;4        *23;r++)    *r=r[36-    x];}puts    (d);
                return(0);}/*IOCCC2014IOCCC2        014IOCCC    2014IOCC    C2014IOC    CC*/







