

  #include   /*recall-the\    /-good--old-\    /IOCCC-days!\    */&lt;unistd.h&gt;
   typedef  unsigned/*int*/  short U;U(main)  [32768],n,r[8];  __attribute__((
  # define  R(x)       A(r[  7-(n       &gt;&gt;x&amp;  7)],       (n&gt;&gt;  x&gt;&gt;3       )%8)
  #define   C(x)       (U*)  ((/*             |IO|             -dpd
  */char*)  main       +(x)  )/*|             |CC|             ll*/
  # define  A(v,       i)(i  ?i&lt;2             ?C(v             ):i\
  -4?v+=2,  C(i-       6?v-  2:v+       *C(v  -2))       :C(v  -=2)       :&amp;v)
  /*lian*/  constructor))U(  x)(){for(;;*r+=  2,*r+=!n?_exit(  write(2,&quot;Illeg&quot;
  &quot;al ins&quot;   &quot;truction ;-&quot;    &quot;(\n&quot;,24)),0:     n&gt;&gt;8==001?(      signed char




                 )n*2   :548==n&gt;&gt;    6&amp;&amp;usleep     /**/(10
                 )+n%  64==   4?0*  write  (r[7   /**/],C(
                 *C(*  r)),   *C(*  r+2)   )+4:  /**/ n&gt;&gt;9
                 ==63   &amp;&amp;--r[7-n/   64%8]?n%+  /**/  64*-
                 2:0,         n&gt;&gt;6  ==47   ?*R( 0):n&gt;&gt;12==1?
                 *R(0  )=*R   (+6)  :n&gt;&gt;  12==+       14?*
                 R(0)   -=*R(2*3)    :0)n=*C(*        r);}

