#define/**/Alan/**/(fflush(0),j=c=0;++c&lt;b[6]+7;v=b[c]^(b[c+
char*H=&quot;close\r\nContent-Type:text/html\r\n\r\n&lt;canvas id=\
&#39;c&#39;width=&#39;128&#39;height=&#39;128&#39;style=&#39;width:256px;height:256px&#39;\
&gt;&lt;script&gt;x=y=-1;v=window.c;v.onmousemove=function(e){x=e.p\
ageX-v.offsetLeft;y=e.               pageY-v.offsetTop};w=\
new WebSocket(&#39;ws&#39;+                     location.href.subs\
tr(4));w.binary&quot;                          &quot;Type=&#39;arraybuff\
er&#39;;w.onmess&quot;                               &quot;age=function(\
e){c=v.getC&quot;                                 &quot;ontext(&#39;2d&#39;)\
;b=c.crea&quot;              &quot;teI&quot;                 &quot;mageData(12\
8,128);u=        new Uint8Array(d=e.           data);b.dat\
a.set(u)      ;c.putImageData(b,0,0)            ;u[0]=x/2;\
u[1]=y/2    ;w.send(d.slice(0,x&lt;0?0:             2));x=y=-\
1}&lt;/scr&quot;   &quot;ipt&gt;&quot;,b[9999];float*e,d[             65536],u,v
,lu,lv,    z;void*f;typedef unsigned              long long
l;l*p,t[  99]={0x67452301,0xEFCDAB89,            0x98BADCFE
,308438*  881,3285377520       },i,j,k           ,n,m[204];
#include        /*io*/          &lt;stdio.h&gt;        /*turing*/
void s(){  ;     for(  k          =0;k++&lt;7 *  2  *9;)for(i=
0;++i&lt;127; )      e=d +  i* 4   +512*k,1[e]      +=(i-u)*(i
-u)+(k-v)* (k- v  )&lt;20?*e+=UV_DROP:0;}l*q=  m,   g=1LL&lt;&lt;32;
l(h)(l v,l (a)){ return(v&lt;&lt;a)|(v%g&gt;&gt;(32-a    )  );}int main
(int c/*ha r*/,  char**y){for(e=d;fgets(b      ,m[97]=480,\
stdin)&amp;&amp;*b &gt;31;  )for( i=j=0;n=b[i],i&lt;18   ?  (l)&quot;sec-webs\
ocket-key: &quot;[i]       ==(n|32):n-32? m[j/4]  |=(j&lt; 24?n:(l)
&quot;258EAFA5-&quot; &quot;E914-47DA-95CA-C5AB0DC85B&quot;     &quot;11\x80&quot;[j-24])
&lt;&lt;(3-j%4)*8 ,++j&lt;61:1;)i++;for(j=3;--j;    ){for(i=4;++i&lt;74
;)i&gt;9?p=q+i- 2             ,p[8]=h(p[5     ]^*p^p[-6]^p[-8]
#define/*hah  aha          &lt;--mouth*/      laplacian(u)l##u
,1):(t[i]=t[9 -i]       );for(p=t+7          ,i=-1;++i&lt;82;k
=*p++,p[2]=h(p[1],5)   +p[-3]+n+     (i/+     20%2?*p^k^p[-
2]:(*p&amp;k)|((i&lt; 20?~*p:*p|k)&amp;p       [-2        ]))+*q++,t[+
81-i]+=(i&gt;76)*     (* p=          h(*           p,30*(i&lt;80)
)))for(;n-k;n=(((               1LL               +(9&lt;&lt;i/20
)/8)&lt;&lt;60)/k+k)/2)             k=n   ;}  for     (i =0;i&lt;57;
i++)i&lt;30?q[i%5*             16/   3+   i/5]   |=t[i%5]%g&lt;&lt;4
&gt;&gt;(30+i%5%3*2-i/5       *6)&amp;   63,0    :(n   =*q++,b[i-30]=
n&lt;62?n-37+&quot;fl!&quot;     [n      /26]:n    *4-    205);for(prin\
tf(&quot;HTTP/1.1 &quot;/*    |     */&quot;%d &quot;          &quot;OK\r\nConnecti\
on:%s%.27s=\r\n\r\n&quot;       ,101   +99*!  *m,!*m?H:&quot;upgrade\
\r\nUpgrade:webso&quot;        &quot;c&quot;   &quot;ket\r\nSec-WebSocket-Acce\
pt:&quot;,b);e-d&lt;65536 ;      e+=  4)e[1]=(*e=UV_BACKGROUND);for
(;*m;c=0){for(f= c&lt;      2  ?0:fopen(y[1],&quot;r&quot;);f&amp;&amp;fscanf(f,
&quot;%f,%f,&quot;,&amp;u,&amp;v)&gt;0;)s      ();for(;j&lt;SPEED*4;j+=2)for(i=0;i&lt;
63504;e+=5-j%4*2,z=      TIMESTEP,*e=u+z*(elta_u),e[1]=v+z*
(elta_v),i+=4)for(c=  0;c+2;u=v,v=e[4],lu=lv,lv=e[-508]+*e+
e[8]+e[516]-v*4)e=d+i+512+i/504*8+j%4-c--;for(;n=c%4,65544&gt;
c;c++)putchar(c&gt;7?n&gt;2||(u=d[c-n-7]*4*(n&lt;2?!n?RGB))&gt;255?255:
#define/*x*/Turing(x)4]=getchar()&amp;127))u=v;if(b[6]&gt;1)s();}}
u&lt;0?0:u:c&lt;0?124-c*3:c==5);/* -- The word &quot;genius&quot; is */ for


                 Alan Turing  (1912--1954)