                                           #define r(R) R&quot;()&quot;
                          /*[*/#include  /**/&lt;stdio.h&gt;
                      #include&lt;math.h&gt;/*!![crc=0f527cd2]*/
                   float I,bu,k,i,F,u,U,K,O;char o[5200];int
              #define R(U) (sizeof(&#39;U&#39;)==1||sizeof(U&quot;1&quot;[0])==1)
            h=0,t=-1,m=80,n=26,d,g,p=0,q=0,v=0,y=112,x=40;  float
           N(float/*x*/_){g=1&lt;&lt;30;d=-~d*1103515245&amp;--g;return  d*_
          /g;}void/**/w(int/**/_){if(t&lt;0){for(g=0;g&lt;5200;o[g++   ]=
          0);for(;g;o[g+79]=10)g-=80;for(t=37;g&lt;62;o[80+g++]=32)   ;
         }if(m&amp;&amp;o[h*80+m-1]==10){for(g=0;g&lt;79;o[t*80+g++]=0){}o[t
         ++*80+g]=10;t%=64;n+=2;I=N(70)+5;if(n&gt;30&amp;&amp;(I-x)*(I-x)+n*
        n&gt;1600&amp;&amp;R()){O=0;F=(x=0x1!=sizeof(&#39; &#39;))?k=1+N(2),i=12-k+N(
        8),N(4):(k=17+N(5),i=0,r()[0]?O=.1:  0);for(u=U=-.05;u&lt;32;
        U=k+i+i*.5*sin((u+=.05)+F))for( K=0   ;K&lt; U;K+=.1)if((bu=K*
       sin(u/5),g=I+cos( u/5) *K)&gt;=0&amp;&amp;g  &lt;     79  )o[g+(int)(t+44+
       bu*(.5-(bu&gt;0?3*O:  O)   ) )%64*  80      ]  =32;x*=02//* */2
      -1;n=O+x?n=I+(x?0   :N     (k)-   k           /2),g=(t+42  )%
      64,m=-~g%64,x?g=m          =-~        m%64:0  ,n&gt;5?o[g*80   +
     n-3]=o[m*80+n-3]=       0:   0              ,n &lt;75?o[g*80+n
     +2]=o[m*80+n+2]=0   :0:0;                      x=I;}h=-~h%64
    ;m=0;}putchar((g=o [h*                          80+m++])?g:_);
   if(g){w(_);}}void W                               (const char*_
  ){for(;*_;w(*_++));}                               int main(int a
  ,char**_){while(a--)d              +=_[a          ]-(char*)0;W( \
 &quot;#include&lt;stdio.h&gt;typed&quot;             &quot;e&quot;         &quot;f\40int\40O;v&quot;
 &quot;oid o(O _){putchar(_);}O&quot;                    &quot;\40main(){O&quot;  &quot;&quot;
&quot;*_[512],**p=_,**d,b,q;for(b=0;b&quot;        &quot;++&lt;512;p=_+q)_[q&quot;    \
&quot;=(p-_+1)*9%512]=(O*)p;&quot;) ;      for(;(g= getchar())-EOF;p=
q){q=p;for(v=512;p-q-g&amp;&amp;q-p-              g;  v--)q=-~q*9%512
;W(&quot;o(&quot;);if(p&gt;q)w(y),w(45);w(                      40);w(y^=20
);w(075);for(a=0;a&lt;v;a++)w(42);                      for(W(&quot;(O**&quot;
 );a--;w(42)){}w(41);w(y^024);w(                      41);if(p&lt;=q)w(
   45),w(y^20);W(&quot;);&quot;);}for(a=7;a-6                      ;W(a&lt;6?&quot;{;}&quot;:&quot;&quot;
      ))for(a  =0;a  &lt;6 &amp;&amp;   !o[h*80+m                       +a];a++){}W(&quot;r&quot;
         &quot;etu&quot;  /*J   */       &quot;rn+0;}\n&quot;                             );return
             /*                      &quot;#*/0                                   ;}