#include &lt;sys/ioctl.h&gt;
#include &lt;unistd.h&gt;
#include &lt;string.h&gt;
#include &lt;signal.h&gt;
#include &lt;stdlib.h&gt;
#include &lt;stdio.h&gt;
                     #define O_o &quot;sfX4.Fv8H!`uf&quot;\
                &quot;|~0y&#39;vWtA@:LcO9d}y.!uL!Gd+ml(&lt;+Ds!J&quot;\
            &quot;e.6!r!%l6G!n~^&lt;i=%pEwL%P!&#39;&lt;!FQt%u 5toG57j/3&quot;\
         &quot;!:E%;!ea!!!WqE0z!f/y}!%!!Qi6!uzt!n}?]!bl!ak!SetR&lt;&quot;\
       &quot;Zj$x!~V!n&amp;g8!cK! KrgR&#39;8@c]!%-q9V.3fa[E8X%dY&#39;w!#H &lt;P~6&quot;\
      &quot;?guhljL!^P% ?&quot;                            &quot;8!@dP,!!o+fb&quot;\
     &quot;!pv!;!Hm%Ro4&quot;                                &quot;n:}nkD!Q!kN&quot;\
     &quot;e:| &#39;b5sc!e&quot;                                  /* nothing */
     #define mu(a)                                  a a a a a //-
     #define O_(Q_                                  ) &quot;\033[&quot; #Q_
     #define Q_(O)                                  mu(mu(mu(O)))
     #define Q/*--                                  ++--*/O9--||(
     #define main(                                  )main(){/**/\
     signal(13,1),                                  _();}f()//--+
     #define k( k)                                  getenv( &quot;D&quot;#k
 char*O0=O_o,OO,*Q1,O5[97];int*Q5,_Q=0,Q0=0,_O=0,_0=0,O=5,QQ,O6,Q6,O3
,Q4,O4=41088,O1=sizeof(O5),O7=234;long long __;_()Q_({)int*Q3,Q2,O2,C,
QO,O9=O,O8=!!!!!!!!!!k(RAFT));long long Q8;char*Q9=O_(1A)O_(%dB)O_(%dC
)O_(34m)&quot;\xe2%c%c\r\n&quot;O_(0m)O_(%dA),*Q7;__+=(__*92+*O0-35-__)*(QO=Q_(!
!)(*O0-33)*!O9--),O0+=O1*QO,QO&amp;&amp;_(),Q Q4&amp;&amp;(O--,_(),O0+=194,O++,Q4--,_(
))),Q O=0,__=0,_(),O=3,_()),Q __&amp;&amp;(C=__&amp;15,_O+=(C&lt;2)*12+!(QO=C&amp;14^2)*(
4-_O)+(C==6)*( 12-2*_O)+(C&gt;6)*(9-(C-7)%3),_Q+=!QO*(_Q%QQ+(C&amp;1)*O3-_Q),
_0+=!_0*!QO+(1-2*_0)*!(C^4),(C==5)&amp;&amp;(__&gt;&gt;=4,Q8=__,Q7=O0,Q4=__&amp;15,O=1,_
()|O     ++&amp;_(),__=Q8    ,O0=Q7 ),Q3=(        _Q+=     O8*(9      *O4*
O1 &gt;     lrand48())        +(_O%=8,(          (_O%     6&gt;2)      -(_O%
7&lt;2)     )*QQ+((_O          +7)%8&lt;3       )-(_O&gt;4)     )*(      C&gt;5 ),
Q2 =     _Q/ O3)*            O6+Q5      +(O2=_Q%QQ     )/      2,*Q3=*
Q3 %     O4+O4|(1     &lt;&lt;     Q_(&quot;&quot;     &quot;@CADBEHI&quot;)            [_Q%2+_Q
%O3/     QQ*2 ]-     64)*     _0,      sprintf(O5,           Q9, Q2+1,
O2/2     ,*Q3&gt;&gt;8     ,85*     3&amp;*      Q3,Q2+1 )&amp;&amp;           _0&amp;&amp;(O=8,
Q1 =     O5,_()),     Q0     +=(O2     &gt;Q0)*_0*(O2            -Q0 ),__
+=!(     C&gt;9)*(3-            __+ (      __&gt;&gt;4))-3,     __      +=(C&gt;12
) *(     (__&lt;&lt;4 )+          C-3-__)       ,usleep(     O4*      _0/(3*
O8+1           )),O        =3,_() ))          ,!O9     --&amp;&amp;      read(
1 ,&amp;           OO,1)&gt;    0&amp;&amp;(O= (QO=OO        ==35     )*3+6      ,_()
,QO&amp;&amp;(OO=10,O=6,_(),1)||(O=4,_()),0)||close(dup2(3-dup2(1,dup(0)-3),1)
*0+2)*0||Q write(1,&quot;&gt; &quot;,2),ioctl(Q0=0,TIOCGWINSZ,O5)^--O&amp;(O3=(QQ=(O6=*
((short*)O5+1))*2)*4),Q6=-O1,Q5=calloc(3*O6,8),_()),Q (O=8,QO=!(O2=OO-
10)|!(Q2=OO-32)*(Q0+58&gt;QQ)|(Q0+12&gt;QQ))&amp;&amp;(Q1=O_(3B),_(),write(1,&quot;&gt; &quot;,2)
),Q0+=!QO*!Q2*4-QO*Q0,O2*Q2&amp;&amp;(!Q0&amp;&amp;(memset(Q5,0,3*O3),Q0=4,Q1=&quot;\n\n\n&quot;
O_(3A),_()),O=7,_Q=7*QQ+Q0+2,_O=_0=0,OO+=(OO&gt;64 &amp;OO&lt;91)*32,O0=Q_(O_o)+
O7,_(),(*O0-OO)||(O=2,O0+=&#39;a&#39;,_( )))),Q *O0-OO)&amp;&amp;(*(O0+=O1)-33)&amp;&amp;(O=0,
_(),O=7,O0+=O1,_()),Q write(0,Q1,strlen(Q1))),Q OO=Q_(O_o)[Q6+=O1],(Q6
 %strlen(O_o)-O7)&amp;&amp;(O=6,_(),O=9,_()));Q_(})/*+++++ IOCCC 2015 +++++*/

main()
{
    puts(&quot;hello world!&quot;);
}