#include/*nui*/&lt;stdio.h&gt;//;70/*#}r[3]op;f(p;ok})i[;k-r*?(rc&amp;(o}nr**s*2)!}-mpi##
extern int n0;typedef int x;x//i/eu2-&gt;uuo0uo=;nXfdx+1e8uOeh&amp;k-x[e1(i)&gt;{=eqa,nii
n,u,k,o,_,i=1;static char//[X]/f/t]:n=t-rxt+0f[=(-=+;t)*,aa!&gt;1=dt0pzrpi(l)idtnn
d[1125][0x401];x main(){if(//]* nu]O[nc-(ac=;odxx1k]}u)2ulr(=00+u2=ee&amp;fos{n,*cc
i){for(n=0;1024&gt;n;n++)//]Tkhng[0ur)[u[h&gt;u)h1or];&gt;]-=Or):=l*Ou);+r4poa&amp;(=ep(qnll
for(u=0x0;u&lt;1025;)d[n][u++]=64//[n;o]ua0=)a,&lt;(=}X;no[n{8uo)=&amp;{i]n)?fl!!g{u)=,uu
/2;for(u=n=0////////]_#p^#onui[/u+}+?+r;d{r/X////////////c/(&amp;if=-)p(l(xewt{1udd
/4;EOF!=(o=////////////]#ebdl#ah[0}n/1()////////////////////1f(k1)*ion)thsO;,ee
getchar())//        //////]u#oh[,;///////////            //////;;)2nc={ci(=ck&lt;&lt;
&amp;&amp;u&lt;1024;//            /////////////////                    ////}{:t((ihl&quot;Nh,ss
)u+=o-10//                /////////                            ///2)nifaeYUaott
?n&lt;1024//                                                       ////,n(r(uLr,dd
?d[n++//       @@@                                                ///td(EuL*Xli
][u]=o//      @   @                                                ///+)Or;O,io
,k=k&lt;//       @   @                                                 ///)Fii;xb.
n?n:k//       @   @                                                   ///&quot;fi,.h
,0:0//         @@@                                                     //)(n/h&gt;
:!(n//                                                                 //;0t/&gt;/
=0);//                                                                  //!/|//
for(//      5                                                           //=/*/%
 ;k--//     12                                                           =q tni
;)d[k//                                                                  //))u/
/01][u//                                                                 //1Ni/
/1]/*n///                                                                //(Ui;
&gt;*/=!/*N//                                                               //=K~/
h*/1,/*UN///                                                            //nqO~*
.*/puts/*n////                                                          //[/?,]
o*/(d[k])/*u//////               ///////                                //1*q[u
i*/;}else{//t/////////////      ///////////                            //,stup;
d[0][0]++;puts(/*f/////////     //]====[////////                       //(N tni
ti&amp;/N/////.///s/It]]_bz8[//     ///SHOUJO\vv///////////               //;}&quot;jvo&quot;
su /U/////N///t}Ue]~J#phi[//    //\SHUUMATSU|]_[////////             ///,&quot;/utf&quot;
&lt;ntt/fe=)|UI0{u;Nnu]^u#j[v//    //,^^\RYOKOU/:)]a#p[.//            ///&quot;c!tj!xb&quot;
e/ n/ilI(|/(1ep)/ *&gt;-&gt;IOCCC//   //]^#dbi#`h#anuok^u#[//          ///&quot;S&quot;,&quot;/ttfm&quot;
d/eit{i(rl/r-s-&quot;/e/]o[^^^^^!/////]hfhu[Qj:FfT]uhp)~[[//      ///&quot;iuspx!fsb!tho&quot;
unn;n)h=a({aIl0onnt//&quot;jiu!fmcjefoJ&quot;,&quot;/zsbdt!fsb!tobnvI!&quot;  &quot;///&quot;,&quot;~&lt;1!osvufs&lt;*2&quot;
lriqi(w!hf)h=e1trin//&quot;.;2;1;1+*432&amp;25\*3,o)_6)92x\sbiduvq@1=v@2:.o@4:.o),v,1/&gt;&quot;
cef ;n{Fci2cl}-iufi//&quot;v*1?**)sbidufh&gt;o))fmjix|*)ojbn!uoj&lt;v-o!uoj31\?i/pjeut=fe&quot;
ntetli)Ot{3t;}lhte}//&quot;vmdoj$&quot;,&quot;svpU!utbM!(tmsjH&quot;{=]041[]6[u,n*rahc;q tni nretxe
ixdn,aqEe)-u)}=Ced;//};0+nruter;)K(U;)++n*--;n*;K=n(rof{)(niam )O,K,U(N enifed#
#e#iIm((g)Ip ;I&quot;r#0.[(c)2018][cffc189a]*/&quot;Nuko&quot;);}return+0;}//&gt;h.oidts&lt;edulcni#