        #define/*__Int3rn^ti[]n/l_()I3fusc^t3|]_C_C&lt;&gt;I7E_C[]nt3st__*/L/*__MMXVIII__*/for
    #include/*!&quot;&#39;()*+,-./12357:;&lt;=&gt;?CEFGHIJKLMNSTUVWXYZ[]^_`cfhijklmnrstuvwxyz{|}*/&lt;stdio.h&gt;
  char*r,F[1&lt;&lt;21]=&quot;~T/}3(|+G{&gt;/zUhy;Jx+5wG&lt;v&gt;&gt;u55t.?sIZrC]n.;m+:l+Hk]WjNJi/Sh+2f1&gt;c2H`)(_2(^L\
 -]=([1/Z&lt;2Y7/X12W:.VFFU1,T77S+;N?;M/&gt;L..K1+JCCI&lt;&lt;H:(G*5F--E11C=5?.(&gt;+(=3)Z-;*(:*.Y/5(-=)2*-U,\
/+-?5&#39;(,+++***&#39;&#39;EE&gt;T,215IEUF:N`2`:?GK;+^`+?&gt;)5?&gt;U&gt;_)5GxG).2K.2};}_235(]:5,S7E1(vTSS,-SSTvU(&lt;-HG\
-2E2/2L2/EE-&gt;E:?EE,2XMMMM1Hy`)5rHK;+.T+?[n2/_2{LKN2/_|cK2+.2`;}:?{KL57?|cK:2{NrHKtMMMK2nrH;rH[n&quot;
&quot;CkM_E21-E,-1-&gt;E(_:mSE/LhLE/mm:2Ul;2M&gt;,2KW-+.-u).5Lm?fM`2`2nZXjj?[n&lt;YcK?2}yC}H[^7N7LX^7N7UN&lt;/:-\
ZWXI&lt;^I2K?&gt;T+?KH~-?f&lt;;G_x2;;2XT7LXIuuVF2X(G(GVV-:-:KjJ]HKLyN7UjJ3.WXjNI2KN&lt;l|cKt2~[IsHfI2w{[&lt;VV&quot;
&quot;GIfZG&gt;x#&amp;#&amp;&amp;$#$;ZXIc###$&amp;$$#&gt;7[LMv{&amp;&amp;&amp;&amp;#&amp;##L,l2TY.&amp;$#$#&amp;&amp;$,(iiii,#&amp;&amp;&amp;#$#$?TY2.$#$1(x###;2EE[t,\
SSEz.SW-k,T&amp;&amp;jC?E-.$##      &amp;#&amp;57+$$#      &amp;&amp;&amp;W1-&amp;$$7W  -J$#$kEN&amp;#&amp;      $##C^+$##W,h###n/+L2YE&quot;
&quot;2nJk/H;YNs#$[,:TU(#$   ,:   &amp;&amp;~H&gt;&amp;#   Y;   &amp;&amp;G_x&amp;#2;   ,mT&amp;$YE-#&amp;   5G   $#VVF$#&amp;zNs$$&amp;Ej]HELy\
CN/U^Jk71&lt;(#&amp;:G7E+^&amp;#  l|?1  $$Y.2$$  7lzs  WzZw&gt;&amp;$E    -&lt;V-wE(2$$  G&gt;x;  2zsW/$$#HKt&amp;$$v&gt;+t1(&gt;&quot;
&quot;7&gt;S7S,;TT,&amp;$;S7S&gt;7&amp;#&gt;E_::U  $$&#39;&quot;,op  ,*G=  F,*I=957+F  ;int*t,k,O,  i,   j,T[+060&lt;&lt;+020];int M(
int m,int nop){;;;return+   m%(0+nop  );;}  int*tOo,w,  h,z,W;void(C)  (int n){n=putchar(n);}int
f,c,H=11,Y=64&lt;&lt;2,Z,pq,X   ;void(E/*d  */)(  int/*RP*/n  ){L(Z=k+00;  Z;  Z/=+2+000)G[000]=*G*!!f
|M(n,2)&lt;&lt;f,pq=2,f=+06   &lt;f?++pq,++pq  ,G++  ,z:f+001,n  /=2;;}void  (V)(  int/*opqrstabd*/n){C(n
%Y);;C(n/Y+00);;}void  J(){L(pq--,pq   =j   =O=-1+0;++  j&lt;240;I[6+   (h   +6+j/12/2*2+M(j/2,2))*
W+M(j/2/2,+06)*2+w*014      +00+M(00+      000+j,002      +00)]=000      +00+k)k=M(G[j/2/2+(*r-+
32)**&quot;&lt;nopqabdeg&quot;],/*4649&amp;96#*/3);/*&amp;oaogoqo*/;}/*xD%P$Q#Rq*/int/*dbqpdbqpxyzzyboo3570OQ*/main()
{L(X=Y-1;i&lt;21*3;i++,I++)L(r=G,G+=2;*G++;)*G&gt;=13*3?*G-*r?*I++=*G:(*I++=r[1],*I++=r[2]):1;L(j=12,r
=I;(*I=i=getchar())&gt;-1;I++)i-7-3?I-=i&lt;32||127&lt;=i,j+=12:(H+=17+3,W=W&lt;j?j:W,j=12);L(;*r&gt;-1;r++)*r-
7-3?J(),w++:(w=z,h+=17+3);C(71);C(73);V(&#39;*&#39;*&#39;1&#39;*7);C(57);C(32*3+1);V(W);V(H);C(122*2);L(V(i=z);i
&lt;32*3;)C(i++/3*X/31);C(33);C(X);C(11);L(G=&quot;SJYXHFUJ735&quot;;*G;)C(*G++-5);C(3);V(1);L(V(j=z);j&lt;21*3;
 j++){k=257;V(63777);V(k&lt;&lt;2);V(M(j,32)?11:511);V(z);C(22*2);V(i=f=z);V(z);V(W);V(H);V(1&lt;&lt;11);r=
  G=I+W*H;L(t=T;i&lt;1&lt;&lt;21;i++)T[i]=i&lt;Y?i:-1;E(Y);L(i=-1;++i&lt;W*H;t=T+Z*Y+Y)c=I[i]?I[i]*31-31:(31&lt;
    j?j-31:31-j),Z=c[t[c]&lt;z?E(Z),k&lt;(1&lt;&lt;12)-2?t[c]=++k,T:T:t];E(Z);E(257);L(G++;k=G-r&gt;X?X:G-r
        ,C(k),k;)L(;k--;C(*r++/*---#$%&amp;04689@ABDOPQRabdegopq---*/));}C(53+6);return(z);}