#include&lt;stdio.h&gt;
#include&lt;stdlib.h&gt;
#include&lt;unistd.h&gt;
typedef unsigned char*_;
_ s,i,z,e,O,F=
#include W

       &quot;; ; } { { { {	{ } { { } ; }	{ ; ; { } ; {	{ } ; } ; { {	{ { } { { } \
	; } { { { { {	} { ; } { } {	{ } { { } { {	{ ; ; { { } {	{ } { ; } { \
	    } { {	{ { {	} ; }	{ } {		{ } {		{ { \
	    } { ;	} { }	{ { {	{ { }		; } {		} { \
	    { { }	{ { }	; ; {	; ; {		{ } {		{ } \
	    { ; }	{ } {	{ { }	{ } {		{ { ;		{ { \
	    { } {	{ } {	{ { {	} { {		{ { {		} ; \
	; { ; ; { { {	{ { } { ; } {	} { { { { { }	; ; { ; ; { {	; { ; { { { \
	} { } { { { ;	{ ; { { { ; ;	{ } { { { } {	; } { } { { {	{ { } { { { \
	; ; { { } { ;	{ { { } { } {	{ { ; { ; { {	{ ; ; { { { {	{ } { { { { \
	\
	} { { { { { }	; } { } { { {	{ { { } { { {	{ } ;		} ; { { { } \
	{ { { { { } {	{ } { { { } {	{ ; { { } { ;	{ { {		{ ; { { ; { \
	{ { {		{ } }		{ { ;	{ } {	{ { ;		; { \
	{ ; { ; { } {	} ; {		} { } ; { ; }	{ { {		} { ; { } \
	{ ; { { { } {	; } }		{ ; ; { { } {	; ; }		{ ; ; ; { \
		} } {	{ } }		{ ; {	{ } }	{ } }		} { \
		; } {	} } {		; } }	{ ; ;	{ } }		} { \
	{ { { { { } }	} ; ; { } { ;	; } {	; } ;	} { } { } } }	{ } { } { } \
	{ ; } { ; ; {	} { } } { } {	; } }	} { }	} } } } } ; }	} } } ; { } \
	{ } ; } } } }	; } } } ; { {	} } }	; ; }	} { { } } } ;	{ { &quot; ; ; ; ;
unsigned v,o,l,A,T,I,L,E,c,H,a,C,K,R,Z=256; char n,M[2053]; int*q; int h(_ F,int l) { for(;
 l--&amp;&amp;*F; putchar(*F++)); return 0; } int r(int I,int O){ return!fprintf(O&amp;2?stderr:stdout
    ,&quot;%d%c&quot;,I,O&amp;1?l:32); } int m(char O){ for(a=0; a-O&amp;&amp;z&lt;e; L+=((a=*z++)==92?*z==a||*
					z==39||*z==
					34||*z==l?*
     z++:a:a)==l); return a; } int d(_ e,int l){ _ F=M+Z+q[l]; _ O=M+Z+q[n=-~l]; for(
  ; l&lt;*q&amp;&amp;n-l&amp;&amp;F&lt;O; F+=l)for(n=0; n&lt;l&amp;&amp;e[n]==F[n]; ++n); return l&amp;&amp;n==l?T +=--l,++K:0; }
 int j(){ for(c=0,o=Z,O=z; z&lt;=e&amp;&amp;M[c=*z++]&amp;16; ++C,L+=c==l); for(s=z-1; z&gt;=e; )return C-=
!c,c; for(a=M[c]; v&amp;32&amp;&amp;c==35; )return m(l),o+2; for(; a&amp;8; ){ for( ++o; M[c] &amp;12; c=*z++);
return d(s,--z-s)?o:++o; } for(; a&amp;4; ){ for(c=c==48&amp;&amp;(*z|32)==120? *++z:c; M[c]&amp;6; c=*z++)
; return o+(c==46?strtod(s,(char**)&amp;z),5:!--z^4); } for(; c==47&amp;&amp; (*z==c||*z==42); ){ for(;
c==*z++; )return m(l),o; for(m(42); z&lt;e			&amp;&amp;*z++-47; --z, m(42)); return o; }
return c==39||c==34?m(c),c:*z++==61&amp;&amp;			 a&amp;64?c|128: a&amp;128&amp;&amp;z[~0]==c?*z==61
&amp;&amp;a&amp;32&amp;&amp;c-45?++z,c|o|128:c|o:a&amp;/*		    2052   */32&amp;&amp;z[~0]==62?o+6:*--z?c:32; }
void g(int l,int O){ for(c=0;				    c&lt;l; ++c)(a=M[s[c]]&amp;16)?--I:M[s
[c]]&amp;1&amp;&amp;M[s[c+1]]&amp;16?--I:0,			  O=O	      ?!a:! a?++A:O; } void f(int T
,int F){ int n; _ o=O; for			 (c=		v&amp;2; H==Z; L-=!(v&amp;2 ||o[~0]
-l),C-=o-O)for(H=0; o&lt;s&amp;&amp;			*o++		 -l; ); O-=O==s &amp;&amp;O[~0]==l;
T-=T==34||T==39? g(F,1),		       0:Z		  ; a=O==s&amp;&amp;s&gt;i; for(A-=T&amp;&amp;
a&amp;&amp;M[O[-1]]-16,!(v&amp;8)&amp;&amp;			      (T|		  c)?h(O,s-O), h(s,F):T; !T
++; H=Z+s[1]-42){ for(			     n=a		   ; c; c^=c)for(I+=F,g(F,n
),n=c=2; c&lt;F&amp;&amp;s[1]==47			    ; ++		   c)a? (a=M[s[c]]&amp;8)||d(s+
n,c-n)&amp;&amp;(I-=c-++n):M[s			   [c]			   ]&amp;8?a= n=c:a; for(c=v&amp;2;
!c;A+=!a&amp;&amp;M[s[F]]-16&amp;&amp;						   s[1]-47)for(c=0; c&lt;F; ++
c)L-=s[c]==l; for(o=s;						   o&gt;O &amp;&amp;*--o-l; ); C-=*o==
l||o==i||O[~0]==l?s-o-						   (*o==l):0; } } int b(int
l){ for(a=0; l--; a+=c-						   59?c==125:-~1) for(a+=a+
a; (c=* F++)== 32||c==9;					  ); return a; } int main (
int S,char**H){ for(s=e=					 M+Z,q= (int*)s,e+=Z/2; *F-
59; *e++=*F++)for(; *F==32				       ; ++F,q[++*q]=e-s); for(q[++
*q]=e-s,z=M,v=b(3); v--; )for				     (z+= b(3),o= b(3),c=b(5); o--;
*z++=c); for(*++e=l=10,O=s=M+4*				   Z,v=b (3); v--; O[o]=b(5))o=b(5)
; for(O+=32,v=0; ~(a=getopt(S,H,O)		       ); )for(v|=s[a&amp;31]; !(a ^~-Z &gt;&gt;2); )
return h(U,~0); for(O+=32,a=0,o=2; c=		   getchar(),o&lt;a|| (i=realloc(i ,a+=Z)),~c;
i[o]=c,c==l+3?v&amp;1&amp;&amp;++E: c==l&amp;&amp;i[~-o]==92 ?--o,++L,v&amp;1?E+=2,++A:A:++o)O ??(c??)&amp;&amp;!(i??(??--o
??)&amp;i??(o-2??)??&#39;63)?o-=2,E+=2,c=O??(c??):0; for(F=e,e=i+o,z=i+=2,*e=0; o=j(); v&amp;1?f(o,a):v
&amp;8?v:v&amp;2||o-Z?~v&amp;32&amp;&amp;r(o,0),h(s,a),z[-1]-l&amp;&amp;h(F,1):0)a=z-s,o-Z?C+=a,++A,I+=v&amp;4&amp;&amp;o==-~Z?1:M[
o]==1&amp;&amp;(M[*z]==16||!*z)?0:a:a; a=e-O; a&amp;&amp;v&amp;1?f(0,a),v&amp;8||h(O,a):a; v&amp;2?C=e-i:0; T*=v&gt;&gt;2&amp;1;R
=C-I-T; C+=E; return v&amp;32?0:v&amp;16?r(I,1):r(L,2)+r(A,2)+r(C,2)+r(I,2)+r(R,2)+r(K,2)+r(T,3); }