#include &lt;stdint.h&gt;
#include &lt;stdio.h&gt;
#include &lt;string.h&gt;
#include &lt;stdlib.h&gt;

#define k 16
#define i 24
#define q(a,b)(w[a]*w[b])
#define u(u)(int)((u[w]&gt;0?1:-1)*.5f+100*u[w])
#define j(j,J)w[j]=w[j]&gt;J?-(J):-w[j];
#define D(D)setvbuf(D,0,_IOFBF,a+1);
#define l(l)(K)(l&gt;a?a:l&gt;-a?l:-a)
#define g(g){fprintf(stderr,&quot;%s\n&quot;,g);return 1;}

typedef int32_t I;
typedef int16_t K;

#define C(A,B) w[2 B]=t[          A[d[A];w[3 B]=w[1 B]+q(4          ,2 B);w[4 B]=w[2 B]-q(3 \
   B,4);z[A*=w[3];z[A+= q(3          B,9);t[A[f[k+A]=z[A;k[f+          A=d[A++;if(d[A&gt;=d[i+A)d[A
     FILE*n=0,*h=0;float*t[i]          ;void m(){if(n)fclose(n)          ;if(h)fclose(h);for(I s=0
       ;s&lt;i;s++)if(s[t])free(s[          t]);}int main(int A,char          **b){I*S=(I*)&quot;V@WDfcvcen&quot;
        &quot;w#vf\4sg\5Gdb&amp;ohwrs&#39;na&quot;          &quot;dm\11`g&#39;}k|\12d~\x7f%{&quot;          &quot;mz\14Nlc*z.a~ja/`ed`ee1&quot;
         &quot;wx~w\22Erev3r}xq5x`fb6&quot;          &quot;ts7&amp;!7zqlk5(4+:yr{uu~w&quot;          &quot;o2\34Otgx&#39;&gt;;)0,y\25[RY&quot;
          &quot;\0MHY\33\4\26F\7\7)tFW&quot;          &quot;\4IM\\\37\0\21A\3\3,bF&quot;          &quot;JWNFO\22\15\35M\14\14 *&quot;
           &quot;**&quot;,a=65535,f[3*i+k],O[          42],*o =O,*c=f+1,*d=f +i          +k,s,v;char*y; float z[i]
           ,X[i],w[21]={1.60f,.30f,          0.5f,.06f,.77f,.965926f,          .258819f,.64731f,.9f};for
            (s=0;s&lt;5;s++)if(A&gt;s+3){s          [w]=strtod(b[s+3],&amp;y);w[          s]/=*y==37?100:/*reverb!!
            v[3]=2&lt;&lt;c[q+k+3];s=3+k+y          printf(&quot;Hello, world!&quot;);          ;w[4]=(w+3)[k-1];)q=3*/1;
            } for(s=0;s&lt;42;s++) s[O]          =S[s]^16843009*(s+1);y=(          char*)o+12;j(1,1)h=fopen(
             1&lt;A?3[b-2]:y+5+k,y);if(!          h)g(y+6)j(3,1)atexit(m);          j(2,1)D(h)if(!fread(f,44,
             1,h))g(y+6)j(1,0)if(*++c          !=*o++||2[--c]!=1[o]||8[          c--]!=*o)g(y+6) w[0]*=(12
             [f]=4[++c]&gt;&gt;k,6[f]);j(0,          6e5f)j(0,-4e3f)j(2, 0)f[          13]=(I)*w+f[10]/(2*12[f])
            ;K*e=(K*)(f+ 10);j(3,1)w          [9]=3[w]&lt;0?1+3[w]:1-w[3]          ;if( 3&lt;=f[12]||(4[c++]&amp;a)
            !=1|| 6[c--]&gt;&gt;k!=k) g(y+          59)7[c]=k/2*(4[c]=5+4*(a          &gt;&gt;=1))-i+20;c[6]=2*c[6]/f
            [12];f[1]=20+(10[f]=f[13          ]&lt;&lt;2)+k;n=fopen(A&gt;2?1[b+          1]:y+28,y+3);if(!n)g(y+36
           )D(n)fwrite(f,28+k,1,n);          printf(y+99,w[0]/6[f],u(          1),u(2),u(3));*X=(*w/=k);
           1[X]=q(0,8);for(s=0;s&lt;i;          s++){if(s&gt;1)s[X]=X[s-2]*          7[w];s[d+i]=(I)s[X];s[z]=
          (s[d]=0);s[f+k]=1;if(s[X          ]&gt;99)f[k-1]=(s-1)|1;s[t]          =calloc(sizeof(float),s[d
         +i]);}while(++f[15]&lt;12);          for(s= 14[f]=0;s&lt;f[13];s          ++){if(f[14]||(10[f+4] =!
        fread(e+1,2*f[12],1,h)))          e[f[12]=1]=0;w[11]=(w[15          ]=w[k]=e[12[f]],w[10]=e[1
       ]);for(v=0; v&lt;i;v+=2){w[          14]=w[11];w[19]=w[k];if(          v&lt;f[15]){C(v],+10)=0;C(v+
     1],+15)=0;}11[w]=q(5,14)          -q(6,19);w[k]=q(6,14)+q(          5,19);}w[k]*=w[2];w[11]*=
   w[2];w[11]+=q(10,1);w[k]          +=q(15,1);w[20]=w[11];1[          e]=l(20[w]);2[e]=l(k[w]);
fwrite(e+1,4,1,n);}}//=w          +=q(32];f[1]=36+(10[f&amp;y)          ;w[s]/=*y==37?1;59)7[c]=k