#include &lt;stdio.h&gt;
#include &lt;stdlib.h&gt;
#include &lt;stdint.h&gt;
#include &lt;string.h&gt;
#define R (z=a=(s*=S)&gt;&gt;31)*n&gt;&gt;32;for(
#define K(x) ))||fseek(F,0,SEEK_##x)||
int main(int c,char**V){int k,l,p,i,x,y
,n,q;uint64_t s,S=5,z;uint32_t*h,a,t[512
];while(c++==5){uint8_t*m;void*F;x=atoi(V
[2]);y=atoi(V[3]);s=atoi(V[4]);if(x&gt;&gt;20||(
#define H(b,x) memset b{for(a=i=0;i&lt;y;)a=(\
a^m[x+i++])*79764919;for(;(i=h[a&amp;q])^-1;a++)
y-1)&gt;&gt;7||!(F=fopen(V[q=1],&quot;rb&quot;K(END)y&gt;(n=fte\
ll(F K(SET)!(m=malloc(n+y))||fread(m,1,n,F)-n
||n&gt;&gt;29)break;;for(fclose(F);S*5&gt;S;)S*=5;for(
i=k=l=0;i&lt;n;)if(&#39;_&#39;-(a=m[i++])){if(a==&#39;&lt;&#39;)for
(a=&#39; &#39;;i&lt;n&amp;&amp;m[i++]-&#39;&gt;&#39;;);;if((a-&#39; &#39;&amp;&amp;a-&#39;\n&#39;&amp;&amp;
a-&#39;\r&#39;&amp;&amp;a-&#39;\t&#39;)||k-(a=&#39; &#39;)) m[l++]=k=a;};n=l;
memcpy(m+l,m,y);for(;l*3&gt;q;)q+=q;if((h=malloc
(4*q))){H((h,-1,4*q--);for(k=0;k&lt;l;h[a&amp;q]=k++
),k);}p=R;x--;p=p-l?p:0){H((t,n=0,8&lt;&lt;8);,p)if
(!memcmp(m+p,m+i,y))k=m[i+y]*2,t[k++]++,n++,t
[k]=i;}n=R k=-1;n&gt;=0;)n-=t[++k*2];putchar(k);
p=t[k+k+1]+1;}putchar(&#39;\n&#39;);c=0;}}return!!c;}
