              /* A long time ago in a galaxy far, far away.... */

int*d,D[9999],N=20,L=4,n,m,k,a[3],i;char*p,*q,S[2000]=&quot;L@X-SGD-HNBBB-AD-VHSG-\
-XNT\x1b[2J\x1b[H&quot;,*s=S,*G=&quot;r2zZX!.+@KBK^yh.!:%Bud!.+Jyh.!6.BHBhp!6.BHBh!:%Bu\
v{VT!.hBJ6p!042ljn!284b}`!.hR6Dp!.hp!h.T6p!h.p6!2/LilqP72!h.+@QB!~}lqP72/Lil!\
h.+@QBFp!:)0?F]nwf!,82v!.sv{6!.l6!,j&lt;n8!.xN6t!&amp;NvN*!.6hp&quot;;/*Stay_on_target.**/
#include/**/&lt;complex.h&gt;/**//*Oh,my_dear_friend.How_I&#39;ve_missed_you.--C-3PO***/
typedef/**/complex/**/double(c);c(X)[3],P,O;c/**/B(double t){double s=1-t,u;P=
s*s*X[1]            +2        *s*t*        *X+t        *t*X       [2]+O;u=I*P;
return+48*((    s=P)+   48*I   )/(   1&lt;u?   u:   1);}   /*   1977  IOCCC2020*/
#include/**    Do.Or   do_not   .   There_is_   no_try...   --Yoda**/&lt;stdio.h&gt;
void/**/b(    double   t,/***   *   **/double   u){double   s=P=B(t)-B(u);(s=P
*(2*s-P))    &lt;1?m=P=B   ((t+   u)/   2),k   =-   I*P,   m&gt;   -41&amp;&amp;m&lt;39&amp;&amp;9&lt;k&amp;&amp;k
&lt;48?             m+=k/        2*80+        73,S        [m]=               S[m]
-73?k%2?S[m]-94?95:73:S[m]-95?94:73:73:1:(b(t,(t+u)/2),b((t+u)/2,u),0);}/*&lt;oo&gt;
_No.             _I_am_            IOCCC           1977                   ***/
#include/*****    your   father..   --DarthVader   **/   &lt;time.h&gt;/****   ****/
int(main)(int    (x),   char**V){;   clock_t(c)=   /*   */clock();;;   for(d=D
;m&lt;26;m++,s    ++)*s&gt;   63?*d++=m%   7*          16-7   *8,*d++=m/   7*25,*d++
=*s-64:0;;    if(V[1])   {;;;FILE   *F   =fopen(V[+1],   &quot;r&quot;);for   (d=D,L=N=m
=0;(x=/**             *            ***              **/            fgetc(F))&gt;0
||fclose(F);)if(x&gt;13?64&lt;x&amp;&amp;x&lt;91?*d++=m*16,*d++=L*25,*d++=x%26:0,m++,0:1)for(++
L;d-D&gt;N*3||(m=0);N++)D[N*3]-=m*8;}for(;i&lt;200+L*25;i++){for(n=0,p=S+33;n&lt;1920;*
p++=n++%80&gt;78?10:32){}for(*p=x=0,d=D;x&lt;N;x++,d+=3){O=(d[1]-i-40)*I+*d;n=d[2];p
=G;for(;n--;)for(;*p++&gt;33;);*a=a[1]=*p++;for(;*p&gt;33;p++)if(*p%2?*a=*p,0:1){a[2
]=*p;for(m=0;m&lt;3;m++){k=a[m]/2-18;q=&quot;/&amp;&amp;&amp;##%%##.+),A$$$$&#39;&amp;&amp;&#39;&amp;&amp;((%-((#&#39;/#%%#&amp;#\
&amp;&amp;#D&amp;&quot;;for(n=2;k--;)n+=*q++-34;X[m]=n%13+n/13*I;}b(0,1);*a=a[1]=*p;}}for(puts(
s),s=S+30;(clock()-c)*10&lt;i*CLOCKS_PER_SEC;);}return 0;}/*Nevertellmetheodds*/